### ISSUE TITLE
Gene Ontology section discrepancies

### ISSUE THREAD

**Issue by ialbert** [biostars/biostar-handbook-issues#1]
A reader reports that links in the 

https://read.biostarhandbook.com/ontology/gene-ontology.html

chapter are non functional.

**Comment by ialbert** [comment]
It appears that the Gene Ontology went through a few major changes on January 8th, 2017. File naming has been changed - in addition we believe that a more major refactoring occured as the results we obtain are sometimes quite different as well.

We have fixed the links so our examples work, but will continue to investigate the matter and update the chapter to reflect the more profound changes that occured.

It goes to show just how much data changes even within two months of the book's release!

**Comment by swernig** [comment]
I recommend including GeneSCF as a tool (http://genescf.kandurilab.org). It's an excellent gene ontology tool that is easy to use and works better that DAVID, as you can see here: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-1250-z

I have personally used this tool in my analysis and got much better results than other GO tools. 

Keep up the good work!

**Comment by ialbert** [comment]
Thanks for the link @swernig  I have not used it yet. I will investigate.

perhaps you'd be interested in starting a markdown page for it :-)

**Comment by ialbert** [comment]
A new issue has been started for GeneSCF

https://github.com/biostars/biostar-handbook-issues/issues/20
