### ISSUE TITLE
xtract command: can not execute binary file

### ISSUE THREAD

**Issue by nkuperwasser** [biostars/biostar-handbook-issues#100]
Hello, I have followed all the steps in the handbook guide (downloaded everything new on Jan 31 2020), activated the bioinfo environment, installed the components according to the Handbook website, and checked that the paths are correct. The entrez-direct utilities all work fine after installation (esearch, efetch, etc etc), excpet for the xtract command. I ran an update on the entrez-direct package as well and still get the same error. Is there something that I am missing? I have been looking through some of the other forums and there may be an issue with the file architecture, and when I did: $file xtract, I got the following details:

xtract: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=PFsOSZjKx4OrmHD5Bwmu/zGzoYroadHkNaH3o3Csi/zAL6g_Cnn3klIv6NBUiS/swsm8RmHeMFF5ZTvvS-e, not stripped

I don't know what all that means, but it appears as it's an executable file, but apparently it can not run....

I am running on macOS Catalina, Intel core i9

Thanks!

NK

**Comment by ialbert** [comment]
This sounds like a packaging error with conda, the xtract program used to be written in perl where the architecture did not matter. The latest version is written in GO and it seems it conflicts with Catalina.

This may take a bit to resolve at the packaging level, for now you can do a:

    conda install entrez-direct=10.2 

to use the previous working version

**Comment by ialbert** [comment]
https://github.com/bioconda/bioconda-recipes/issues/20083

**Comment by ialbert** [comment]
Another quick and dirty fix is to do:

curl https://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/xtract.Darwin > `which xtract`

this will rewrite your copy of xtract with the correct version

**Comment by nkuperwasser** [comment]
Great, thank you very much...the last "quick and dirty fix" using the curl worked (and tested from the example of the Handbook section). Will need to learn more about xtract to check other things in the future, but looks like it's working.

Sincerely

NK

**Comment by ialbert** [comment]
The packaging error has been corrected in bioconda. 

New installations should now work.
