### ISSUE TITLE
RNAseq book- 4. Alignment based RNA-Seq: Create coverage data - "Couldn't open .fai"

### ISSUE THREAD

**Issue by misterchristoff1** [biostars/biostar-handbook-issues#101]
RNAseq book- 4. Alignment based RNA-Seq: Create coverage data - "Couldn't open .fai"
Attempting to convert golden snitch bam files to bigwig format but get 
Couldn't open .fai error

I've installed Jim Kent's bedGraphtoBigWig tool via Conda
I'm in
~/work/golden

cat ids | parallel "bedtools genomecov -ibam  bam/{}.bam -split -bg  > bam/{}.bg"

successfully generates bam files:
~/work/golden/bam
-rw-rw-rw- 1   13013643 Feb 11 09:19 BORED_1.bam
-rw-rw-rw- 1       352 Feb 11 09:20 BORED_1.bam.bai
-rw-rw-rw- 1     393610 Feb 11 12:33 BORED_1.bg
-rw-rw-rw- 1   78718219 Feb 11 09:19 BORED_1.sam
-rw-rw-rw- 1   16387064 Feb 11 09:19 BORED_2.bam
-rw-rw-rw- 1       352 Feb 11 09:20 BORED_2.bam.bai
-rw-rw-rw- 1    424144 Feb 11 12:33 BORED_2.bg
-rw-rw-rw- 1   96641517 Feb 11 09:19 BORED_2.sam
-rw-rw-rw- 1   14263443 Feb 11 09:19 BORED_3.bam
-rw-rw-rw- 1        320 Feb 11 09:20 BORED_3.bam.bai
-rw-rw-rw- 1     407824 Feb 11 12:33 BORED_3.bg
-rw-rw-rw- 1   86386897 Feb 11 09:19 BORED_3.sam
-rw-rw-rw- 1   30704307 Feb 11 09:19 EXCITED_1.bam
-rw-rw-rw- 1       352 Feb 11 09:21 EXCITED_1.bam.bai
-rw-rw-rw- 1     512942 Feb 11 12:33 EXCITED_1.bg
-rw-rw-rw- 1  165860369 Feb 11 09:19 EXCITED_1.sam
-rw-rw-rw- 1   20661914 Feb 11 09:19 EXCITED_2.bam
-rw-rw-rw- 1        352 Feb 11 09:21 EXCITED_2.bam.bai
-rw-rw-rw- 1     451126 Feb 11 12:33 EXCITED_2.bg
-rw-rw-rw- 1  110576819 Feb 11 09:19 EXCITED_2.sam
-rw-rw-rw- 1   25555788 Feb 11 09:19 EXCITED_3.bam
-rw-rw-rw- 1        400 Feb 11 09:21 EXCITED_3.bam.bai
-rw-rw-rw- 1     485397 Feb 11 12:33 EXCITED_3.bg
-rw-rw-rw- 1  137643822 Feb 11 09:19 EXCITED_3.sam

~/work/golden
 cat ids | parallel "bedGraphToBigWig bam/{}.bg  ${IDX}.fai bam/{}.bw"

Couldn't open .fai
Couldn't open .fai
Couldn't open .fai
Couldn't open .fai
Couldn't open .fai
Couldn't open .fai

any advice??
Chris Smith

**Comment by ialbert** [comment]
the samtools index also needs to be created

    samtools faidx $IDX

it is done in the same place as the hisat2 index building

**Comment by misterchristoff1** [comment]
Aha, overlooked that line. Works fine. Thanks. I've learned a lot about IGV from this Golden Snidget dataset. 

We're asked to reflect on coverage using the IGV visualisation ("Is our calculation of coverage (135x) computed in the previous chapter a reasonable approximation for average gene expression?")
The IGV histograms range from 0 to 13735 reads for BORED_2.bw and 0 to 17515 for EXCITED_1.bw.
I'm struggling to assess an average coverage by eye from these histograms. I've gone to this post

https://www.biostars.org/p/5165/

and tried using 

samtools depth BORED_1.bam | awk '{sum+=$3} END { print "Average = ",sum/NR}'

Average =  220.992

seems we have up to double the estimated coverage in some samples (eg Excited_1.bam).
Is samtools depth a reliable method of calculating coverage from a BAM file?

**Comment by ialbert** [comment]
the average should be close, and looks like it is, but individually, as you note the coverage values are radically different, 

the point of the question is to have readers realize that, in RNA-Seq there is a huge disconnect between traditional coverage measures and individual transcript coverages.

**Comment by misterchristoff1** [comment]
ialbert -the average should be close, and looks like it is, but individually the coverage values are radically different,
the point of the question is to have readers realize that, in RNA-Seq there is a huge disconnect between traditional coverage measures and individual transcript coverages.
