### ISSUE TITLE
RNA-Seq by example - 5. Classification based RNA-Seq - not clear example adding reads

### ISSUE THREAD

**Issue by mantvydasl** [biostars/biostar-handbook-issues#102]
In the book it is written:
```
110 reads that cover of the AAAAAAAAAA region
100 reads will have GGGGGGGGG in them,
10 reads will cover TTTTTTTTT.
If we were to simply adding up the reads “naively” as they match the transcripts we would end up with:
200 reads matching AAAAAAAAAAGGGGGGGGG
110 reads matching AAAAAAAAAATTTTTTTTT
```
However, as I add "naively" I get:
110 reads with AAAAAAAAAA + 100 reads with GGGGGGGGG = 210 reads matching AAAAAAAAAAGGGGGGGGG
110 reads with AAAAAAAAAA + 10 reads with TTTTTTTTT = 120 reads matching AAAAAAAAAATTTTTTTTT

**Comment by ialbert** [comment]
Apologies, it sure looks like my counting was excessively naive :-) 

You are correct, the numbers have been changed.

Thanks for reporting the mistake.
