### ISSUE TITLE
DESeq problem!! 

### ISSUE THREAD

**Issue by choisama** [biostars/biostar-handbook-issues#103]
Hello. I am complete beginner and following these tutorials.
But in chapter XXII RNA-Seq example -> Alignment based RNA-Seq of biological data, i encountered problem! (https://www.biostarhandbook.com/rnaseq-align-data.html)

**When i run this script:**

cat simple_counts.txt | Rscript deseq1.r 3x3 > results.txt

**It shows these errors:**
Error in .local(object, ...) : 
  NAs found in size factors. Have you called already 'estimateSizeFactors'?
Calls: estimateDispersions -> estimateDispersions -> .local
Execution halted
(base) 

After getting this error when i try to look at results.txt its empty? I am using ubuntu linux

Thank you

**Comment by ialbert** [comment]
Most likely the file does not contain what it should. Investigate the file first of what it contains.

**Comment by ialbert** [comment]
Also, instead of the chapter you are reading now please follow the **RNA-Seq by Example** book:

https://www.biostarhandbook.com/books/rnaseq/index.html

that book will supersede the chapter in the main volume. It has more examples and more details.
