### ISSUE TITLE
deseq2.r header comments still say edgeR

### ISSUE THREAD

**Issue by njbowen** [biostars/biostar-handbook-issues#104]
#!/usr/bin/env Rscript
#
# The program creates differential expression results using the edgeR method.
#
# Usage:
#
# cat counts.txt | Rscript deseq2.r NxM
#
# Produces a CSV file table with differentially expressed rows printed to the standard output

**Comment by ialbert** [comment]
thanks for the note, fixed, will be pushed out on the next code update.
