### ISSUE TITLE
RNA-seq by example hanbdook -> heatmap.r error cannot visualize heatmap

### ISSUE THREAD

**Issue by choisama** [biostars/biostar-handbook-issues#106]
Good afternoon

Currently i am following RNA-Seq by Example tutorial. but **heatmap.r** shows error and visualization cannot made.
It shows following error:

```
choi@choi-Vostro-3459 ~/Documents/work/golden
$ cat results1.csv | heatmap.r > results2.pdf
/usr/bin/env: 'Rscript --vanilla': No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
(base)

```

how to fix this problem? thank you. i am running ubuntu.

**Comment by ialbert** [comment]
sorry about that, the way the argument is passed works slightly differently on some Unix machines

I thought I fixed all scripts but looks like I missed the heatmap.r

the updated version is now up, download again and should work now

**Comment by choisama** [comment]
Ah thank you so much, I am looking forward to updated version of heatmap.r

**Comment by choisama** [comment]
Thank you so much! it works great
