### ISSUE TITLE
Coronavirus Genome Analysis Guide issue with reformat.py

### ISSUE THREAD

**Issue by Stautis** [biostars/biostar-handbook-issues#107]
Hello, 

I'm currently working my way through the Coronavirus Genome Analysis Guide and am encountering a slight issue. I get to chapter 4.2 where instructions specify to do: 

`pip install pyyaml` and `pip install --upgrade BiostarHandbook`. 

Then, in chapter 4.5.3, it is seemingly indicated that the latter of the two pip install commands should install some scripts, among them reformat.py. However, when running:

`reformat.py -h` 

I get "-bash: reformat.py: command not found". 

Also when doing: 

`python reformat.py -h`, or `locate reformat.py`, 

the file is not found. 

The package is installed in:
`~/miniconda3/lib/python3.7/site-packages`

so I check here for the script file without finding anything.  

Python is located at:
`~/miniconda3/bin/python`

I'm not sure how essential it is to get this step to work with regards to later chapters in the handbook, but any help resolving this would be greatly appreciated. Thanks!

**Comment by ialbert** [comment]
My bad I thought I fixed all instances, the tool has been rewritten, it is now part of the package called `bio`

It should be invoked  as:

    bio metadata

and will print:

```
usage: bio [-h] [-a] [-s]

Reformats NCBI yaml data into tabular form.

optional arguments:
  -h, --help  show this help message and exit
  -a, --acc   print Genbank accession numbers
  -s, --sra   print SRA metadata

```

the usage is:

    cat metadata.yaml | bio metadata -a

I will fix the book in a moment

**Comment by Stautis** [comment]
That works, thanks!

**Comment by ialbert** [comment]
just keep posting issues if you find errors like this, I am trying to track down all code usages, but sometimes I miss certain

**Comment by Stautis** [comment]
Alright, will do
