### ISSUE TITLE
RNA-seq by example: Cannot visualise heatmap 

### ISSUE THREAD

**Issue by AnthonyDohertyTCD** [biostars/biostar-handbook-issues#109]
This command is producing the following error:

cat results1.csv | heatmap.r > results1.pdf
Error: package or namespace load failed for 'gplots' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/anthonydoherty/miniconda3/envs/bioinfo/lib/R/library/KernSmooth/libs/KernSmooth.dylib':
  dlopen(/Users/anthonydoherty/miniconda3/envs/bioinfo/lib/R/library/KernSmooth/libs/KernSmooth.dylib, 6): Library not loaded: @rpath/libopenblasp-r0.3.7.dylib
  Referenced from: /Users/anthonydoherty/miniconda3/envs/bioinfo/lib/R/library/KernSmooth/libs/KernSmooth.dylib
  Reason: image not found
In addition: Warning message:
package 'gplots' was built under R version 3.6.2 
Execution halted

The preceding command below works perfectly for me. 
I cat counts.txt | deseq1.r 3x3 > results1.csv

Any help would be greatly appreciated.

**Comment by ialbert** [comment]
what command did you use to install, I would try removing and reinstalling


'

**Comment by AnthonyDohertyTCD** [comment]
I used URL=http://data.biostarhandbook.com/books/rnaseq/code/install-conda.txt
curl $URL | xargs conda install -y

then: 

curl http://data.biostarhandbook.com/books/rnaseq/code/deseq1.r > ~/bin/deseq1.r
curl http://data.biostarhandbook.com/books/rnaseq/code/deseq2.r > ~/bin/deseq2.r
curl http://data.biostarhandbook.com/books/rnaseq/code/edger.r > ~/bin/edger.r
curl http://data.biostarhandbook.com/books/rnaseq/code/heatmap.r > ~/bin/heatmap.r

then: 

chmod +x ~/bin/*.r

as laid out in the RNA-seq by example differential expression section. 

I am very new to the command line how would I go about removing. 

Thanks for your help

**Comment by ialbert** [comment]
the R package for ggplot seems to have failed to install correctly. You could try redoing the process like so:

    conda remove -y r-gplots

then

    conda install -y r-gplots

**Comment by AnthonyDohertyTCD** [comment]
Many thanks for your help the above solved my issue. 

Unfortunately the following command: cat counts.txt | deseq2.r 3x3 > results2.csv

Produced the below error:

Error: package or namespace load failed for 'DESeq2' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/anthonydoherty/miniconda3/envs/bioinfo/lib/R/library/stringi/libs/stringi.dylib':
  dlopen(/Users/anthonydoherty/miniconda3/envs/bioinfo/lib/R/library/stringi/libs/stringi.dylib, 6): Library not loaded: @rpath/libicui18n.64.dylib
  Referenced from: /Users/anthonydoherty/miniconda3/envs/bioinfo/lib/R/library/stringi/libs/stringi.dylib
  Reason: image not found
In addition: There were 11 warnings (use warnings() to see them)
Execution halted
(bioinfo) 

I subsequently tried to uninstall and install DESeq2 with the following command: 

conda remove -y r-DESeq2

Produced this error: Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are missing from the target environment:
  - r-deseq2

Many thanks again for the quick fixes and responses.

**Comment by ialbert** [comment]
it really feels like somehow the two packages conflict in some way. When you install one it installs the wrong version of the other.

in this case the package is called:

    bioconductor-deseq2

see if you can install and reinstall. But it might be that now that breaks the first tool again.

let's do the following instead:

Make a new environment:

    conda create -y -n rnaseq python=3.6

Activate the new environment and install into it:

    conda activate rnaseq
    URL=http://data.biostarhandbook.com/books/rnaseq/code/install-conda.txt
    curl $URL | xargs conda install -y

Now lets test if everything works:

    wget http://data.biostarhandbook.com/books/rnaseq/data/golden-counts.txt     
    
    cat golden-counts.txt | deseq2.r 3x3 > out.csv

    cat out.csv | heatmap.r > out.pdf

I just did the above and all program run fine for me, but I am on Linux here, not a Mac OS like you but I think it will work.

Now this environment will only have the rnaseq depend programs in it, so if you want to align you need to switch back to `bioinfo`

**Comment by AnthonyDohertyTCD** [comment]
Unfortunately getting this error again:

cat golden-counts.txt | deseq2.r 3x3 > out.csv
Error: package or namespace load failed for 'DESeq2' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/anthonydoherty/miniconda3/envs/rnaseq/lib/R/library/DESeq2/libs/DESeq2.dylib':
  dlopen(/Users/anthonydoherty/miniconda3/envs/rnaseq/lib/R/library/DESeq2/libs/DESeq2.dylib, 6): Library not loaded: @rpath/libopenblasp-r0.3.7.dylib
  Referenced from: /Users/anthonydoherty/miniconda3/envs/rnaseq/lib/R/library/DESeq2/libs/DESeq2.dylib
  Reason: image not found
Execution halted
(rnaseq)

**Comment by ialbert** [comment]
I will need to investigate this on a MacOS system, in the meantime just use the other methods, there are three methods, they produce comparable results and the three methods are just for comparison.

**Comment by AnthonyDohertyTCD** [comment]
Will do. 

Thanks again!

**Comment by ialbert** [comment]
The error appears to come from conda, here is an issue I opened with them.

https://github.com/bioconda/bioconda-recipes/issues/21084

In the meantime a workaround could be to do the following to fix  the package that causes the problem.

`conda install libopenblas==0.3.7`

**Comment by AnthonyDohertyTCD** [comment]
Thank you that fixed the issue for me. I have just one last question. How would I format the desk command to Subset the results for only those with a significant p value and a + or - 1.5fold change. Im not sure what the this command deseq2.r 3x3 produces as default. 

Thank you again for all the help and quick fixes.

**Comment by ialbert** [comment]
The format of the data and what each column there means is explained in detail in the section:

**What do the results mean?**
https://www.biostarhandbook.com/books/rnaseq/differential-expression.html

there you can see that to filter by fold change you would need to select by the column `foldChange`

Now you can do that in many ways, even Excel or at the command line like so, this below should select FDR <0.05 and foldChange > 1.5

    cat results.csv | csvcut -c name,foldChange,FDR | awk -F , '$2>1.5 && $3 < 0.05  { print $1 }'

**Comment by nirjharaloy** [comment]
Hi, the code for the heatmap is running fine on ubuntu but I'm not being ale to run it in R (R studio, R 4.1.0). Codes after 31 didn't run and after loading the gplot, it's only showing this:

# The heatmap row names will be taken from the first column.
# The normalized data starts past the rightmost of these columns.
# The normalized counts are on the right size.
# Load the data from the second column on.
# Adds a little noise to each element to avoid the
# Normalize each row to a z-score
for (i in 1 : nrow(values)) {
# Set the row names on the zscores.
# Turn the data into a matrix for heatmap2.
# Open the drawing device.
# Set the color palette.
# Draw the heatmap.

**Comment by ialbert** [comment]
it is not entirely clear from your description of what is happening,

runs fine on Ubuntu - but not in R? 

Perhaps what you mean is that it runs fine with the R at the command line but not in R via RStudio (is that Windows R?) 

In general, these types of errors mean that you have two different versions of R, and the latter is not set up quite right.

**Comment by nirjharaloy** [comment]
I did set up Ubuntu according to the instructions in the book. I did bulk install all software using this code in Ubuntu:

# Install the  software.
curl -s http://data.biostarhandbook.com/install/conda.txt | xargs mamba install -q -y

I don't know whether R comes with this handbook package. Otherwise, I didn't install R in Ubuntu.

I have been using R studio and R 4.1.0 was installed with it. So, there should not be two versions of R unless R comes with any of the required packages for RNAseq mentioned in the book. 

However, I tried running the heatmap-code again directly on R (not R studio) and it gave me error after loading the ggplot library. It gave me the following errors:

> # Read normalized counts from the standard input.
> data = read.csv("stdin", header=T, as.is=TRUE)
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input

> # Subset data for values under a treshold.
> data = subset(data, data$FDR <= LIMIT)
Error in data$FDR : object of type 'closure' is not subsettable
> 
> # The heatmap row names will be taken from the first column.
> row_names = data[, 1]
Error in data[, 1] : object of type 'closure' is not subsettable

**Comment by ialbert** [comment]
You previously said that the code ran from the command line. That means that you have to have an R that is set up correctly otherwise it would have not run. 

When you install with mamba it does install another R into the bioinfo environment. The R installed with RStudio appears to be a different R altogether. So it is very likely that you have two versions of R installed.

It is possible to run the code in R studio, refer to the book for an example of how to do it:

https://www.biostarhandbook.com/books/rnaseq/rnaseq-setup.html

Specifically, the section titled: **Running our scripts in RStudio** some changes need to be made, for example the original code is reading the command line input, the stdin needs to be changed to your file name.

Though I must ask, if you could run the script from command line, why bother with RStudio?

**Comment by nirjharaloy** [comment]
Thanks Dr. Albert. I'm trying to learn to do it in both methods. (commandline and Rstudio). Although I never liked the R syntax but this what I've been learning and want to use in my statistical analysis and plots for my Exosomal RNAseq, I wanted to understand the use of codes in Rstudio. I'll try again from another PC and let you know. 

Are planning to add a section on RNAseq analysis focused on microRNAs (This question is not related to this thread though, sorry!)

**Comment by nirjharaloy** [comment]
Hi, 

I tried reinstalling Deseq2 in R following the book's instructions. But the heatmap code didn't run. Here's the file of the output:

The
![Screenshot 2022-01-26 11 22 37](https://user-images.githubusercontent.com/97198345/151214813-d6fbc7d7-5838-4b53-9ec1-9cb726a496c1.png)
 codes which do not run, only show the notes on the R console, but not the code.
![Screenshot 2022-01-26 11 22 37](https://user-images.githubusercontent.com/97198345/151214852-56fcdec1-2bc2-45dc-86b8-65999de8a4e2.png)

**Comment by ialbert** [comment]
make sure to make the device a file at line 70 

right now it outputs to the standard out, it will look something like

pdf("filename.pdf")

**Comment by nirjharaloy** [comment]
The pdf file isn't created. Codes after line 36 are not running. They are only showing the notes on the R console. I think I'm missing something trivial. But what is that? Please help.

**Comment by ialbert** [comment]
read the code and understand what it does,

for example, the input needs to be changed as described in the book chapter that I linked above, for both reading the input and saving the output

in your case it looks like you have not changed it, the code needs a few small changes to move it from command line to RStudio,

**Comment by nirjharaloy** [comment]
I did change the Deseq script and that worked in Rstudio. Are there any changes needed to be made in the hitmap and edger script as well? The book only mentioned about the Deseq script, I think.

**Comment by ialbert** [comment]
the exact same logic applies, since both scripts originally worked from command line and now are adapted to run in RStudio

**Comment by ialbert** [comment]
you need to include the entire code, not just one line, the reason you are getting an error there is that something else is not set correctly

**Comment by nirjharaloy** [comment]
I included this entire code at the beginning of the Heatmap code:

"# Command line argument.
args = "3x3"

# Input stream.
infile = "counts.txt"

# Output stream.
outfile = "deseq2-results.csv"

Now, I got this while trying to read the deseq2-results file. Which is the "stdin" or standard input file? The deseq2 and edger result files are in the directory. But still, I'm getting this error in the heatmap-code:

data = read.csv("deseq2-results", header=T, as.is=TRUE)
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'deseq2-results': No such file or directory

**Comment by ialbert** [comment]
the error is clear, you don't have the file present there, 

make sure to run your code in the correct directory, you have to set that in RStudio

**Comment by nirjharaloy** [comment]
Just adding the file extension to the file name solved it. The file was always there. R language is always inconsistent and confusing for me. So, read.csv("deseq2-results.csv") solved the issue. 

Now, what is this issue?
"pdf('|cat', width = WIDTH, height = HEIGHT)
'cat' is not recognized as an internal or external command,
operable program or batch file. 

I have never used the pdf function before. I am clueless!

**Comment by ialbert** [comment]
just put a filename there, the |cat simply opens a stream

pdf("myfile.pdf")

**Comment by nirjharaloy** [comment]
Thank you Dr. Albert! Done. 

My notes for future users on this issue is, it's not always the presence of two versions of R that might affect the codes. I have been using R before taking the course albeit I never liked the R syntax. So, I currently, have two versions of R in my desktop, terminal version worked without any trouble. Here the issue was with adjustments of the code. There were many changes in the code and if there's a space here, I'd love to upload the updated code for Rstudio in windows.

Thanks for the help. It was a nice learning experience.

**Comment by ialbert** [comment]
this is a good point, I should probably add the Rstudio versions to the book, it would not be a big deal. Will do so in the future.
