### ISSUE TITLE
corona virus analysis

### ISSUE THREAD

**Issue by njbowen** [biostars/biostar-handbook-issues#110]
In the section:

How well does nCov cluster with bat SARS?
During our data preparation we obtained the genome files. Let’s combine SARS and nCov:
# Combine genomes.
cat refs/bat-sars-genomes.fa $nCov > work.fa

my "bat-sars-genomes.fa" file was actually "batSARS-genomes.fa"

best,
NJB

**Comment by ialbert** [comment]
Thanks for the proofreading and the reports. 

I will correct these today - each will be closed when the correction is applied.

There was a larger scale renaming at some point, to try to simplify and unify the labeling. Some of these are remnants of that. 

Regardless I will work through all examples in the coming day to make sure all is well.
