### ISSUE TITLE
corona virus analysis

### ISSUE THREAD

**Issue by njbowen** [biostars/biostar-handbook-issues#112]
below you use the term pangolin,  did you mean to do that?

What is the global alignment of nCov and RaTG13?

RaTG13=refs/MN996532.fa
Semi globally align the **pangolin** genome to nCov:

stretcher -filter $nCov $RaTG13  > align.txt

**Comment by ialbert** [comment]
ah, indeed a remnant of a time I was looking for a pangolin virus, fixed
