### ISSUE TITLE
Failed to download human_genome blast database by update_blastdb.pl human_genome --decompress

### ISSUE THREAD

**Issue by arriyaz** [biostars/biostar-handbook-issues#115]
I want to perform a blast against human Refseq. That's I tried to download the human_genome database by using update_blastdb.pl, but unfortunately it gives me the following error message:

```
$ update_blastdb.pl human_genome --decompress
Connected to NCBI
Downloading human_genome (2 volumes) ...
Downloading human_genome.00.tar.gz...Unable to close datastream at /home/arriyaz/miniconda3/envs/bioriyaz/bin/update_blastdb.pl line 316.
Failed to download human_genome.00.tar.gz.md5!
```
Each time I tried the code it downloaded some amount of the file (like 9MB, 8.3MB, 16MB etc) but eventually failed.

How I can download the human_genome database from blast ftp? I need it extremely.

**Comment by ialbert** [comment]
sounds like a network problem, the files are fairly large

note that you can also manually download the desired databases from

ftp://ftp.ncbi.nlm.nih.gov/blast/db/

once downloaded decompress the desired files with:

tar xzvf yourfilename.tar.gz

**Comment by arriyaz** [comment]
In your given link, human_genome contains two files (human_genome.00.tar.gz and human_genome.01.tar.gz).
In this case, do I need to do any kind of concatenation or something like that after unzipping the files?
If I am not wrong these two files are together whole human_genome database for the blast.
In that case which one I should use as database to perform blast.

**Comment by ialbert** [comment]
download both, unpack both, there are many files that make up a single index, all together form the full index

**Comment by arriyaz** [comment]
Thank you very much.
