### ISSUE TITLE
bash permission denied

### ISSUE THREAD

**Issue by mt0030** [biostars/biostar-handbook-issues#117]
Hi,

I am facing a problem with running conda in Ubuntu. It was worked properly lastday after installation. But currently after opening the Ubuntu, it is showing following text- 
 
```
-bash: /home/mtarek/.bashrc: Permission denied
mtarek@DESKTOP-L000DUK:~$ bash
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.
```

```
bash: /home/mtarek/.bashrc: Permission denied
mtarek@DESKTOP-L000DUK:~$ source ~/.bash_profile
bash: /home/mtarek/.bashrc: Permission denied
mtarek@DESKTOP-L000DUK:~$  

```

if you have anyidea, please let me know.

Thank you.

**Comment by ialbert** [comment]
this sounds a bit like you have were logged in as root, installed the tools and everything as root, but now you are trying to run as regular user.

**Comment by mt0030** [comment]
Thank you for your quick response. I have set the conda as regular user and its works.
