### ISSUE TITLE
Miniconda download issues

### ISSUE THREAD

**Issue by stephaniehall123** [biostars/biostar-handbook-issues#119]
I'm trying to download conda but I'm running into the following error:

PackagesNotFoundError: The following packages are not available from current channels:

  - entrez-direct
  - bcftools
  - cutadapt
  - bamtools
  - seqkit
  - htslib
  - minimap2
  - bedtools
  - bowtie2
  - freebayes
  - perl-net-ssleay
  - subread
  - picard
  - parallel
  - pysam
  - blast
  - emboss
  - trimmomatic
  - hisat2
  - bioawk
  - bbmap
  - fastqc
  - samtools
  - sra-tools
  - vt
  - ucsc-bedgraphtobigwig
  - cd-hit
  - seqtk
  - readseq
  - bwa
  - datamash
  - snpeff

I'm not sure what I'm doing wrong.

**Comment by ialbert** [comment]
please ensure that you have enabled the bioconda channel:

```
conda config --add channels bioconda
conda config --add channels conda-forge
```

**Comment by stephaniehall123** [comment]
Thank you for the quick response. I completed your advice and proceeded to the next steps and work this time. No issues with bin doctor, this time.

**Comment by ialbert** [comment]
sounds great.
