### ISSUE TITLE
need help for "Analyzing SAM files"

### ISSUE THREAD

**Issue by shoujungu** [biostars/biostar-handbook-issues#12]
i downloaded: 
efetch -db=nuccore -format=gb -id=AF086833 > AF086833.gb

and then typed
samtools view -c bwa.bam AF086833:470-2689

but it showed:
[main_samview] region "AF086833:470-2689" specifies an unknown reference name. Continue anyway.

Could anyone help me to figure out why this error occur? Thanks!

**Comment by ialbert** [comment]
This error most likely indicates that the alignment was performed against a reference that was named differently.

Viewing the BAM file you can verify how the aligned sequences are named.

**Comment by shoujungu** [comment]
Thanks!
I fixed it.


Shoujun
