### ISSUE TITLE
wget not working

### ISSUE THREAD

**Issue by Biostarhill** [biostars/biostar-handbook-issues#120]
Hi All, I just started the biostar handbook
On the 'Data analysis with Unix' section and the sub section of 'How do I obtain a data file that is online?' , i try to download the SGD file, and get the following.

$ wget http://data.biostarhandbook.com/data/SGD_features.tab 
-bash: wget: command not found

When I use the curl command the whole page shows up in my terminal, but I don't know what to fo after that.
Thank you

**Comment by ialbert** [comment]
do a 

     conda install wget

not sure why they stopped including that by default, it used to be included, 

will update the installation to make this explicit

**Comment by ialbert** [comment]
the installation script has been updated to include `wget` thanks for reporting.

**Comment by Dina3** [comment]
I get this issue though:

dyld: lazy symbol binding failed: Symbol not found: _libiconv_open
  Referenced from: /Users/dina/miniconda3/bin/wget
  Expected in: /usr/lib/libiconv.2.dylib

dyld: Symbol not found: _libiconv_open
  Referenced from: /Users/dina/miniconda3/bin/wget
  Expected in: /usr/lib/libiconv.2.dylib

Abort trap: 6

Any help, please

**Comment by ialbert** [comment]
you should install this into the bioinfo environment

alternatively you can always use `curl` instead of wget with:

`
curl -O http://www.data.org/somefilename.txt

**Comment by Dina3** [comment]
Thank you :) 
Do you mind to explain why the first text files need to be install into the bioinfo environment, please. As I understand, bioinfo environment was in conda - am I right?

Still many thanks

**Comment by ialbert** [comment]
I will agree with you that it should work, but as you can see yourself it does not.

Conda is having a lot of problems as a platform and things that should work do not, so we got to do our best to patch it along.
