### ISSUE TITLE
samtools: library not loaded

### ISSUE THREAD

**Issue by kwhiggins27** [biostars/biostar-handbook-issues#123]
Hello!  I'm trying to complete some of your exercises with samtools, but I keep getting the attached error message.  I checked the directory where samtools is supposed to be saved, and it looks like the program is in there.  

![Screen Shot 2020-07-17 at 5 18 33 PM](https://user-images.githubusercontent.com/68446743/87831549-ccacbc00-c851-11ea-849d-0e20032c9836.png)

**Comment by ialbert** [comment]
An unexpected error for sure, I too can reproduce it.

:ooks like a recent packaging error with bioconda, needs to be elevated on their side.

Until they take care of it install a previous version of samools, for me that solved it:

    conda install samtools==1.9

**Comment by kwhiggins27** [comment]
Thanks very much!

**Comment by ialbert** [comment]
See also this:

https://github.com/bioconda/bioconda-recipes/issues/13488

**Comment by ialbert** [comment]
Actually you might want to pin samtools to 1.10

    conda install samtools==1.10

as it is newer. The main installation has been updated to pin to this version.
