### ISSUE TITLE
Problems installing the bioinformatics software

### ISSUE THREAD

**Issue by Corwyn-A** [biostars/biostar-handbook-issues#124]
curl http://data.biostarhandbook.com/install/conda.txt | xargs conda install -y
xargs : The term 'xargs' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:58
+ ... url http://data.biostarhandbook.com/install/conda.txt | xargs conda i ...
+                                                             ~~~~~
    + CategoryInfo          : ObjectNotFound: (xargs:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
I have the environment set up, however for some reason its not accepting the Linux commands. I have uninstalled and reinstalled ubuntu from the windows store and uninstalled and reinstalled the miniconda. Reseting my computer did not do anything.

**Comment by ialbert** [comment]
The error above means that you are running the command in Powershell and not under Linux.

Make sure to follow the instructions, then start a Linux Bash Shell not a Windows Powershell.
