### ISSUE TITLE
Problem with bioinformatic environment 

### ISSUE THREAD

**Issue by Wisnerlee** [biostars/biostar-handbook-issues#125]
Hi there, 

A beginner for Unix and bioinformatics, I had some problem to set up the bioinformatic environment following the 2nd edition handbook for my MacBook. 

I tried to run the following command line:

(bioinfo) MENGJIAJIANGs-MacBook-Pro:~ mengjiajiang$ curl http://data.biostarhandbook.com/install/conda.txt | xargs conda install -y

In the end, the terminal reported a lot of conflicts of the packages.
 ```

(bioinfo) MENGJIAJIANGs-MacBook-Pro:~ mengjiajiang$ ~/bin/doctor.py
# Doctor! Doctor! Give me the news.
# The ~/bin folder is not in your PATH!
# Checking 11 symptoms...
# ERROR! Missing program: bwa
# ERROR! Missing program: datamash
# ERROR! Missing program: fastqc
# ERROR! Missing program: hisat2
# ERROR! Missing program: seqret
# ERROR! Missing program: subread-align
# ERROR! Missing program: featureCounts
# ERROR! Missinag program: efetch
# ERROR! Missing program: esearch
# ERROR! Missing program: samtools
# ERROR! Missing program: fastq-dump
# Your system shows 12 errors.
# See also: doctor.py --fixme


```
I also tried: 

(base) MENGJIAJIANGs-MacBook-Pro:~ mengjiajiang$ efetch -db nuccore -id 2 -format gb

It worked as showed in the handbook. However, the following command line did not work:

(bioinfo) MENGJIAJIANGs-MacBook-Pro:~ mengjiajiang$ efetch -db nuccore -id 2 -format gb
-bash: efetch: command not found

How should I solve the problem? I just wonder whether it is due to the reason that I install the packages before activate the bioinfo channel!!!

Many thanks for the kind help.
 
Best
Xiang

**Comment by ialbert** [comment]
Yes, you need to install into the bioinfo environment and not into the base environment.

If you did install into the base rather than the bioinfo various problems may occur.

**Comment by Wisnerlee** [comment]
Thanks for the reply. 

I delete and reinstall the miniconda3. Now the efetch works in bioinfo environment. Problem seems to be solved. 

(bioinfo) MENGJIAJIANGs-MacBook-Pro:~ mengjiajiang$ ~/bin/doctor.py 
# Doctor! Doctor! Give me the news.
# The ~/bin folder is not in your PATH!
# Checking 11 symptoms...
# Your system shows 1 error!
# See also: doctor.py --fixme

I still get 1 error. This is due to the "# The ~/bin folder is not in your PATH!", not the environment setup, right?

Many thanks!

Best, 
Xiang

**Comment by ialbert** [comment]
that path error is because you have not applied the bash initialization script that the installation describes here:

https://www.biostarhandbook.com/terminal-init.html

**Comment by Wisnerlee** [comment]
I tried to check the files in the home directory with "ls -a" and the ".bashrc" is missing. Then I run the following command line, close and reopen the terminal.

curl http://data.biostarhandbook.com/install/bashrc.txt >> ~/.bashrc

However, the doctor.py still reports the same error as before. 

Should I delete both the ".bash_profile" and ".bashrc" and download it again? Since it is indicated I should not initialize the terminal twice. 

Many thanks. 

Best, 
Xiang

**Comment by ialbert** [comment]
If you look at the source of 

http://data.biostarhandbook.com/install/bashrc.txt

you will see that it does add the proper PATH setting. If your PATH is not updated it means that you have not followed all commands as indicated and the .bashrc is not loaded up. You should run the second command as well:

It is important to follow all instructions as written here:

https://www.biostarhandbook.com/terminal-init.html
