### ISSUE TITLE
coronavirus taxonkit

### ISSUE THREAD

**Issue by KenSaville** [biostars/biostar-handbook-issues#127]
Hi

When working through the coronavirus chapter, taxonkit wasn't installed.  There is a link in the text that says  bio: software package may need to be updated but it wasn't clear how to do that.

I installed taxonkit using conda install -c bioconda taxonkit

then I needed to download taxdump.tar.gz, unpack it and copy it into the proper place.

after that it worked fine.  But did I miss a step where taxonkit was insatlled via the handbook instructions?

Thanks

Ken

**Comment by ialbert** [comment]
Thanks for the note, it was an oversight,

pleased to see that you figured it out.

To assist future readers we have added the information to the section titled "Using taxonomies to select data" 

https://www.biostarhandbook.com/books/corona/using-taxonomy.html
