### ISSUE TITLE
I can't see the rootfs file in the very beginning

### ISSUE THREAD

**Issue by poss5566** [biostars/biostar-handbook-issues#131]
In the section of Setting up Windows.
After my installation of Ubuntu app, I can't access to the following path:
C:\Users\<Windows UserName>\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\<Ubuntu UserName>

In the LocalState file, but only a file named "ext4" can be found.

What is the error and how can I solve it? 
![pig](https://user-images.githubusercontent.com/74089269/98433975-82a05c80-2106-11eb-9b06-9febcb221453.png)

**Comment by ialbert** [comment]
It appears the directory name has changed. 

Luckily in the meantime I found a  new approach to open an explorer window to your files.

From your Linux bash shell type:

    explorer.exe .

this command will open Windows Explorer showing your Linux files. This will already work as needed.

In addition you can right click any folder and send it to the Desktop (create shortcut) for convenience. 

The book will be updated with this information today.

**Comment by poss5566** [comment]
Thanks a lot for the quick reply

**Comment by ialbert** [comment]
The book has been updated to recommend running:

    exporer.exe .

to pop a view to the files.
