### ISSUE TITLE
Xargs signal error while installing bioinformatics tools

### ISSUE THREAD

**Issue by tiptophamza** [biostars/biostar-handbook-issues#132]
When i enter the code for installing the bioinformatics tools i.e. curl http://data.biostarhandbook.com/install/conda.txt | xargs conda install -y
the following error message occur after a while;
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   306  100   306    0     0    761      0 --:--:-- --:--:-- --:--:--   761
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): - xargs: conda: terminated by signal 9
(bioinfo) 

below is the response from doctor.py
~/bin/doctor.py
# Doctor! Doctor! Give me the news.
# Checking 11 symptoms...
# ERROR! Missing program: bwa
# ERROR! Missing program: datamash
# ERROR! Missing program: fastqc
# ERROR! Missing program: hisat2
# ERROR! Missing program: seqret
# ERROR! Missing program: subread-align
# ERROR! Missing program: featureCounts
# ERROR! Missing program: efetch
# ERROR! Missing program: esearch
# ERROR! Missing program: samtools
# ERROR! Missing program: fastq-dump
# Your system shows 11 errors.
# See also: doctor.py --fixme
(bioinfo) 

PS: I have recreated the environment, deleted miniconda to start afresh the same issue keeps popping up. I even try it on a different linux system but i dont get pass this stage. Kindly assist. Thanks.

**Comment by ialbert** [comment]
Note the following error message:

    Collecting package metadata (repodata.json): - xargs: conda: terminated by signal 9

It indicates the installation did not operate correctly.

you will need to rerun the command:

    curl http://data.biostarhandbook.com/install/conda.txt | xargs conda install -y

**Comment by ialbert** [comment]
But I will give it a go on a new system as well to test it out.

Looks like some sort of conda error.

**Comment by ialbert** [comment]
I have tested out on a new system, the installation proceeds correctly. Now a process being killed by signal 9 means that the operating system does not want to allow it to run.

https://stackoverflow.com/questions/16338884/what-does-exited-abnormally-with-signal-9-killed-9-mean

"Signal 9 means that the application needs to be killed, it is not handled by the process, but by the Linux scheduler. "

For example the application is running out of memory or something similar.

**Comment by tiptophamza** [comment]
Thank you for your swift response. However, how do i fix this issue as it still persist after several try. I also checked the stackoverflow url you shared but no head way as to how to fix it.

Would you suggest i install the 11 missing program identified by doctor.py individually using the command conda install "program name"? or install the entire program on curl http://data.biostarhandbook.com/install/conda.txt indivdually using the same conda command?? 
if No, kindly advice accordingly. Thank you.

**Comment by tiptophamza** [comment]
In a bid to try other alternatives, i downloaded the  http://data.biostarhandbook.com/install/conda.txt using the command:
 wget http://data.biostarhandbook.com/install/conda.txt

then i tried installing using the following command:
conda install r- conda.txt

Bellow is the response gotten.

$ conda install r- conda.txt
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): - Killed
(bioinfo)

**Comment by ialbert** [comment]
it sounds like it is your operating system that is killing the conda program.

try installing one tool at a time, like so

    conda install bwa

(look inside the conda.txt for all the programs it installs, pick a few and see if that installs).

**Comment by tiptophamza** [comment]
I installed manually and observed the signal error was from the entrez file and biopython. I trouble shoot the operating system then try again and booms doctor.py says you are doing well and I am saying to you @ialbert that you are doing well...Thanks
Kindly close this issue as it has been resolved successfully.
