### ISSUE TITLE
Fixing a wrong link

### ISSUE THREAD

**Issue by yamaton** [biostars/biostar-handbook-issues#133]
The page [How to improve the assembly process](https://www.biostarhandbook.com/how-to-improve-the-assembly-process.html) has a wrong internal link; it should be fixed as follows.

```
- https://www.biostarhandbook.com/pattern/kmers.html
+ https://www.biostarhandbook.com/sequence-k-mers.html
```

**Comment by ialbert** [comment]
The link has been corrected (make sure to press reload on the page as it may be cached).
