### ISSUE TITLE
installing bioconductor packages downgrades R

### ISSUE THREAD

**Issue by kristapuciitis** [biostars/biostar-handbook-issues#135]
Hello,

I can successfully setup my conda and bioinfo environment following [How to install conda](https://www.biostarhandbook.com/install-conda.html) and [How to install software](https://www.biostarhandbook.com/install-software.html) on Linux system. R is installed, and `which R` shows
`/home/kristaps/miniconda3/envs/bioinfo/bin/R`, and `R --version` starts with `R version 4.0.3 (2020-10-10) `.

Later following  [https://www.biostarhandbook.com/bio-statistics.html](https://www.biostarhandbook.com/bio-statistics.html) I try to setup bioconductor. Since R is installed from conda, I run `conda install -y bioconductor-deseq  bioconductor-deseq2 bioconductor-edger r-gplots`.

Conda shows
```
The following packages will be SUPERSEDED by a higher-priority channel:

  r-base               conda-forge::r-base-4.0.3-ha43b4e8_3 --> pkgs/r::r-base-3.2.2-0
```
After installation I can't run R anymore. When I launch R it shows `/home/kristaps/miniconda3/envs/bioinfo/lib/R/bin/exec/R: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory`.

---------------

As a side note, conda installs 4.0.2 version of R if I install the bioconductor packages first and only then install packages mentioned in [How to install software](https://www.biostarhandbook.com/install-software.html). What a strange behavior.
Still, I would like to keep the freshest 4.0.3 version.

**Comment by ialbert** [comment]
Apologies, looks like I have forgotten to remove the link to that page. It has been reworked.

The bioconductor-deseq has been deprecated and should not be installed. The proper installation for statistical methods is on the following page:

https://www.biostarhandbook.com/books/rnaseq/rnaseq-statistics.html

**Comment by ialbert** [comment]
In this case you should rerun the environment setup starting with:

conda create --name bioinfo python=3.6 

https://www.biostarhandbook.com/install-software.html

Again apologies for leaving that in, unfortunately conda is unable to handle it graciously.

**Comment by ialbert** [comment]
The outdated installation instructions have been removed from the book.
