### ISSUE TITLE
help with input/output error

### ISSUE THREAD

**Issue by minlr** [biostars/biostar-handbook-issues#141]
Hello! I was doing simulation exercises and after trying to execute perfect.sh script something went wrong. It seems like the script will end up the some output. and there are also some input/output errors. Could someone please help what to do to fix this.
Examples:
After efetch...
![kuva](https://user-images.githubusercontent.com/79216671/108241308-5b6d1880-7154-11eb-9bb5-7fe14b32be00.png)
After bwa mem reference.fa r1.fq r2.fq | samtools sort > align.bam
![kuva](https://user-images.githubusercontent.com/79216671/108241345-658f1700-7154-11eb-95e3-db4efd85a544.png)

**Comment by ialbert** [comment]
the parameter format in `efetch` needs to be `fasta` not `fa` 

unfortunately efetch will return some file (with ASN format)  if you ask for the wrong format

**Comment by minlr** [comment]
Thank you so much! Little thing and everything changes. Now, I got it working.
________________________________
Lähettäjä: Istvan Albert <notifications@github.com>
Lähetetty: keskiviikko 17. helmikuuta 2021 19.34
Vastaanottaja: biostars/biostar-handbook-issues <biostar-handbook-issues@noreply.github.com>
Kopio: Rajamäki, Minna-Liisa O <minna.rajamaki@helsinki.fi>; Author <author@noreply.github.com>
Aihe: Re: [biostars/biostar-handbook-issues] help with input/output error (#141)


the parameter format in efetch needs to be fasta not fa

unfortunately efetch will return the result with ASN format if you ask for the wrong format
