### ISSUE TITLE
Bin folder is not in your path

### ISSUE THREAD

**Issue by dia-dd** [biostars/biostar-handbook-issues#146]
Hello, When I run doctor.py it says the following:
> $ ~/bin/doctor.py
> # Doctor! Doctor! Give me the news.
> # The ~/bin folder is not in your PATH!
> # Checking 11 symptoms...
> # Your system shows 1 error!
> # See also: doctor.py --fixme
I read this [Issue 125](https://github.com/biostars/biostar-handbook-issues/issues/125) which mentioned the same error message but I did the two curl commands and the source command to initialize the terminal mentioned [here](https://www.biostarhandbook.com/terminal-init.html). What am I missing?

**Comment by ialbert** [comment]
your path is not set, perhaps close then reopen your terminal and will go away 

the path is set in one of the curl commands but needs to be applied

**Comment by dia-dd** [comment]
@ialbert thank you for your help again! I must have made a typo somewhere along the way because I went through all the steps a few times and finally got it working.

**Comment by ialbert** [comment]
glad to hear
