### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by beth60197** [biostars/biostar-handbook-issues#147]
Firstly, I love the books! I have found them really helpful. Will there ever be small RNA seq included in later releases?

**Comment by ialbert** [comment]
thanks for the note and endorsement! Much appreciated.

I am finishing the rewrite for the Coronavirus Analysis - once that is done we'll look at the landscape and what people need most, 

take into account the various feedback - like yours - and we'll think about what chapters to redevelop, expand or create as new.

**Comment by beth60197** [comment]
class! looking forward to what comes out next
