### ISSUE TITLE
issue with fastq-dump

### ISSUE THREAD

**Issue by Dzamuk** [biostars/biostar-handbook-issues#149]
Hi, I am stuck with the following error: 
fastq-dump -X 100 -Z SRR1553607 | head
An error occured: std::exception
If this continues to happen, please contact the SRA Toolkit at https://trace.ncbi.nlm.nih.gov/Traces/sra/

fasterq-dump also shows the same error. 
The latest version of sra-tools is installed (2.11.0). 

Could you please help me out? 

Thanks!

**Comment by ialbert** [comment]
What is your operating system?

I found a record of the following error:

https://github.com/ncbi/sra-tools/issues/465

Perhaps rolling it back to a different version would work:

    conda install sra-tools==2.10.8

**Comment by Dzamuk** [comment]
Thank you! My operating system is macOS 11.3.1 (20E241). 

For some reason I am not able to install this version of sra-tools: 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - sra-tools==2.10.8

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by ialbert** [comment]
looks like the version I recommended is available on Linux only, how about:

    conda install sra-tools==2.10.1
    
basically, let's try a version other than 2.11 that may have an inconsistency.

**Comment by Dzamuk** [comment]
Worked! Thank you so much!
