### ISSUE TITLE
Fragment length and SD in Zika example

### ISSUE THREAD

**Issue by gputzel** [biostars/biostar-handbook-issues#15]
This concerns the [Zika example](https://read.biostarhandbook.com/rnaseq/rnaseq-zika-kallisto.html) of kallisto quantification. 

Where do the fragment length of 187 bp and standard deviation of 70 bp come from? It would be helpful to the reader to know how to get this information.

**Comment by aswathyseb** [comment]
The example dataset is based on the following paper from kallisto group. In this they used fragment length of 187 and standard deviation of 70 and hence these numbers. Main document is now updated to include this information.

Paper:
Yi L, Pimentel H, Pachter L (2017) Zika infection of neural progenitor cells perturbs transcription in neurodevelopmental pathways. PLoS ONE 12(4): e0175744. https://doi.org/10.1371/journal.pone.0175744
