### ISSUE TITLE
Setting up conda

### ISSUE THREAD

**Issue by srmcpher** [biostars/biostar-handbook-issues#151]
Hi, I have been trying to set up my computer to get started on the handbook but I seem to be struggling with setting up or activating conda. I set up the environment following the instructions as stated and it seemed to be working like it said it would. However, when I closed the terminal and opened a new terminal it said the command was not found. When I tried to set up the environment again it said that it was already set up and I can only update so I am not sure what I did wrong or if there is just an issue.

Appreciate any help!

**Comment by ialbert** [comment]
this sounds like the path was not set quite right, what  gets printed when you do a:

    ~/miniconda3/bin/conda init

**Comment by srmcpher** [comment]
This is what comes out:
-bash: /home/srmcpher/miniconda/bin/conda: No such file or directory

**Comment by ialbert** [comment]
please note that the command had `miniconda3` in it, 

whereas your command only has `miniconda`

**Comment by srmcpher** [comment]
Sorry, forgot to add that, this is what comes out with miniconda3:
no change     /home/srmcpher/miniconda3/condabin/conda
no change     /home/srmcpher/miniconda3/bin/conda
no change     /home/srmcpher/miniconda3/bin/conda-env
no change     /home/srmcpher/miniconda3/bin/activate
no change     /home/srmcpher/miniconda3/bin/deactivate
no change     /home/srmcpher/miniconda3/etc/profile.d/conda.sh
no change     /home/srmcpher/miniconda3/etc/fish/conf.d/conda.fish
no change     /home/srmcpher/miniconda3/shell/condabin/Conda.psm1
no change     /home/srmcpher/miniconda3/shell/condabin/conda-hook.ps1
no change     /home/srmcpher/miniconda3/lib/python3.8/site-packages/xontrib/conda.xsh
no change     /home/srmcpher/miniconda3/etc/profile.d/conda.csh
no change     /home/srmcpher/.bashrc
No action taken.

**Comment by ialbert** [comment]
There is now a new page with step-by-step installation instructions for troubleshooting the quick setup

https://www.biostarhandbook.com/step-by-step.html
