### ISSUE TITLE
RNA-seq with deseq2 gives different result

### ISSUE THREAD

**Issue by Stealsh** [biostars/biostar-handbook-issues#156]
I'm following the RNA-seq by example and have an issue with deseq2 results using the golden snidget data. 
When I generate the counts.txt, it is exactly the same as that shown (6. The differential expression). However, when I run 
cat counts.txt | deseq2.r 3x3 > deseq2-results.csv

The resulting results.csv shows different numbers than what is shown (6. The differential expression). When I produce the heatmap, it is also different to what is shown, due to those differences in the results.csv.

Has there been a change as to how the DE is calculated? What else could possibly explain this discrepancy? I would like to eventually run analyses on my own data, but this is not inspiring too much confidence.

[deseq2-results.csv](https://github.com/biostars/biostar-handbook-issues/files/7295641/deseq2-results.csv)

**Comment by ialbert** [comment]
Here the important thing is to see if the results are different materially or just the numbers round up a little differently.

Many processes may use bootstrapping or various randomizations, bugfixes may be applied. For example here are the updates for DESEQ2:

https://bioconductor.org/packages/release/bioc/news/DESeq2/NEWS

When I run deseq2 myself I get yet another list of numbers. But again, what really matters is the interpretation, has that remained the same? 

This issue piqued my interest and I will rework the  chapter today. I will check whether  there is any material difference between the two now that DeSeq2 has been updated. 

I will post here once I update the chapter with the outcomes.

Thanks for bringing up this issue, it is definitely something we all need to be aware of.

**Comment by ialbert** [comment]
Looks like the software has changed, it produces additional false positives during evaluations, I will chalk it up to internal changes to the methodology, notably the outputs of edger did not change at all.

The evaluation chapter has been updated with the new values.
