### ISSUE TITLE
Issues loading programs

### ISSUE THREAD

**Issue by theokirkland** [biostars/biostar-handbook-issues#158]
I have previously used the programs from this book without issues.  When I purchased an update problems developed.  I am running these programs on a Mac

The errors were
CondaVerificationError: The package for emboss located at /Users/theoneal/miniconda3/pkgs/emboss-6.6.0-h6debe1e_0
appears to be corrupted. The path 'share/EMBOSS/data/TAXONOMY/names.dmp'
specified in the package manifest cannot be found.
ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/osx-64::perl-compress-raw-bzip2-2.087-pl526h6de7cb9_0, bioconda/osx-64::perl-extutils-makemaker-7.36-pl526_1, bioconda/osx-64::perl-io-zlib-1.10-pl526_2, bioconda/osx-64::perl-json-4.02-pl526_0
  path: 'lib/5.26.2/darwin-thread-multi-2level/perllocal.pod'
ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/osx-64::openjdk-11.0.9.1-hcf210ce_1, conda-forge/osx-64::freetype-2.10.4-h4cff582_1
  path: 'lib/libfreetype.dylib'

When I run doctor.py bwa, fastqc, seqret, subread-align, featureCounts, efetch, esearch, fastq-dump are missing.  I went through the doctor.py --fixme routine without fixing the problem.

Thanks for any help.

**Comment by ialbert** [comment]
I think you need to reinstall everything,

delete the miniconda3 directory

`rm -rf ~/miniconda3`

then start from the beginning. It looks like your conda got damaged big time, harder to fix than starting new

**Comment by theokirkland** [comment]
Thanks for your quick response.  That fixed the problems.

Theo

**Comment by ialbert** [comment]
great to hear
