### ISSUE TITLE
code on p 451 gives error

### ISSUE THREAD

**Issue by theokirkland** [biostars/biostar-handbook-issues#159]
esearch -db gds -query GSE78711 | efetch > sampleinfo.txt 

results in 
curl: (6) Could not resolve host: eutils.ncbi.nlm.nih.gov
 ERROR:  curl command failed ( Sun Nov  7 07:09:54 PST 2021 ) with: 6
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi -d retmax=0&usehistory=y&db=gds&term=GSE78711&tool=edirect&edirect=15.6&edirect_os=Darwin&email=theoneal%40theo-kirklands-macbook-pro.local

What am I doing wrong?

**Comment by ialbert** [comment]
It sounds like you have some sort of internet problem, note how it says that it cannot find the host.

Perhaps try again later. or from a different network.
