### ISSUE TITLE
doctor.py and 

### ISSUE THREAD

**Issue by flyark** [biostars/biostar-handbook-issues#16]
Hi, 

I was using bash on ubuntu on windows, which worked well. At this time, ubuntu version was 15. 

Recently, I did format and re-installed windows as well as bash on ubuntu on windows (version 16). 

I tried to install doctor.py, but experienced the following error. 

mkdir -p ~/bin
curl http://data.biostarhandbook.com/install/doctor.py > ~/bin/doctor.py
chmod +x ~/bin/doctor.py

flyark:~$  ~/bin/doctor.py, 
bash: /home/flyark/bin/doctor.py: /usr/bin/python: bad interpreter: No such file or directory

In addition, I installed wonderdump,which showed the following error. 
mkdir -p ~/bin
curl http://data.biostarhandbook.com/scripts/wonderdump.sh > ~/bin/wonderdump
chmod +x ~/bin/wonderdump

flyark:~$ ~/bin/wonderdump
/home/flyark/bin/wonderdump: line 19: $1: unbound variable

Could you help me how to fix these problems? 
I didn't experience these problems when I used the previous version of bash on ubuntu on windows.

**Comment by flyark** [comment]
I fixed this issue by creating a soft link. (Referred from https://stackoverflow.com/questions/11421399/how-to-fix-bad-interpreter-error-when-using-yum)
=============================
sudo ln -s /usr/bin/python3 /usr/bin/python 
=============================
For anyone who experiences this issue, I hope this is helpful.

**Comment by ialbert** [comment]
Thanks for the note and fix - another solution might be that the script should contain the line:

    #!/usr/bin/env python

but I will need to check that by reinstalling everything.
