### ISSUE TITLE
Setup problems when installing bioinformatic softwares from provided link

### ISSUE THREAD

**Issue by LorenzoGallicchio** [biostars/biostar-handbook-issues#160]
Hi :) I am currently setting up my computer and I am having issues when I need to install bioinformatic softwares, specifically with this command:

_curl http://data.biostarhandbook.com/install/conda.txt | xargs mamba install -y_

which gives back this result on the terminal:

mbbxrlg2@DN2m1i5ur ~
$ curl http://data.biostarhandbook.com/install/conda.txt | xargs mamba install -y
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   237  100   237    0     0   1578      0 --:--:-- --:--:-- --:--:--  1705

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.15.3) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Looking for: ['wget', 'seqkit', 'csvkit', 'parallel', 'entrez-direct', 'minimap2', 'bwa', 'htslib', 'bowtie2', 'emboss', 'bedtools', "samtools[version='>=1.14']", 'sra-tools', 'cutadapt', 'seqtk', 'datamash', 'bcftools', 'freebayes', 'subread', 'bioawk', 'hisat2', 'trimmomatic', 'fastqc', 'snpeff', 'picard', 'blast', 'ucsc-bedgraphtobigwig']

pkgs/main/osx-64         [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/osx-64            [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change

Pinned packages:
  - python 3.8.*

Encountered problems while solving:
  - nothing provides requested seqkit
  - nothing provides requested parallel
  - nothing provides requested entrez-direct
  - nothing provides requested minimap2
  - nothing provides requested bwa
  - nothing provides requested bowtie2
  - nothing provides requested emboss
  - nothing provides requested bedtools
  - nothing provides requested samtools >=1.14
  - nothing provides requested sra-tools
  - nothing provides requested cutadapt
  - nothing provides requested seqtk
  - nothing provides requested datamash
  - nothing provides requested bcftools
  - nothing provides requested freebayes
  - nothing provides requested subread
  - nothing provides requested bioawk
  - nothing provides requested hisat2
  - nothing provides requested trimmomatic
  - nothing provides requested fastqc
  - nothing provides requested snpeff
  - nothing provides requested picard
  - nothing provides requested blast
  - nothing provides requested ucsc-bedgraphtobigwig

(bioinfo) 
mbbxrlg2@DN2m1i5ur ~
$

I am not really sure what is the problem, I also run the doctor script which says that there are 14 files missing (which makes sense considering the error I am getting).

Thanks for the help :)

**Comment by ialbert** [comment]
sounds like you missed the commands to enable the bioconda channels as instructed in a previous chapter: `How to enable bioconda`

enter:

```
conda config --add channels bioconda
conda config --add channels conda-forge
```

then try again

**Comment by LorenzoGallicchio** [comment]
This solved everything! I totally missed that section. Thank you very much.
