### ISSUE TITLE
Version 2.8.0 mismatch for: fastq-dump

### ISSUE THREAD

**Issue by bhagyeshsarode** [biostars/biostar-handbook-issues#163]
I installed the software and currently at the validation step. When I run doctor.py, and it shows the following.

$ doctor.py
# Doctor! Doctor! Give me the news.
# Checking 15 symptoms...
# bwa ... OK
# datamash ... OK
# fastqc -h ... OK
# hisat2 ... OK
# seqret -h ... OK
# featureCounts ... OK
# efetch ... OK
# esearch ... OK
# samtools ... OK
# fastq-dump ... OK
# Version 2.8.0 mismatch for: fastq-dump
# bowtie2 ... OK
# bcftools ... OK
# seqtk ... OK
# seqkit ... OK
# bio ... OK
# Your system shows 1 error!
# See also: doctor.py --fixme
(bioinfo) 

It seems that there is a version mismatch. Is this going to be an issue later on? And if so, how can I update to the correct version?

Thanks

**Comment by ialbert** [comment]
That is not an error, and I thought I fixed that erroneous reporting a few days ago. Perhaps I forgot to publish it.

Did you run the installer today? 

As a fix you can run this to update the doctor:

    curl -s http://data.biostarhandbook.com/install/doctor.py > ~/bin/doctor.py

**Comment by bhagyeshsarode** [comment]
Thank you so much! That fixed it.
