### ISSUE TITLE
doctor.py not found

### ISSUE THREAD

**Issue by KenSaville** [biostars/biostar-handbook-issues#164]
Hi

I'm setting up in ubuntu on windows.  I seem to be making progress, but  the doctor.py step didn't work.

I entered the command
curl http://data.biostarhandbook.com/install.sh | bash

I did not get  the
 "# Biostar Handbook installation complete!" 
message

but was able to activate the bioinfo environment

the doctor.py command says command not found.

I don't see the doctor.py file in the current directory, so maybe it didn't download.

**Comment by ialbert** [comment]
make sure to open a new terminal to apply the new settings, (or run the source command as shown)

the program is installed in ~/bin/ folder

you could run it as ~/bin/doctor.py

**Comment by KenSaville** [comment]
Thanks

I had started a new terminal

I tried ~/bin/doctor.py still no luck

**Comment by ialbert** [comment]
Let's try it manually then, these are the commands the install script would want to execute:

    conda activate bioinfo

then 

```
# Install the doctor.py 
mkdir -p ~/bin
curl -s http://data.biostarhandbook.com/install/doctor.py > ~/bin/doctor.py
chmod +x ~/bin/doctor.py
```

then

    curl -s http://data.biostarhandbook.com/install/conda.txt | xargs mamba install -q -y

then:

    pip install bio -q --upgrade

**Comment by KenSaville** [comment]
will do

thanks

**Comment by KenSaville** [comment]
$ curl -s http://data.biostarhandbook.com/install/conda.txt | xargs mamba install -q -y                                 xargs: mamba: No such file or directory

**Comment by KenSaville** [comment]
doctor.py runs now but says I have 15 errors

**Comment by ialbert** [comment]
I see, it looks like the mamba install did not succeed, then it needs:

     conda install mamba -q -n base -c conda-forge -y

then rerun the command that failed

**Comment by KenSaville** [comment]
Ecountered problems while installing:
nothing provides

**Comment by KenSaville** [comment]
nothing provides requested seqkit

etc

says this for all 15 programs

**Comment by ialbert** [comment]
ok the channels are also missing, I thought that ought to have worked, 

 I'll write the manual commands up in a new chapter,  for now do

```
conda config -q --add channels bioconda
conda config -q --add channels conda-forge
```

then rerun the 

    curl -s http://data.biostarhandbook.com/install/conda.txt | xargs mamba install -q -y

**Comment by KenSaville** [comment]
That worked.

Thanks

doctor.py said all are OK

Thanls again

**Comment by KenSaville** [comment]
actually it says I'm missing a program called bio.  But I can worry about that later I'm sure

**Comment by ialbert** [comment]
This installs `bio`

     pip install bio -q --upgrade

so I gather the rest worked?

**Comment by KenSaville** [comment]
yes the others worked.

**Comment by KenSaville** [comment]
I am doing well!!

thanks
