### ISSUE TITLE
Installing Visual Studio

### ISSUE THREAD

**Issue by eflasch** [biostars/biostar-handbook-issues#167]
I am running ubuntu on an Oracle VM Virtual Box on a Windows 10 machine. I would like to install  the VS Code text editor as per Biostar recommendation. Where do I download to- the Windows machine? the Virtual Box (how)? and into what folder?
Thank you

**Comment by ialbert** [comment]
if you are running VirtualBox then you should be running it via the VirtualBox and its Graphical interface.

I would recommend using the Linux Subsystem instead - it will cause a whole lot less trouble.
