### ISSUE TITLE
make vcf error (doctor.py in working order)

### ISSUE THREAD

**Issue by eotf** [biostars/biostar-handbook-issues#168]
Hello,
I am getting this error after trying to run through the introductory exercise.

$ make vcf
mkdir -p reads
fastq-dump -F -X 10000 --split-files -O reads SRR1553425
Failed to call external services.
make: *** [Makefile:110: reads/SRR1553425_1.fastq] Error 64

Any suggestions?
Im on Ubuntu Win 10.

**Comment by ialbert** [comment]
It sounds like some problems with your internet connection:

https://github.com/ncbi/sra-tools/issues/302

**Comment by ialbert** [comment]
Also:

https://www.biostars.org/p/9475091/

**Comment by eotf** [comment]
Thank you. Just fyi, I had so much trouble with WSL (went through all the SSL, mamba, and HTTPS error posts) that I ended up doing a fresh Ubuntu install on my old laptop and everything works perfectly there.
