### ISSUE TITLE
Trouble installing software from the link in windows 10

### ISSUE THREAD

**Issue by nirjharaloy** [biostars/biostar-handbook-issues#169]
Hi,

I'm using windows 10 and 
Whenever I trying to use this code,
$ curl http://data.biostarhandbook.com/install.sh | bash
I'm getting this:
**xargs: mamba: No such file or directory**

The code worked fine in Mac.

**Comment by ialbert** [comment]
I will provide step by step instructions that can will better identity for me what exactly is going off track

in the meantime see this:

https://github.com/biostars/biostar-handbook-issues/issues/164

also I would look at the code

     curl http://data.biostarhandbook.com/install.sh > install.txt

then view the code in a test editor and attempt to run each line separately to see what exactly is going wrong

**Comment by ialbert** [comment]
I have published a new section titled: **Step by step installation**

https://www.biostarhandbook.com/step-by-step.html

Could you please follow those steps then report which step (if any fails). The automated script runs through those commands in a single step.

**Comment by nirjharaloy** [comment]
Thanks Dr. Albert,

I tried this from your previous suggestion and it worked:
Let's try it manually then, these are the commands the install script would want to execute:

conda activate bioinfo
then

# Install the doctor.py 
mkdir -p ~/bin
curl -s http://data.biostarhandbook.com/install/doctor.py > ~/bin/doctor.py
chmod +x ~/bin/doctor.py
then

curl -s http://data.biostarhandbook.com/install/conda.txt | xargs mamba install -q -y
then:

pip install bio -q --upgrade

However, I appreciate the new chapter. I have found some other minor issues in the RNA-seq by steps. I'll discuss those in this forum.

**Comment by njbowen** [comment]
I've been troubleshooting the install with students on Windows 10 and Ubuntu 20 LTS, 
using the step by step method, it appears to fail somewhere in the conda install or update.  Often it is an https connection error, sometimes due to the student's particular firewall settings, or Norton antivirus app or wifi proxy settings.
