### ISSUE TITLE
Where is the physical location of ubuntu directory?

### ISSUE THREAD

**Issue by nirjharaloy** [biostars/biostar-handbook-issues#170]
Hi,

I'm new to linux. I wonder where is the physical location of the ubuntu directory in the hard drive? Some times I need to physically locate and fetch the genome and the alignment files to see them with the IGV. I couldn't find this apparently simple answer in any forum but my search could have been wrong. How to find the physical location of downloaded files with ubuntu commands?

**Comment by ialbert** [comment]
The information is covered in the book 

https://www.biostarhandbook.com/setup-windows.html

scroll to the sections:

- How do I see the Unix filesystem from Windows?
- Alternative approach for accessing your Linux files

**Comment by nirjharaloy** [comment]
Got it. 
explorer.exe .

code seems to be the best solution.
Thanks a lot!

**Comment by EMDLvdHeijden** [comment]
Evening,

I am struggling to set-up a shortcut to the unix filesystem on my windows laptop. I am following the set-up for windows and have just installed Ubuntu. If I use `explorer.exe .` I get a windows explorer window, but the path that gives me is on the network drive and if I try to make a shortcut to that it tells me it cannot be found. If I try to navigate to the folder manually (after making hidden files visible) I get upto the "LocalState" folder, but the "rootfs"folder doesn't exist on my system. There's only a file "ext4". Not sure how important this is also? Will I still be able to access my windows files from Ubuntu and vice versa without it?

Sorry if I'm missing simple things. I haven't worked on a Windows-based computer in a long time.

Thanks,
Elise

**Comment by ialbert** [comment]
Once you have the explorer window you can right-click any folder (even the main folder if you step one level up) and select Send to Desktop

this action will create a shortcut 

as for the LocalState, they may change the location, perhaps poke around a bit, perhaps they moved it to ext4

**Comment by EMDLvdHeijden** [comment]
Ah, great, thanks a lot - the "Send to Desktop" suggestion worked. (The "ext4" is a hard disk image file and there's nothing else in the "LocalState folder". But anyway, I have the shortcut now. Thanks!
