### ISSUE TITLE
RNA-seq by example chapter 6

### ISSUE THREAD

**Issue by nirjharaloy** [biostars/biostar-handbook-issues#173]
The code: 
**cat counts.txt | deseq2.r 3x3 > deseq2-results.csv**

is giving me this error message:
$ cat counts.txt | deseq2.r 3x3 > deseq2-results.csv
Error: package or namespace load failed for 'GenomeInfoDb' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called 'GenomeInfoDbData'
Error: package 'GenomeInfoDb' could not be loaded
In addition: Warning messages:
1: package 'DESeq2' was built under R version 4.1.1
2: package 'S4Vectors' was built under R version 4.1.1
3: package 'BiocGenerics' was built under R version 4.1.1
4: package 'IRanges' was built under R version 4.1.1
5: package 'GenomicRanges' was built under R version 4.1.1
6: package 'GenomeInfoDb' was built under R version 4.1.1
Execution halted
(bioinfo)

**Comment by ialbert** [comment]
Sounds like a Bioconductor package installation problem.

There are some tips there on how to troubleshoot command line bioconductor , perhaps make a new stats environment.

you can also run the package via RStudio in  a Graphical User Interface, that way you are running the native R

this is also described in the RNA-Seq software installation

**Comment by nirjharaloy** [comment]
I have a stats environment. But I ran this in the bioinfo environment. Should I run it in stats environment?

**Comment by nirjharaloy** [comment]
worked fine in stats environment. Please add a note to activate stats before running these codes.

**Comment by ialbert** [comment]
looks like a typo, should be 

    cat edger-results.csv | heatmap.r >edger-heatmap.pdf
    
 the book has now been corrected, reload the page to see the fix

**Comment by nirjharaloy** [comment]
Thanks for the correction!

**Comment by nirjharaloy** [comment]
Now, what's happening here?

$ cat counts.txt | head -1 | cut -f 7-12
# Program:featureCounts v1.6.4; Command:"featureCounts" "-p" "-a" "refs/features.gff" "-o" "counts.txt" "bam/BORED_1.bam" "bam/BORED_2.bam" "bam/BORED_3.bam" "bam/EXCITED_1.bam" "bam/EXCITED_2.bam" "bam/EXCITED_3.bam"
(stats)

**Comment by ialbert** [comment]
Asking questions like this is not the purpose of the site. You have to have specific questions that demonstrate that there is actually a problem - not that perhaps you are not sure of what you see, we do not typically chain up different questions either

there is a lot of self study that goes with bioinformtatics.

**Comment by nirjharaloy** [comment]
Sorry for the ambiguity. I was trying to understand all the codes in this chapter and noting down the questions in this chapter. That's why I chained up.

$ cat counts.txt | head -1 | cut -f 7-12

this code did not run properly and showed me the sentences printed in bold in the previous comment. I ran it in stats environment. 

And the final two codes in this chapter 
cat results.csv | heatmap.r > output.pdf

should they be like this? (because we didn't create any file named results.csv)
cat deseq2-results.csv | heatmap.r > output.pdf
or cat edger-results.csv | heatmap.r 3> output.pdf

**Comment by ialbert** [comment]
the code:

    cat results.csv | heatmap.r > output.pdf

indicates the generic way to run the tool, the results generated with deseq2 or edger would be piped into the heatmap.r

the idea was that both scripts generate output in way that are compatible, later on the examples are specific to the actual filenames

as for the 

   cat counts.txt | head -1 | cut -f 7-12
   
it prints what you have in the file. Is your file correct? Check the book and the expectations. If the counts.txt file is not quite right, then one of the previous steps might not be quite right and you need to go back to check those.

making mistakes and getting weird results is completely normal, I make tens of mistakes per hour, where a file is not quite what I thought it should be, the solution is always the same, going back step by step and validating the process

**Comment by nirjharaloy** [comment]
Thanks a lot Dr. Albert. 
I checked the counts.txt file. It looks okay. For unknown reasons, the code 
cat counts.txt | head -1 | cut -f 7-12

is printing the header instead of the numbers in column 7-12. I was able to run all the other codes eventually.

**Comment by ialbert** [comment]
you are limiting to the first line with head -1, 

then it looks like the first line is not tab-delimited data, it shows the original invocation, 

now there is an odd behaviour to cut, when the number of columns exceeds the valid columns it returns the first field

https://unix.stackexchange.com/a/465596
