### ISSUE TITLE
samtools install error

### ISSUE THREAD

**Issue by njbowen** [biostars/biostar-handbook-issues#175]
$ curl -s http://data.biostarhandbook.com/install/conda.txt | xargs mamba install -q -y
Encountered problems while solving.
Problem: package samtools-1.14-hdbfa7a9_0 requires htslib >=1.14,<1.15.0a0, but none of the providers can be installed

(bioinfo) 

seems that the samstools htslib install is not working for me.  
on an iMac intel

**Comment by ialbert** [comment]
what happens if you install just samtools alone:

   mamba install samtools

one recurring problem that leads to mysterious errors is when the MacOS is bit out of date (or the XCode component is not quite updated)

**Comment by njbowen** [comment]
from within a preexisting conda bioinfo environment: mamba install samtools seems to have worked ok, i should add, I was trying to do the "new install script" on a machine that was already set up last semester.  i use your textbook in course instruction  and was trying to get ahead of any troubleshooting.  this action might not have been advised, it may not have this issue on "virgin" machines.

**Comment by njbowen** [comment]
here's what I'm getting now when running the current install script (maybe I should start in a newly created conda env or start in base) on a machine that already has conda/mamba installed. 
nbowen@4210-iMac-3 ~
$ curl http://data.biostarhandbook.com/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2766  100  2766    0     0   8904      0 --:--:-- --:--:-- --:--:--  8951

# Bootstrapping the Biostar Handbook ...

# Installing bioinformatics software
Encountered problems while solving.
Problem: nothing provides requested r-base >=4
Problem: nothing provides requested samtools >=1.14
Problem: nothing provides requested mafft

(bioinfo) 
nbowen@4210-iMac-3 ~
$

**Comment by ialbert** [comment]
it is true that perhaps I have not explored all possible ways to run the install script,

the way it works is that it will bootstrap everything, even conda itself.

I will explore a little more closely what happens if one already a bioinfo environment present

to see it work on a brand new system delete every conda related content

    rm -rf ~/miniconda3 ~/minicond*.sh ~/.condarc ~/.conda 

(you may want to also edit bashrc to remove the conda initialization)

then reopen the terminal and run the installation command again

**Comment by njbowen** [comment]
the reset worked.  thanks.
