### ISSUE TITLE
"initialize the terminal" link from bottom of Mac OS setup page is not redirecting in web version of biostar-handbook

### ISSUE THREAD

**Issue by njbowen** [biostars/biostar-handbook-issues#178]
this link at the bottom of the web page for Mac OS in appendix is not redirecting for me, at least, using Chrome on Mac OS 12.1: 

https://www.biostarhandbook.com/setup-macos.html#terminal-init

**Comment by ialbert** [comment]
The issue has been corrected in

https://www.biostarhandbook.com/setup-macos.html

The page needs to be reloaded manually to get the updated version
