### ISSUE TITLE
lecture11.sh failed

### ISSUE THREAD

**Issue by flyark** [biostars/biostar-handbook-issues#18]
I generated lecture11.sh based on 10 page of lecture 11 ppt slide and executed "bash lecture11.sh". 
However, I experienced this error. I think "wget" in lecture11.sh file didn't work because wget works well when this is directly executed. I am using windows 10 bash. Is there any hint?

```
~/unix$ bash lecture11.sh
lecture11.sh: line 2: $'\r': command not found
lecture11.sh: line 5: $'\r': command not found
--2017-09-26 14:30:56--  http://data.biostarhandbook.com/data/sequencing-platform-data.tar.gz%0D
Resolving data.biostarhandbook.com (data.biostarhandbook.com)... 198.74.58.207
Connecting to data.biostarhandbook.com (data.biostarhandbook.com)|198.74.58.207|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-09-26 14:30:57 ERROR 404: Not Found.

lecture11.sh: line 8: $'\r': command not found
tar (child): sequencing-platform-data.tar.gz\r: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
lecture11.sh: line 11: $'\r': command not found
' which didn't exist, or couldn't be read
lecture11.sh: line 14: $'\r': command not found
TrimmomaticSE: Started with arguments:
 illumina.fq better.fq SLIDINGDOWN:4:30
Automatically using 4 threads
Exception in thread "main" java.lang.RuntimeException: Unknown trimmer: SLIDINGDOWN
        at org.usadellab.trimmomatic.trim.TrimmerFactory.makeTrimmer(TrimmerFactory.java:70)
        at org.usadellab.trimmomatic.Trimmomatic.createTrimmers(Trimmomatic.java:59)
        at org.usadellab.trimmomatic.TrimmomaticSE.run(TrimmomaticSE.java:303)
        at org.usadellab.trimmomatic.Trimmomatic.main(Trimmomatic.java:85)
lecture11.sh: line 17: $'\r': command not found
' which didn't exist, or couldn't be read
lecture11.sh: line 20: $'\r': command not found

```
<lecture11.sh>
```
# Comments start with the # sign.

# Work at the command line. 
# If it works, copy it into this file. 


# Get the example dataset for lecture 11.
wget http://data.biostarhandbook.com/data/sequencing-platform-data.tar.gz

# The file unpacks into 4 sequencing datasets. 
tar zxvf sequencing-platform-data.tar.gz

# Quality plots before trimming.
fastqc illumina.fq

# Trim back by quality. 
trimmomatic SE illumina.fq better.fq SLIDINGDOWN:4:30

# Quality plots after trimming. 
fastqc better.fq
```

**Comment by ialbert** [comment]
The file is using windows line endings. Change them to Unix line
endings.
It is a setting that a good text editor can apply for you:

https://www.biostarhandbook.com/setup/setup.html?h=line%20endings


--
Istvan Albert
Professor of Bioinformatics
Pennsylvania State University
https://www.ialbert.me


On Tue, Sep 26, 2017, at 01:43 AM, flyark wrote:
> I generated lecture11.sh based on 10 page of lecture 11 ppt slide and
> executed "bash lecture11.sh".>  However, I experienced this error. I think "wget" in lecture11.sh
>  file didn't work because wget works well when this is directly
>  executed. I am using windows 10 bash. Is there any hint?


> ~/unix$ bash lecture11.sh lecture11.sh: line 2: $'\r': command not
> found lecture11.sh: line 5: $'\r': command not found --2017-09-26 14:30:56--
> http://data.biostarhandbook.com/data/sequencing-platform-data.tar.gz%0D
> Resolving data.biostarhandbook.com (data.biostarhandbook.com)...
> 198.74.58.207 Connecting to data.biostarhandbook.com
> (data.biostarhandbook.com)|198.74.58.207|:80... connected. HTTP
> request sent, awaiting response... 404 Not Found 2017-09-26 14:30:57
> ERROR 404: Not Found.  lecture11.sh: line 8: $'\r': command not found
> tar (child): sequencing-platform-data.tar.gz\r: Cannot open: No such
> file or directory tar (child): Error is not recoverable: exiting now
> tar: Child returned status 2 tar: Error is not recoverable: exiting
> now lecture11.sh: line 11: $'\r': command not found ' which didn't
> exist, or couldn't be read lecture11.sh: line 14: $'\r': command not
> found TrimmomaticSE: Started with arguments: illumina.fq better.fq
> SLIDINGDOWN:4:30 Automatically using 4 threads Exception in thread
> "main" java.lang.RuntimeException: Unknown trimmer: SLIDINGDOWN at or-
> g.usadellab.trimmomatic.trim.TrimmerFactory.makeTrimmer(TrimmerFactor-
> y.java:70) at org.usadellab.trimmomatic.Trimmomatic.createTrimmers(Tr-
> immomatic.java:59) at
> org.usadellab.trimmomatic.TrimmomaticSE.run(TrimmomaticSE.java:303) at
> org.usadellab.trimmomatic.Trimmomatic.main(Trimmomatic.java:85)
> lecture11.sh: line 17: $'\r': command not found ' which didn't exist,
> or couldn't be read lecture11.sh: line 20: $'\r': command not found

>> <lecture11.sh>


> # Comments start with the # sign.  # Work at the command line. # If it
> # works, copy it into this file.   # Get the example dataset for
> # lecture 11. wget
> # http://data.biostarhandbook.com/data/sequencing-platform-data.tar.gz
> # # The file unpacks into 4 sequencing datasets. tar zxvf sequencing-platform-
> # data.tar.gz  # Quality plots before trimming. fastqc illumina.fq  #
> # Trim back by quality. trimmomatic SE illumina.fq better.fq
> # SLIDINGDOWN:4:30  # Quality plots after trimming. fastqc better.fq
>> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 


Links:

  1. https://github.com/biostars/biostar-handbook-issues/issues/18
