### ISSUE TITLE
Fix link

### ISSUE THREAD

**Issue by lshepard2154** [biostars/biostar-handbook-issues#19]
Hi,

First, great job on the book. I like to take a look at it whenever I have time. Just wanted to report that one of your links [here](https://www.biostarhandbook.com/data/fastq-sequence-duplication.html) which was supposed to lead to a BioStar post, is actually going to the picard manual of MarkDuplicates.

Nothing major, but I wanted to report it as I know it is not what you meant to add :)

**Comment by ialbert** [comment]
Thanks for the report. Fixed now - should appear shortly.
