### ISSUE TITLE
"samtools sort" command is not working

### ISSUE THREAD

**Issue by arriyaz** [biostars/biostar-handbook-issues#194]
When I tried to run the `make-bam.sh` from the **How to make a bam file** chapter following error is showing:

![ksnip_20220313-172642](https://user-images.githubusercontent.com/48599524/158057313-a633639f-999d-4bc3-aafc-d366307d72b8.png)

Then I tried to run the code line by line. But now I am getting errors from the following line of code:
```bash
# Align with bwa mem.
bwa mem $FA $R1 $R2 | samtools sort > $SRR.bwa.bam

#and 

# Align the same data with bowtie2.
bowtie2 -x $FA -1 $R1 -2 $R2 | samtools sort > $SRR.bowtie.bam
```
The error message is like as bellow:
![image](https://user-images.githubusercontent.com/48599524/158057447-2d1d088b-4ff8-4b42-a6c3-53d4c2518b5e.png)

So, I guess the problem is with the `samtools sort` command. I think here we should mention an option. But I'm not sure which one I should use. Moreover, in the book, there was no option used after the `samtools sort` command.

Can somebody help me, please?

**Comment by ialbert** [comment]
this looks like you have an older version of samtools that needs additional parameters to work the same way as the newer versions

try this:

    bowtie2 -x $FA -1 $R1 -2 $R2 | samtools sort -o  - > $SRR.bowtie.bam

note how there is both a `-o` and a `-` there

in general the proper troubleshooting is to run one step at a time, make a SAM file, then sort the SAM file

**Comment by arriyaz** [comment]
Thank you very much.
