### ISSUE TITLE
Access the files from both Linux and with Windows Explorer

### ISSUE THREAD

**Issue by LPain** [biostars/biostar-handbook-issues#22]
Hello everyone,

I would like to access the files from both Linux and with Windows Explorer, following instructions from "How do I set up the filesystem with Ubuntu on Windows?" with the bash for ubuntu terminal

So I typed:
mkdir -p '/mnt/c/Users/Lpain/Desktop/unix'

then

ln -s  '/mnt/c/Users/Lpain/Desktop/unix' ~/unix 

I have a folder named "unix" inside the Linux terminal but not visible in my Desktop under Windows..

Does somebody have any idea/suggestion  of what i can fix it?

Many thanks in advance

**Comment by ialbert** [comment]
I think it is there just not visible because something else perhaps is covering it.

do a

ls '/mnt/c/Users/Lpain/Desktop/'

and see if you can see other folders

**Comment by LPain** [comment]
Thank you very much, it was effectively that and my file'unix' appeared on my Desktop
