### ISSUE TITLE
update_blastdb.pl --showall | head

### ISSUE THREAD

**Issue by flyark** [biostars/biostar-handbook-issues#23]
In slide #15 in lec 14, there is a code like 
```
update_blastdb.pl --showall | head

16SMicrobial
cdd_delta
env_nr
```

When I ran update_blastdb.pl, this showed up. 

```
update_blastdb.pl --showall | head
Connected to NCBI

update_blastdb.pl --decompress 16SMicrobial
Connected to NCBI
16SMicrobial not found, skipping.
```

No 16SMicrobial or etc after the phrase "Connected to NCBI". (I'm using Bash on Ubuntu on Windows)

Should I get the data first? I downloaded  "16SMicrobial.tar.gz" by 
`wget ftp://ftp.ncbi.nlm.nih.gov/blast/db/16SMicrobial.tar.gz`

I couldn't have found how to get or store the data. Could you explain the detailed procedure?

Thank you in advance.

**Comment by ialbert** [comment]
Indeed there is something not working quite right with the `update_blastdb.pl` command when used on Windows Bash. It hangs and does not produce output with 

     update_blastdb.pl --showall 

My guess is that Windows Bash seems to block it. I will have to investigate. - this is a new symptom, I am quite sure this used to work with no problems. 

In the meantime your proposed solution is correct. The `update_blastdb.pl`  scripts basically downloads files from the web and unpacks them for us. The command that you would need to run is:

```
wget ftp://ftp.ncbi.nlm.nih.gov/blast/db/16SMicrobial.tar.gz
tar -xzvf 16SMicrobial.tar.gz
```

**Comment by ialbert** [comment]
Update:

the tool will work if the additional `--passive` flag is speficifed. This flag helps it bypass firewall limitations.

    update_blastdb.pl --passive --showall | head -2
    update_blastdb.pl --passive --decompress 16SMicrobial
