### ISSUE TITLE
Installation of miniconda

### ISSUE THREAD

**Issue by akgreat22** [biostars/biostar-handbook-issues#240]
I had issues with my Ubuntu and I needed to re-install from scratch. 

When I tried installing miniconda using the link from the Biostar handbook, I got the following error;

curl: (6) Could not resolve host: bash
curl: (6) Could not resolve host: Miniconda3-latest-Linux-x86_64.sh

How do I resolve this?

**Comment by ialbert** [comment]
looks like you are typing in something like:

      curl bash Miniconda3-latest-Linux-x86_64.sh

doing so produces the error:

```
curl: (6) Could not resolve host: bash
curl: (6) Could not resolve host: Miniconda3-latest-Linux-x86_64.sh
```

make sure to type in the correct command (copy paste it)

most likely all you need is:

    bash Miniconda3-latest-Linux-x86_64.sh

**Comment by akgreat22** [comment]
I actually copied and pasted it.

**Comment by ialbert** [comment]
can you please link to the page that has this command, I cannot find it

**Comment by akgreat22** [comment]
It is on page 79 of the Biostar Handbook.- Bioinformatic data analysis guide

The link I copied was;
curl -OL
https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh bash
Miniconda3-latest-Linux-x86_64.sh

**Comment by ialbert** [comment]
is this the PDF? what version is it? What is the date on the first page?

this line of code does not seem to exist in the current version of the book.

always use the web edition to copy code as the field advances quickly and commands won't work in the future

regardless, this seems to be a copy-paste error of some sort, sometimes, when you copy-paste from a PDF it does not copy over correctly, even more reason to use the web version always.

what you copied over is missing a newline; it should be

```
curl -OL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh 
bash Miniconda3-latest-Linux-x86_64.sh
```

**Comment by akgreat22** [comment]
It is the PDF. Version: April 26, 2019.

How do I access the web edition?

**Comment by ialbert** [comment]
that version is ancient

https://www.biostarhandbook.com/

it also has an updated PDF but even that is outdated since the book is getting updates all the time, today I added a new section for example

**Comment by akgreat22** [comment]
Would you advice me to get a student edition or professional edition for the online version?

**Comment by ialbert** [comment]
Since the professional edition gives you 2 years of all updates and the book constantly changes - I consider that a much better deal. The student edition is for students that need to take a semester-long course and expires in six months.

**Comment by akgreat22** [comment]
Hello Dr Albert.
Could someone purchase the book for me, I mean paying on my behalf? If yes,
how would I get access to the online material?

The reason is that the Nigerian Central bank has placed a transaction limit
on our debit card so I couldn't use it on any of the payment platforms.

Thank you.
Akpan Ubong.

**Comment by akgreat22** [comment]
Hi Dr Albert, I have been able to pay for the book through a friend in the
US.

So, I'll be up to date.

Thanks.
Akpan U.

**Comment by ialbert** [comment]
ok sounds good, I will close this issue then.
