### ISSUE TITLE
BLAST version (2.6.0 -> 2.2.31)

### ISSUE THREAD

**Issue by flyark** [biostars/biostar-handbook-issues#25]
Hi, 

I installed the latest BLAST according to the instruction for LINUX (https://www.biostarhandbook.com/tools/align/blast.html)

After the successful installation, I could see the latest BLAST (blastn 2.6.0), and it worked well (e.g, update_blastdb.pl). 

```
which blastn
/home/flyark/src/ncbi-blast-2.6.0+/bin/blastn
blastn -version
blastn: 2.6.0+
 Package: blast 2.6.0, build Dec  7 2016 14:50:34
```

However, blastn version became 2.2.31 when I re-started bash on windows. 
```
which blastn
/usr/bin/blastn
blastn -version
blastn: 2.2.31+
Package: blast 2.2.31, build Jan  7 2016 23:17:17
```

I think that the old BLAST, which had been automatically installed  according to the introduction, masks the new BLAST when bash is re-started. 

Could I know how to replace the old BLAST to the new one completely?

p.s. the present ncbi-blast version is 2.6.0.
2.5.0 in the installation page needs to be replaced to 2.6.0.

**Comment by ialbert** [comment]
This all depends on which version comes first in the path. It appears that you have two different versions of blast available on your computer.

The export command was only active in the current window and it did not get applied automatically when a new terminal was opened.

See the pages:

* https://www.biostarhandbook.com/setup/bash-profile.html
* https://www.biostarhandbook.com/setup/bash-search-path.html
