### ISSUE TITLE
Extremely minor nitpicky issue: Sublime Text 2 is now Sublime Text 4

### ISSUE THREAD

**Issue by WillMc93** [biostars/biostar-handbook-issues#252]
The section on picking a text editor (II.5) lists Sublime Text 2 instead of Sublime Text 4. I know it's incredibly minor but it might be worth just changing this to "Sublime Text" to avoid having to update as Sublime updates.

Again, I'm sorry for being this pedantic.

**Comment by ialbert** [comment]
Normally this would take a while to fix,  but right at this moment, I had the section open at almost the same location, and corrected it. the corrected version is now live on the web, the other versions get the update when the whole  book is recreated

cheers
