### ISSUE TITLE
Inconsistent nucleotide ordering

### ISSUE THREAD

**Issue by dhbradshaw** [biostars/biostar-handbook-issues#26]
> What are nucleotides?
> 
> Nucleotides are the building blocks of nucleic acids (DNA and RNA–we'll get to that one later on). In DNA, there are four types of nucleotide: Adenine, Cytosine, Guanine, and Thymine. Because the order in which they occur encodes the information biologists try to understand, we refer to them by their first letter, A, C, G and T, respectively.
> 
> A   Adenine             
> G   Guanine             
> C   Cytosine         
> T   Thymine             

It's distracting to have the ordering be alphabetical 2 times in the text and then grouped by purine/pyrimadine in list format.

**Comment by ialbert** [comment]
Sorry about that.

It is now fixed. You may need to reload the page. 

Cheers.

**Comment by dhbradshaw** [comment]
Nothing to be sorry about.  

It's part of the creative process and gave me a low stakes way to get my feet wet.  Thanks for putting this together.  I think it will be fun.
