### ISSUE TITLE
Stuck at Doctor.py step for installation process

### ISSUE THREAD

**Issue by nush320** [biostars/biostar-handbook-issues#264]
Hi,

I am getting the following statements when I run the `doctor.py` program in the step-by-step installation process. I have tried deactivating conda, uninstalling and reinstalling it, doing the same with python according to the troubleshooting guide but I am getting the same error. Please help! 

```
$ doctor.py
# Doctor! Doctor! Give me the news.
# Checking symptoms ...
# bwa           --> ERROR
# datamash      --> ERROR
# fastqc -h     --> ERROR
# hisat2        --> ERROR
# seqret -h     --> ERROR
# featureCounts --> ERROR
# efetch        ... OK
# esearch       ... OK
# samtools      --> ERROR
# fastq-dump    ... OK
# bowtie2       --> ERROR
# bcftools      --> ERROR
# seqtk         --> ERROR
# seqkit        --> ERROR
# bio           --> ERROR
# fastq-dump -X 1 -Z SRR1553591 ... OK
```

**Comment by ialbert** [comment]
first do a 

    conda activate bioinfor

did it work? and if so then what does the

    conda list 

print?

In general, your errors look as if conda is not properly activated when the `doctor.py` is run

**Comment by nush320** [comment]
> 

Hi, it says - command not found.

**Comment by ialbert** [comment]
sounds like conda is not installed quite right

what happens at steps 3,4,5 in the step-by-step instructions:

https://www.biostarhandbook.com/step-by-step.html

**Comment by nush320** [comment]
Hi, @ialbert I did not notice anything out of the ordinary in those steps. They seemed to execute without a hitch.

**Comment by nush320** [comment]
So I just tried troubleshooting and I uninstalled everything and was trying again. Unfortunately the Ubuntu 22.04 version I was using before did not work at all. It said "System cannot find file". I downloaded just the app titled "Ubuntu" and I could at least get through the username steps. I also realized there's an automatic installation and the step-by-step is the manual one? While doing the automatic one its stopped with the following errors. Please let me know if this tells you anything and what I could try? @ialbert 
# 7/10 Installing bioinformatics software
#
Traceback (most recent call last):
  File "/home/bstarnush/miniconda3/condabin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/home/bstarnush/miniconda3/lib/python3.10/site-packages/mamba/mamba.py", line 49, in <module>
    import libmambapy as api
  File "/home/bstarnush/miniconda3/lib/python3.10/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/home/bstarnush/miniconda3/lib/python3.10/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: libarchive.so.13: cannot open shared object file: No such file or directory

**Comment by nush320** [comment]
Was able to figure out that my bioinfo environment was not activated.
