### ISSUE TITLE
install issue with quick install command

### ISSUE THREAD

**Issue by BIOSTARFAN** [biostars/biostar-handbook-issues#265]
$ curl http://data.biostarhandbook.com/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3440  100  3440    0     0  26120      0 --:--:-- --:--:-- --:--:-- 26259
#
# 1/10 Bootstrapping the Biostar Handbook
#
#
# 7/10 Installing bioinformatics software
#
Traceback (most recent call last):
  File "/home/zengf/miniconda3/condabin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/home/zengf/miniconda3/lib/python3.10/site-packages/mamba/mamba.py", line 49, in <module>
    import libmambapy as api
  File "/home/zengf/miniconda3/lib/python3.10/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/home/zengf/miniconda3/lib/python3.10/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: libarchive.so.13: cannot open shared object file: No such file or directory
(base)

**Comment by ialbert** [comment]
this is a weird error, as it fails at installing mamba, hence well before even getting to install any bioinformatics tools

this may be a mamba related issue, in which case I need to rework the installation

https://github.com/mamba-org/mamba/issues/1826

**Comment by ialbert** [comment]
what system is this Mac OS M1/M2?

**Comment by BIOSTARFAN** [comment]
I used the windows system, using ubuntu as terminal

**Comment by ialbert** [comment]
did you already have anaconda/miniconda installed or was it a brand new shell?

**Comment by BIOSTARFAN** [comment]
I have installed anaconda on my computer before.

**Comment by ialbert** [comment]
in the same shell?

I think that is the problem here, make a new user that runs a separate environment

**Comment by BIOSTARFAN** [comment]
I can uninstall anaconda to have a try. Thanks.

**Comment by BIOSTARFAN** [comment]
I deleted the anaconda and had another try, still not work, showing the same errors.

**Comment by ialbert** [comment]
you also have to uninstall everything for the handbook

`curl http://data.biostarhandbook.com/uninstall.sh | bash`

then

`http://data.biostarhandbook.com/install.sh | bash`

maybe the best is to start with a clean Unix system.  Uninstall Ubuntu and reinstall it.

It is sad though that conda itself is incapable of working corretly, the whole point of it was supposed to avoid these problems.

**Comment by BIOSTARFAN** [comment]
I got a new problem when install step by step. At step 9:
9. Install the bioinformatics software
# Activate bioinfo.
conda activate bioinfo

# Install the  software.
$ curl -s http://data.biostarhandbook.com/install/conda.txt | xargs mamba install -q -y
Could not solve for environment specs
The following packages are incompatible
├─ bcftools   does not exist (perhaps a typo or a missing channel);
├─ bedtools   does not exist (perhaps a typo or a missing channel);
├─ bioawk   does not exist (perhaps a typo or a missing channel);
├─ blast   does not exist (perhaps a typo or a missing channel);
├─ bowtie2   does not exist (perhaps a typo or a missing channel);
├─ bwa   does not exist (perhaps a typo or a missing channel);
├─ csvtk   does not exist (perhaps a typo or a missing channel);
├─ datamash   does not exist (perhaps a typo or a missing channel);
├─ emboss   does not exist (perhaps a typo or a missing channel);
├─ fastp   does not exist (perhaps a typo or a missing channel);
├─ fastqc   does not exist (perhaps a typo or a missing channel);
├─ freebayes   does not exist (perhaps a typo or a missing channel);
├─ hisat2   does not exist (perhaps a typo or a missing channel);
├─ mafft   does not exist (perhaps a typo or a missing channel);
├─ minimap2   does not exist (perhaps a typo or a missing channel);
├─ parallel   does not exist (perhaps a typo or a missing channel);
├─ perl-text-csv   does not exist (perhaps a typo or a missing channel);
├─ samtools >=1.14  does not exist (perhaps a typo or a missing channel);
├─ seqkit   does not exist (perhaps a typo or a missing channel);
├─ seqtk   does not exist (perhaps a typo or a missing channel);
├─ snpeff 5.0  does not exist (perhaps a typo or a missing channel);
├─ subread   does not exist (perhaps a typo or a missing channel);
├─ trimmomatic   does not exist (perhaps a typo or a missing channel);
└─ ucsc-bedgraphtobigwig   does not exist (perhaps a typo or a missing channel).
(bioinfo)

**Comment by ialbert** [comment]
sounds like the channels are not activated, as it says in the error.

In general if you get an error where nothing works that indicates a step was missed before.  If you get an error where one single tool does not work then it might be some local issue. But when the whole thing fails then it means something is fundamentally not in order.

**Comment by BIOSTARFAN** [comment]
As the auto install script died at step 7 and I started from step 7. Forgot to activate bioconda. Now, all good. Thanks very much for your help. For the original problem, it because I didn't install conda, just run the install script directly (I read the pdf version of the book which skips conda install and activate biocnda). Now, all fixed. I will read the online version of the book.
```
$ ~/bin/doctor.py
# Doctor! Doctor! Give me the news.
# Checking symptoms ...
# bwa           ... OK
# datamash      ... OK
# fastqc -h     ... OK
# hisat2        ... OK
# seqret -h     ... OK
# featureCounts ... OK
# efetch        ... OK
# esearch       ... OK
# samtools      ... OK
# fastq-dump    ... OK
# bowtie2       ... OK
# bcftools      ... OK
# seqtk         ... OK
# seqkit        ... OK
# bio           ... OK
# fastq-dump -X 1 -Z SRR1553591 ... OK
# You are doing well, Majesty!
(bioinfo)
```

**Comment by ialbert** [comment]
sounds like it all worked. Glad to hear. I will be closing this issue then
