### ISSUE TITLE
Trouble assigning a role the the number 2 in point 3 about the ls output.

### ISSUE THREAD

**Issue by dhbradshaw** [biostars/biostar-handbook-issues#27]
At the beginning of the Unix bootcamp, you introduce ls:

```
ls
Applications Desktop Documents Downloads
```
You then make 4 points about the output from that command.  The third point says 

> The output of the ls command lists two things. In this case, they are directories, but they could also be files. We'll learn how to tell them apart later on. These directories were created as part of a specific course that used this bootcamp material. You will therefore probably see something very different on your own computer.

I'm not sure how to interpret this because there are four directories listed.  Maybe "two" refers to two types of things, but my best guess here is that it refers to the number of directories and is out of date.

**Comment by ialbert** [comment]
what I mean is that you could have directories and files listed.

**Comment by ialbert** [comment]
the wording will be changed in the second edition.
