### ISSUE TITLE
Missing antecedent in section 9 of the unix bootcamp

### ISSUE THREAD

**Issue by dhbradshaw** [biostars/biostar-handbook-issues#29]
```
/Users/ialbert/
is identical to specifying the full path:

cd /Users/ialbert/edu/tmp
```
Presumably, there should be a ```~/edu/tmp``` first.

**Comment by ialbert** [comment]
Thanks for pointing this out.

The section has been rewritten and has been pushed out to main (may need a browser reload for you).
