### ISSUE TITLE
What's the best way to get involved in contributing to the guide?

### ISSUE THREAD

**Issue by greggjm** [biostars/biostar-handbook-issues#3]
Currently working through the biostar handbook on Windows 10 using bash on Ubuntu as a bench scientist. The guide is incredibly useful, but it's taking some time to troubleshoot various issues along the way I've encountered due to running Ubuntu through Windows.

I'm also making a thorough enough how-to manual that anybody else in my lab would be able to copy it line by line to successfully install the required components. I've started writing scripts to automate the install process for windows users so they can avoid potential problems caused by an inexperienced user attempting to set up the necessary tools. I'd like to contribute what I've found so far, and troubleshoot a couple resilient errors moving forward.

**Comment by ialbert** [comment]
Hello Greg. That would incredibly useful and much appreciated.  

Perhaps the simplest way to get that information would be to open a pull request right here, on this repository.

**Comment by greggjm** [comment]
I'll open a pull request after I've finalized my notes on the install and
setup process. I'm not entirely familiar with how they work, could they
also be used to collaborate on potential scripts for review? I'd like to
make them accessible to curl straight from bash.

As for a couple of the resilient installation errors associated with
installing conda packages, would it be best to create a separate thread for
all Windows conda install issues?




On Feb 23, 2017, at 01:00, Istvan Albert <notifications@github.com> wrote:

Hello Greg. That would incredibly useful and much appreciated.

Perhaps the simplest way to get that information would be to open a pull
request right here, on this repository.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/biostars/biostar-handbook-issues/issues/3#issuecomment-281902764>,
or mute the thread

**Comment by ialbert** [comment]
Fork this repository, add your changes then you'll have a pull request show up. It allows for seamless interactions, we can discuss and add more changes to the same pull request. It is a good way to discuss a script that you might want to add.

It is probably best to separate issues and open a new issue for a different problem. One can then mention issues in pull requests and commits, that way a trail is formed.
