### ISSUE TITLE
the ebola project PRJNA257197 update

### ISSUE THREAD

**Issue by mckf111** [biostars/biostar-handbook-issues#30]
It seems that this project has been updated these 2-3 days, I can't see the protein and nucleotide data, only SRA data was kept. However, esearch and efetch tools still can work:)

![capture](https://user-images.githubusercontent.com/28294703/31710253-b99ae9c6-b3f4-11e7-8d7d-9fd5c6eb20c6.JPG)

**Comment by ialbert** [comment]
Thanks for the note. 

Interesting and surprising. And it now provides less information, :-\

We have to keep watching this in case more changes occur..

**Comment by mckf111** [comment]
sigh... And the change came out without any trace information, no version control. Could this be a normal phenomenon in bioinformatics?

**Comment by ialbert** [comment]
Biology used to follow its own rules - informatics changed that - and there is a culture shift taking place and it is not pretty.

**Comment by mckf111** [comment]
UPDATE: now they come back again, maybe some kind of database maintenance before~~~

**Comment by ialbert** [comment]
Interesting events. We'll close this issue then
