### ISSUE TITLE
python version issue in section "Visualizing genomic variations"

### ISSUE THREAD

**Issue by mckf111** [biostars/biostar-handbook-issues#31]
After I downloaded the *perfect_coverage.py file*, run the following code:

**$ cat refs/AF086833.fa | python perfect_coverage.py**

it complains:

>Traceback (most recent call last):
  >File "perfect_coverage.py", line 55, in <module>
    read1, read2 = file('R1.fq', 'wt'), open('R2.fq', 'wt')
>NameError: name 'file' is not defined
>(bioinfo)

**Comment by ialbert** [comment]
The script was originally designed for Python 2.7 and would fail on Python 3.0. 

It has now been updated to work for both. Fetch new version with


    curl -O http://data.biostarhandbook.com/align/perfect_coverage.py

Thank you for reporting this problem.
