### ISSUE TITLE
Most annotated human genes and proteins

### ISSUE THREAD

**Issue by Raggorobbie** [biostars/biostar-handbook-issues#33]
For first time learners of Unix, it would be helpful if this section (page 420) contained an explanation of the commands/pipelines called to sort the list of genes and grab the top ten most highly annotated genes and proteins. Particularly the last step sort -k1,1nr is unclear. Are we not meant to understand this yet?

**Comment by ialbert** [comment]
Apologies for missing that.

That command is meant to specify a sort of by column `1`, ending at column `1` (so won't sort on other columns) and to perform the sort numerically (`n`) and in reverse order (`r`)

A good explanation of how sort works can be found here:

https://en.wikipedia.org/wiki/Sort_(Unix)

I will add this to that section.
