### ISSUE TITLE
Installation problem with new MacBook Pro

### ISSUE THREAD

**Issue by JHanLab** [biostars/biostar-handbook-issues#336]
Hi, have installed the bioinfo environment on a few of my Apple computers with no problem, but I just got a new MacBook Pro (M3 chip, running macOS Sonoma 14.6.1) and I am having a problem with one of the applications. When I run doctor.py, there is an error with seqret (screenshot attached). 
<img width="1125" alt="Screenshot 2024-08-17 at 4 36 36 PM" src="https://github.com/user-attachments/assets/6846606a-a3e8-4335-9fec-e3252016ed1c">
It is looking for the library libpq.5.dylib, which I do not see on my computer anywhere. I also don't see the path /usr/local/lib/ on my computer (there is nothing in the local folder, screenshot attached).
<img width="1073" alt="Screenshot 2024-08-17 at 4 42 56 PM" src="https://github.com/user-attachments/assets/000455a4-1993-433f-962d-f16bcdb48e02">

**Comment by ialbert** [comment]
Not sure why this happens, but seqret is rarely used in the book (has been supplanted by bio) - so it is not running is not a priority.

this error can be ignored and testing seqret will be removed

**Comment by JHanLab** [comment]
Thank you
