### ISSUE TITLE
macOS Installation Issues

### ISSUE THREAD

**Issue by hngu09** [biostars/biostar-handbook-issues#338]
I have a MacBook Pro with an M1 Pro on macOS 15.0. Both the install script and step-by-step installation get stuck on the same step which is initializing the shell. Here's what happens:

``` 
hungs-MBP:~ hngu$ ./bin/micromamba shell init -s bash -p ~/micromamba -q
The following argument was not expected: -p
Run with --help for more information.
```

Any idea of what's happening here?

**Comment by ialbert** [comment]
Sorry about that, looks like micromamba suddenly changed a parameter, with the new release of micromamba version 2.0 the `-p` is not accepted anymore it should be `-r` (before it could  be both `-p` and `-r` probably for historical reasons).

I have updated the install script, it show work now, 

I will need to also test the install on a brand-new system to make sure nothing else changed.

**Comment by hngu09** [comment]
If it saves you any concern, the install script works perfectly fine now. Thank you for your help!

**Comment by ialbert** [comment]
Good to hear. 

Thanks for reporting! This error would have affected just about everyone starting today. So it was quite timely and fortuitous that I became aware of the problem right away.
