### ISSUE TITLE
Problem with crossmap installation

### ISSUE THREAD

**Issue by piruzubieta** [biostars/biostar-handbook-issues#339]
Hello,

I have installed crossmap but when trying to run, it does not work:

root@DESKTOP-OCNBRSQ ~/micromamba/envs/bioinfo
# conda install crossmap -y
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
bioconda/linux-64                                           Using cache
bioconda/noarch                                             Using cache

root@DESKTOP-OCNBRSQ ~/micromamba/envs/bioinfo
# CrossMap.py
CrossMap.py: command not found
(bioinfo)

Any idea?
Thanks!

**Comment by ialbert** [comment]
Typically we cannot provide installation instructions to software as there may be myriad of issues that are unrelated to the book

In this case the situation probably is that the software runs under a different name, instead of `CrossMap.py` it is probably `CrossMap`

**Comment by piruzubieta** [comment]
Hi,
Great, thanks. Indeed just using the different name it worked.
Thanks a lot!
Pablo
________________________________
De: Istvan Albert ***@***.***>
Enviado: viernes, 1 de noviembre de 2024 13:15
Para: biostars/biostar-handbook ***@***.***>
Cc: piruzubieta ***@***.***>; Author ***@***.***>
Asunto: Re: [biostars/biostar-handbook] Problem with crossmap installation (Issue #339)


Typically we cannot provide installation instructions to software as there may be myriad of issues that are unrelated to the book

In this case the situation probably is that the software runs under a different name, instead of CrossMap.py it is probably CrossMap
