### ISSUE TITLE
 esearch -db sra -query PRJNA257197

### ISSUE THREAD

**Issue by muffinman563** [biostars/biostar-handbook-issues#34]
Hello,

When running the command
esearch -db sra -query PRJNA257197

I get this issue:

501 Protocol scheme 'https' is not supported (LWP::Protocol::https not installed)
No do_post output returned from 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=sra&term=PRJNA257197&retmax=0&usehistory=y&edirect_os=darwin&edirect=7.70&tool=edirect&email=canjustinkiessling@CanJustsMacBook.home'
Result of do_post http request is
$VAR1 = bless( {
                 '_headers' => bless( {
                                        'client-date' => 'Sat, 27 Jan 2018 14:18:01 GMT',
                                        '::std_case' => {
                                                          'client-warning' => 'Client-Warning',
                                                          'client-date' => 'Client-Date'
                                                        },
                                        'client-warning' => 'Internal response',
                                        'content-type' => 'text/plain'
                                      }, 'HTTP::Headers' ),
                 '_rc' => 501,
                 '_content' => 'LWP will support https URLs if the LWP::Protocol::https module
is installed.
',
                 '_msg' => 'Protocol scheme \'https\' is not supported (LWP::Protocol::https not installed)',
                 '_request' => bless( {
                                        '_headers' => bless( {
                                                               'content-type' => 'application/x-www-form-urlencoded',
                                                               'user-agent' => 'libwww-perl/6.31'
                                                             }, 'HTTP::Headers' ),
                                        '_content' => 'db=sra&term=PRJNA257197&retmax=0&usehistory=y&edirect_os=darwin&edirect=7.70&tool=edirect&email=canjustinkiessling@CanJustsMacBook.home',
                                        '_method' => 'POST',
                                        '_uri' => bless( do{\(my $o = 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi')}, 'URI::https' )
                                      }, 'HTTP::Request' )
               }, 'HTTP::Response' );

WebEnv value not found in search output - WebEnv1

**Comment by ialbert** [comment]
There is a section called

3.2 What if I have a "Chronic Case of Entrez Direct"?

that deals with this exact problem. Please see this page

https://www.biostarhandbook.com/setup/setup.html?h=chronic

**Comment by muffinman563** [comment]
Hi, i followed the instructions up to the "conda uninstall entrez-direct" and my output was:

-bash: esearch: command not found

I re-installed entrez-direct using conda install entrez-direct and now my output is:

CanJustsMacBook:~ canjustinkiessling$ esearch -db sra -query PRJNA257197
Can't locate HTML/Entities.pm in @INC (you may need to install the HTML::Entities module) (@INC contains: /Users/canjustinkiessling/src/edirect/aux/lib/perl5 /Users/canjustinkiessling/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/darwin-2level /Users/canjustinkiessling/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1 /Users/canjustinkiessling/perl5/perlbrew/perls/perl-5.20.1/lib/5.20.1/darwin-2level /Users/canjustinkiessling/perl5/perlbrew/perls/perl-5.20.1/lib/5.20.1 .) at /Users/canjustinkiessling/src/edirect/edirect.pl line 71.
BEGIN failed--compilation aborted at /Users/canjustinkiessling/src/edirect/edirect.pl line 71.

**Comment by ialbert** [comment]
Make sure the follow the instructions on the page. You should NOT  reinstall with conda. 

You will need to copy paste the instructions on the page that I have linked in. These instructions are located right above the sentence that starts with:

"Execute the commands above to install your local version of Entrez Direct."

**Comment by muffinman563** [comment]
I did execute that, and i still got the error as per post#1. I ran
"mkdir -p ~/src
curl ftp://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/edirect.zip > ~/src/edirect.zip
unzip -o ~/src/edirect.zip  -d ~/src
echo 'export PATH=~/src/edirect:$PATH' >> ~/.bashrc
source  ~/.bashrc"

and the output was

CanJustsMacBook:~ canjustinkiessling$ esearch -db sra -query PRJNA257197
Can't locate HTML/Entities.pm in @INC (you may need to install the HTML::Entities module) (@INC contains: /Users/canjustinkiessling/src/edirect/aux/lib/perl5 /Users/canjustinkiessling/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/darwin-2level /Users/canjustinkiessling/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1 /Users/canjustinkiessling/perl5/perlbrew/perls/perl-5.20.1/lib/5.20.1/darwin-2level /Users/canjustinkiessling/perl5/perlbrew/perls/perl-5.20.1/lib/5.20.1 .) at /Users/canjustinkiessling/src/edirect/edirect.pl line 71.
BEGIN failed--compilation aborted at /Users/canjustinkiessling/src/edirect/edirect.pl line 71.

**Comment by muffinman563** [comment]
Also noticed another problem for efetch:

CanJustsMacBook:~ canjustinkiessling$ efetch
Can't locate HTML/Entities.pm in @INC (you may need to install the HTML::Entities module) (@INC contains: /Users/canjustinkiessling/src/edirect/aux/lib/perl5 /Users/canjustinkiessling/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/darwin-2level /Users/canjustinkiessling/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1 /Users/canjustinkiessling/perl5/perlbrew/perls/perl-5.20.1/lib/5.20.1/darwin-2level /Users/canjustinkiessling/perl5/perlbrew/perls/perl-5.20.1/lib/5.20.1 .) at /Users/canjustinkiessling/src/edirect/edirect.pl line 71.
BEGIN failed--compilation aborted at /Users/canjustinkiessling/src/edirect/edirect.pl line 71.

**Comment by ialbert** [comment]
From above it seems that you some other software installed that is not in the book. 

It is called perlbrew and it seems that it the cause of the error s

I would recommend either uninstalling or using perlbrew to install the missing packages.

**Comment by muffinman563** [comment]
I installed pearlbrew via command line, now my output is this:

Last login: Sat Jan 27 22:18:09 on ttys000
CanJustsMacBook:~ canjustinkiessling$ esearch -db sra -query PRJNA257197
501 Protocol scheme 'https' is not supported (LWP::Protocol::https not installed)
No do_post output returned from 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=sra&term=PRJNA257197&retmax=0&usehistory=y&edirect_os=darwin&edirect=7.70&tool=edirect&email=canjustinkiessling@CanJustsMacBook.home'
Result of do_post http request is
$VAR1 = bless( {
                 '_msg' => 'Protocol scheme \'https\' is not supported (LWP::Protocol::https not installed)',
                 '_request' => bless( {
                                        '_uri' => bless( do{\(my $o = 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi')}, 'URI::https' ),
                                        '_headers' => bless( {
                                                               'content-type' => 'application/x-www-form-urlencoded',
                                                               'user-agent' => 'libwww-perl/6.31'
                                                             }, 'HTTP::Headers' ),
                                        '_method' => 'POST',
                                        '_content' => 'db=sra&term=PRJNA257197&retmax=0&usehistory=y&edirect_os=darwin&edirect=7.70&tool=edirect&email=canjustinkiessling@CanJustsMacBook.home'
                                      }, 'HTTP::Request' ),
                 '_content' => 'LWP will support https URLs if the LWP::Protocol::https module
is installed.
',
                 '_headers' => bless( {
                                        'client-warning' => 'Internal response',
                                        '::std_case' => {
                                                          'client-warning' => 'Client-Warning',
                                                          'client-date' => 'Client-Date'
                                                        },
                                        'content-type' => 'text/plain',
                                        'client-date' => 'Sat, 27 Jan 2018 19:19:06 GMT'
                                      }, 'HTTP::Headers' ),
                 '_rc' => 501
               }, 'HTTP::Response' );

WebEnv value not found in search output - WebEnv1 
CanJustsMacBook:~ canjustinkiessling$

**Comment by ialbert** [comment]
I cannot help with perlbrew. I don't recommend that people install it. 

I do sympathise with the problems you have and it is ridiculos that a tool developed by NCBI that is just a basic simple tool has so many problems.

I would recommend getting rid of perlbrew and sticking only the the original instructions. These do work but now if you have lots of other packages installed - that interfere.

**Comment by muffinman563** [comment]
Well can i just proceed with the rest of the book? I'm at the "How much data is in the SRA" chapter. 

I noticed that with the install all command, i only had 3 optional ones that weren't installed, and when  i tried i couldn't install any of them. Can you tell me why i have the bin error?

CanJustsMacBook:~ canjustinkiessling$ ~/bin/doctor.py
# Doctor! Doctor! Give me the news.
# The ~/bin folder is not in your PATH!
# Checking 15 symptoms...
# Optional program not found: wonderdump
# Optional program not found: global-align.sh
# Optional program not found: local-align.sh
# Your system shows 1 error.

**Comment by ialbert** [comment]
You need to add ~/bin to your path.

If you follow the 

1.1 How do I initialize my terminal configuration?

that will add ~/.bin to you path.

You can learn more about that here:

https://www.biostarhandbook.com/setup/bash-profile.html

**Comment by muffinman563** [comment]
CanJustsMacBook:~ canjustinkiessling$ curl http://data.biostarhandbook.com/install/bash_profile.txt >> ~/.bash_profile
-bash: /Users/canjustinkiessling/.bash_profile: Permission denied
CanJustsMacBook:~ canjustinkiessling$ curl http://data.biostarhandbook.com/install/bashrc.txt >> ~/.bashrc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   759  100   759    0     0    759      0  0:00:01 --:--:--  0:00:01  2225
CanJustsMacBook:~ canjustinkiessling$  
CanJustsMacBook:~ canjustinkiessling$ 
CanJustsMacBook:~ canjustinkiessling$
