### ISSUE TITLE
Mac Studio M2 Ultra biopython error in stats install

### ISSUE THREAD

**Issue by genomics-ccrtd-cau** [biostars/biostar-handbook-issues#341]
bioinfo env and install worked flawlessly.
stats and salmon_env yielded this error:
1 warning and 2 errors generated.
      error: command '/Users/genomics1/micromamba/envs/stats/bin/x86_64-apple-darwin13.4.0-clang' failed with exit code 1
      [end of output]

went back and tried to install biopython with 
micromamba install -c conda-forge biopython
while in the stats env and got this error:

pin on python 3.13.* is not installable because it requires
       └─ python =3.13, which conflicts with any installable versions previously reported.
critical libmamba Could not solve for environment specs

should i reintall stats env packages with earlier python version?

**Comment by ialbert** [comment]
I should probably set the python environment to python 3.12 or lower; the bioinfo has it pinned to 3.10

I think the latest version of python 3.13 must have some incompatibilities.

try with

micromamba install -c conda-forge biopython python=3.12

**Comment by ialbert** [comment]
can you try to see wether this works

    micromamba create -yn salmon_env salmon make parallel python=3.12

I don't have an M2 based system right now

**Comment by genomics-ccrtd-cau** [comment]
> can you try to see wether this works
> 
> ```
> micromamba create -yn salmon_env salmon make parallel python=3.12
> ```
> 
> I don't have an M2 based system right now

Yes, it seemed to create and isntall fine.
is the biopython only in salmon_env or in stats as well? 

this worked in stats env as well:  micromamba install -c conda-forge biopython python=3.12
thanks.

**Comment by ialbert** [comment]
yes I think in stats also you could install after the fact, 

```
conda activate stats
conda install python=3.12
```

I will make the change in the installation script
