### ISSUE TITLE
issue in installing micromamba

### ISSUE THREAD

**Issue by nchut** [biostars/biostar-handbook-issues#344]
Hello,
I am completely new to this field. I recently bought Biostar book and was trying to download software using
curl http://data.biostarhandbook.com/install.sh | bash
 and failed (showed multiple error).
After that I was trying to follow step by step installation guide. 
when trying to download micromamba (using WSL platform) using
curl -Ls https://micro.mamba.pm/api/micromamba/osx-64/latest | tar -xj bin/micromamba
nothing is actually happening. Now I am totally lost. 
Just to let you know I am completely illiterate to this field, just trying to learn this new field by buying this book.
Please help.
Thanks in advance.

**Comment by ialbert** [comment]
the first step in troubleshooting is do post the errors you get after you run the first command

you can copy paste from the terminal

nothing happens might mean you are not connected to the internet or you are using an internet connection where certain URLS are not permitted (like a school etc)

**Comment by nchut** [comment]
Thank you very much; I will look into that.

**Comment by nchut** [comment]
I have another question; my computer is little old, doesn't have preinstalled ubuntu, do I need to download Ubuntu and Python before downloading Biostar software? 
Sorry again, if it sound like a dumb question, as I am new here, doesn't know anything.
Thanks in advance.

**Comment by nchut** [comment]
Also, when I am trying to download software (WSL terminal) using the Biostar command
curl http://data.biostarhandbook.com/install.sh | bash

**It's giving me error:**
$ doctor.py
# Doctor! Doctor! Give me the news.
# Checking symptoms ...
# bwa           --> ERROR
# datamash      --> ERROR
# fastqc -h     --> ERROR
# hisat2        --> ERROR
# featureCounts --> ERROR
# efetch        ... OK
# esearch       ... OK
# samtools      --> ERROR
# fastq-dump    ... OK
# bowtie2       --> ERROR
# bcftools      --> ERROR
# seqtk         --> ERROR
# seqkit        --> ERROR
# bio           --> ERROR
# fastq-dump -X 1 -Z SRR1553591 ... OK
#
# Found some problems
#
# Unable to run: bwa, datamash, fastqc -h, hisat2, featureCounts, samtools, bowtie2, bcftools, seqtk, seqkit, bio
#
# Check the Biostar Handbook for installation help.

**Comment by ialbert** [comment]
make sure to activate the bioinfo enviroment first

    micromamba activate bioinfo

you will need to do that each time you open a new terminal

**Comment by nchut** [comment]
It worked!! Thank you very much for your help.
