### ISSUE TITLE
xargs: conda: No such file or directory 

### ISSUE THREAD

**Issue by zaklmurray** [biostars/biostar-handbook-issues#36]
Hi there, 

I am very new to bioinformatics and to this book. 

I am trying to set-up my Mac as per the instructions in the book. 

When I ran the command: 
curl http://data.biostarhandbook.com/install/conda.txt | xargs conda install -y

I get an error saying: 
"xargs: conda: No such file or directory".

Can anyone tell me why this is coming up?

Cheers, Zak

**Comment by ialbert** [comment]
This error message is generated if the program invoked with xargs does not seem to exist.

    ls -1 | xargs foo
    xargs: foo: No such file or directory

Make sure that conda is installed and that it is added to the import path. 

What this means is that if you typed just `conda` you would get an output by the `conda` program.

**Comment by zaklmurray** [comment]
Hi ialbert, 

Thank you very much for your response.

I re-ran the command today and it seemed to work fine. I did have conda installed and I believe that it was added to the import path as well so I am not sure why it didn't work when I ran the command the first time. 

I also ran the doctor.py script after running the "install everything" command and it says that I have an error still. When I ran the script, it gave me the following error: 

zakmurray@Zaks-MacBook-Pro ~
$ ~/bin/doctor.py
# Doctor! Doctor! Give me the news.
# Checking 15 symptoms...
# Missing program: R
# Optional program not found: wonderdump
# Optional program not found: global-align.sh
# Optional program not found: local-align.sh
# Your system shows 1 error.
# See also: doctor.py --fixme
(bioinfo) 

Is the one error just related to not having R installed? 

Regards, 
Zak

**Comment by ialbert** [comment]
yes, correct.
