### ISSUE TITLE
Tophat not installing with Biostar Handbook

### ISSUE THREAD

**Issue by squirrelgirl33** [biostars/biostar-handbook-issues#37]
I'm working from the Biostar Handbook and trying to do the alignment with tophat. I'm on page 480 for reference.

I was able to successfully run

    $ bowtie2-build $REF $IDX

However, then it says that I need to change the invocation of the aligner to 

    $ tophat -G $GTF -o tophat_hbr1 $IDX $R1 $R2
    bash: /usr/bin/tophat: No such file or directory
    (bioinfo) 

And that's my output. If I do which tophat, nothing comes up, so it seems like it's just not there. So, I tried to install tophat with 

    $ conda install tophat
    Fetching package metadata .................
    Solving package specifications: .
    
    UnsatisfiableError: The following specifications were found to be in conflict:
      - python 3.6*
      - tophat -> python 2.7*
    Use "conda info <package>" to see the dependencies for each package.
    
    (bioinfo) 

I saw some solutions online for changing a line of code in tophat to do this, but I don't even know where that file is. I can downgrade python, but I'm not sure if that will work, and I'm worried that I'll break other things if I do. Also, when I do 

    $ ls /usr/bin | grep python
    dh_python2
    dh_python3
    python
    python-config
    python2
    python2-config
    python2.7
    python2.7-config
    python3
    python3.4
    python3.4m
    python3m
    x86_64-linux-gnu-python-config
    x86_64-linux-gnu-python2.7-config
    (bioinfo) 
    moltres@moltres-ao ~/biostar/Sequencing/griffith
    $ python -V
    Python 3.6.3
    (bioinfo) 

I see a bunch of different python versions, and I'm not sure if I should switch between them or what.

It doesn't even say to install tophat anywhere in this section. I'm pretty lost here.

**Comment by ialbert** [comment]
unfortunately, TopHat 2 needs an older version of Python and cannot be installed concurrently with the existing tools.

Luckily this is where the ability to maintain different environments can be of service. Create a new Python 2 specific environment with ` conda`  then install TopHat 2 into that. Usually I run this in another window

    conda create -y --name py2bio python=2.7

 Then 

    source activate py2bio
    conda install tophat

**Comment by squirrelgirl33** [comment]
Thank you, that solved my issue. I don't think I quite understood what I was doing in the beginning with the conda create script, and it's been forever since I did it, so I didn't even consider that.

**Comment by ialbert** [comment]
great.
