### ISSUE TITLE
Automated HISAT2 not generating SAMPLE_summary.txt or runlog.txt (p. 496)

### ISSUE THREAD

**Issue by squirrelgirl33** [biostars/biostar-handbook-issues#38]
I'm trying to do the Zika RNA-Seq automated alignments, but I noticed that when I got to the differentially expressed genes analysis, all my numbers were off. I'm trying to trace back what might be wrong, and I suspect that it's something with my bam files produced by the automated script on page 496. This is the script I ran using bash:
```
set -ueo pipefail

mkdir -p bam

CPUS=4

IDX=refs/grch38/genome

RUNLOG=runlog.txt

echo "Run started by `whoami` on `date`" > $RUNLOG

for SAMPLE in $(cat paired_ids.txt)
do
	R1=reads/${SAMPLE}_1.fastq
	R2=reads/${SAMPLE}_2.fastq
	BAM=bam/${SAMPLE}.bam
	SUMMARY=bam/${SAMPLE}_summary.txt

	echo "Running HISAT2 on paired end $SAMPLE"
	hisat2 -p $CPUS -x $IDX -1 $R1 -2 $R2 | samtools sort > $BAM 2> $RUNLOG
	samtools index $BAM
done

for SAMPLE in $(cat single_ids.txt)
do
	R1=reads/${SAMPLE}.fastq
	BAM=bam/${SAMPLE}.bam
	SUMMARY=bam/${SAMPLE}_summary.txt

	echo "Running Hisat2 on single end: $SAMPLE"
	hisat2 -p $CPUS -x $IDX -U $R1 | samtools sort > $BAM 2> $RUNLOG
	samtools index $BAM

done
```
However, my runlog.txt file is completely empty, and I don't get a bam/${SAMPLE}_summary.txt

I also don't understand what the IDX=refs/grch38/genome is referencing since I don't have a file precisely by that name.

Is this a glitch, or am I doing something wrong here? Thanks.

**Comment by ialbert** [comment]
A script like the above automates an entire process, but you need track down and understand each step that it does. 

So what is the IDX doing?

When you run an aligner it will operate on an index file. This is one that was created in a prior step. The IDX references that file.

**Comment by squirrelgirl33** [comment]
I know IDX is specifying the index, but I'm confused since previously it always referred to a .fa or .idx file, and now there's no extension. There's not a reference in the book that I can find that covers how this situation is different from the others other than "This index has the prefix of 'genome.'" Is it supposed to just use any of the files with genome.#.ht2?

**Comment by squirrelgirl33** [comment]
Okay, thank you. I think I understand that better now, but it was unclear to me before that IDX didn't have to be just a single file.

Then could you maybe explain what's going wrong with my count.txt file then?

In the book you give some example genes with columns 1,7-14:
```
SCNN1D		78	98	653	946	51	61	499	422
ACAP3		1528	1610	11871	17377	1649	1509	14102	10830
MIR6726		0	0	0	1	0	0	0	0
PUSL1		67	68	437	670	81	88	656	553
```
However, if I check these in my file, then I get this:

```
$ cat counts.txt | grep -E "SCNN1D|ACAP3|MIR6726" | cut -f 1,7-14
SCNN1D	12	15	5	4	3	7	6	4
ACAP3	185	215	147	195	232	205	186	166
MIR6726	0	0	0	0	0	0	0	0
NACAP3	0	0	0	0	0	0	0	0
```
I've double-checked all the files that I've downloaded, and they're the same. Could you maybe give me suggestions of what to check? Is there versioning of something that could cause this issue?

**Comment by ialbert** [comment]
The entire RNA-Seq section has been reworked. We will close this now.
