### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by molecules** [biostars/biostar-handbook-issues#40]
On the page https://www.biostarhandbook.com/ is the sentence "The book is available in over the web, as a PFD, an eBOOK and in Kindle formats.". Did you mean PDF instead of PFD?

**Comment by ialbert** [comment]
heh, sorry about that, PFD actually stands for Personal Floatation Device ;-)

**Comment by ialbert** [comment]
2nd edition addresses this and many other issues.
