### ISSUE TITLE
Possible improvement of RNA-Seq: Griffith Test Data

### ISSUE THREAD

**Issue by anonymnon** [biostars/biostar-handbook-issues#42]
First and foremost, thank you for putting together this wonderful guide. I am a complete novice when it comes to programming/bioinformatics and this guide has really helped me learn a lot. I'm very close to being able to start to run some analyses on my own.

My suggestion pertains to the section RNA-Seq: Griffith Test Data -> Analyzing the control samples -> Did our RNA-Seq analysis reproduce the expected outcomes?

The main issue I have is with the final command
```bash
paste table1 table2 > compare.txt
```

If opened with `$ less compare.txt`, it shows:
```
ERCC-00002      0.5     -1^M    ERCC-00002      0.587081192626208       -0.768368054756608
ERCC-00003      0.5     -1^M    ERCC-00003      0.680961534372993       -0.554354788186953
ERCC-00004      4       2^M     ERCC-00004      5.88286106939268        2.55651796573194
ERCC-00009      1       0^M     ERCC-00009      1.21972406601959        0.286554808762869
ERCC-00012      0.67    -0.58^M ERCC-00012      Inf     Inf
ERCC-00013      0.5     -1^M    ERCC-00013      Inf     Inf
ERCC-00014      0.5     -1^M    ERCC-00014      0.487600858570454       -1.0362274286211
ERCC-00016      0.67    -0.58^M ERCC-00016      NA      NA
ERCC-00017      4       2^M     ERCC-00017      Inf     Inf
ERCC-00019      4       2^M     ERCC-00019      2.7835815473997 1.4769423488067
```

If this is opened in Excel, it shows a very ugly output
![image](https://user-images.githubusercontent.com/42382290/44102139-04b0ea42-9fb7-11e8-8801-4f077dac2fb0.png)

The main issue underlying this is the `^M` generated by the `paste` command. Now, I have no idea why the paste command generated this `^M`, and I have verified that all previous files do not have '^M'.

```bash
$ head ERCC-datasheet.csv
ERCC ID,subgroup,concentration in Mix 1 (attomoles/ul),concentration in Mix 2 (attomoles/ul),expected fold-change ratio,log2(Mix 1/Mix 2)
ERCC-00130,A,30000,7500,4,2
ERCC-00004,A,7500,1875,4,2
ERCC-00136,A,1875,468.75,4,2
ERCC-00108,A,937.5,234.375,4,2
ERCC-00116,A,468.75,117.1875,4,2
ERCC-00092,A,234.375,58.59375,4,2
ERCC-00095,A,117.1875,29.296875,4,2
ERCC-00131,A,117.1875,29.296875,4,2
ERCC-00062,A,58.59375,14.6484375,4,2
```

```bash
$ head results.txt
id      baseMean        baseMeanA       baseMeanB       foldChange      log2FoldChange  pval    padj
ERCC-00130      29681.8244237545        10455.9218232761        48907.7270242329        4.67751460376822        2.22574215774208        1.16729711209905e-88       9.10491747437256e-87
ERCC-00108      808.597670575459        264.877838024487        1352.31750312643        5.10543846632202        2.35203486825767        2.40956154792488e-62       9.39729003690704e-61
ERCC-00136      1898.3382995277 615.744918976546        3180.93168007886        5.16598932779828        2.36904466305553        2.80841619396485e-58       7.3018821043086e-57
ERCC-00116      952.57953992746 337.704944218003        1567.45413563692        4.64149004174798        2.21458802318734        1.72224091670519e-45       3.35836978757511e-44
ERCC-00092      310.791194556933        96.697066636053 524.885322477813        5.42814110849266        2.44045822515553        2.44705874688655e-40       3.81741164514302e-39
ERCC-00004      3918.98719921685        1138.76690513024        6699.20749330347        5.88286106939268        2.55651796573194        8.29322966465066e-38       1.07811985640459e-36
ERCC-00095      141.487857460492        52.8817320556433        230.093982865341        4.35110526680992        2.12138192059427        2.46928414480309e-19       2.7514880470663e-18
ERCC-00062      77.4886630526754        22.8781484767386        132.099177628612        5.7740327091121 2.52957928026876        7.80930857468792e-17       7.61407586032072e-16
ERCC-00131      134.742367710255        55.9465732085198        213.53816221199 3.81682290738535        1.93237225006829        4.75964190578523e-16       4.12502298501386e-15
```
```bash
$ head table1
ERCC-00002      0.5     -1
ERCC-00003      0.5     -1
ERCC-00004      4       2
ERCC-00009      1       0
ERCC-00012      0.67    -0.58
ERCC-00013      0.5     -1
ERCC-00014      0.5     -1
ERCC-00016      0.67    -0.58
ERCC-00017      4       2
ERCC-00019      4       2
```
```bash
$ head table2
ERCC-00002      0.587081192626208       -0.768368054756608
ERCC-00003      0.680961534372993       -0.554354788186953
ERCC-00004      5.88286106939268        2.55651796573194
ERCC-00009      1.21972406601959        0.286554808762869
ERCC-00012      Inf     Inf
ERCC-00013      Inf     Inf
ERCC-00014      0.487600858570454       -1.0362274286211
ERCC-00016      NA      NA
ERCC-00017      Inf     Inf
ERCC-00019      2.7835815473997 1.4769423488067
```

Thus, for some bizarre reason, `^M` is being added by the paste command which completely breaks down-stream data analysis.

Of course, it is easy to remove `^M` by multiple commands and fix the file. However, for folks like myself that follow the guide very closely, it is not clear what is going on. The guide simply glosses over intermediate steps to analyze the data:

***********************************
![image](https://user-images.githubusercontent.com/42382290/44102745-6d82d552-9fb8-11e8-85a3-06297e183a44.png)
***********************************

At the very least, it should be mentioned that additional steps were taken to organize the data as shown in the final data table. Otherwise, it is extremely frustrating to figure out if something went wrong in the intermediate steps. Ideally, the output of `compare.txt` should be shown before showing the data table so the user is reassured that they did the steps correctly.

Thanks!

**Comment by ialbert** [comment]
Having a `^M` inside of a text file when looking under Unix a typically indicates that the file has Windows-style line endings and those may be mixed with Unix-style line endings. Naturally, the result is a complete disaster when it comes to text files.

Normally should not happen - paste should not be adding windows style line endings - perhaps the first  file has a Windows line endings. Wich is very curious, since that comes from the command:

    curl http://data.biostarhandbook.com/rnaseq/ERCC/ERCC-datasheet.csv | grep ERCC-00 | cut -f 1,5,6 -d , | sort > table1

Which on my system works as expected.

What does the file `table1` look like when you open it up with less, does it have the `^M`?

Finally you can remove the pesky line endings from the original file with commands such as:

     cat input_file | tr -d '\r'  > output_file

**Comment by anonymnon** [comment]
Hi Ian!

Thanks for the super fast reply. Here is `table1`.

```
$ less table1
ERCC-00002      0.5     -1
ERCC-00003      0.5     -1
ERCC-00004      4       2
ERCC-00009      1       0
…
```
No `^M` anywhere that I can see. Sounds like this is an isolated issue for my environment. However, I still think the guide should show the expected output of `compare.txt` so users can know if anything weird from the commands executed above.

**Comment by ialbert** [comment]
we'll add that example output - 

I will say that in some cases similary named Windows commands might take precedence, in this case if there was a `paste` command

I would also create two files and paste them to see how it all behaves

   ls > 1
   ls > 2
   paste 1 2 

and so on, not having it behave properly, and not knowing why may cause lots of very annoying (sometimes slilent) problems later on.

**Comment by anonymnon** [comment]
Here is the output from the commands you suggested:
```bash
% sed -e "s/^M//" filename > newfilename
$ ls > 1
(bioinfo)
xxx@Bob ~/rnstut/griff
$ ls > 2
(bioinfo)
xxx@Bob ~/rnstut/griff
$ paste 1 2
1       1
ERCC-datasheet.csv      2
ERCC-datasheet2.csv     ERCC-datasheet.csv
ERCC-results.csv        ERCC-datasheet2.csv
align.sh        ERCC-results.csv
bam     align.sh
compare.txt     bam
compare2.txt    compare.txt
counts - no -g gene_name.txt    compare2.txt
counts.txt      counts - no -g gene_name.txt
counts.txt.summary      counts.txt
deseq1.r        counts.txt.summary
deseq2.r        deseq1.r
edger.r deseq2.r
griffith-align.sh       edger.r
griffith-count.sh       griffith-align.sh
griffith-getdata.sh     griffith-count.sh
norm-matrix-deseq1.txt  griffith-getdata.sh
norm-matrix-deseq2.txt  norm-matrix-deseq1.txt
norm-matrix-edgeR.txt   norm-matrix-deseq2.txt
reads   norm-matrix-edgeR.txt
refs    reads
results.txt     refs
results_deseq1.txt      results.txt
results_deseq2.txt      results_deseq1.txt
results_edger.txt       results_deseq2.txt
runlog.txt      results_edger.txt
simple_counts.txt       runlog.txt
table1  simple_counts.txt
table1 - Copy   table1
table2  table1 - Copy
table2 - Copy   table2
        table2 - Copy
(bioinfo)
xxx@Bob ~/rnstut/griff
```
Since I only see the `^M` if I do the `less` command, I did this as well:

```bash
$ paste 1 2 > test.txt
(bioinfo)
xxx@Bob ~/rnstut/griff
$ less test.txt
```
Output of the preceding command:
```
1       1
ERCC-datasheet.csv      2
ERCC-datasheet2.csv     ERCC-datasheet.csv
ERCC-results.csv        ERCC-datasheet2.csv
align.sh        ERCC-results.csv
bam     align.sh
compare.txt     bam
compare2.txt    compare.txt
counts - no -g gene_name.txt    compare2.txt
counts.txt      counts - no -g gene_name.txt
counts.txt.summary      counts.txt
deseq1.r        counts.txt.summary
deseq2.r        deseq1.r
edger.r deseq2.r
griffith-align.sh       edger.r
griffith-count.sh       griffith-align.sh
griffith-getdata.sh     griffith-count.sh
norm-matrix-deseq1.txt  griffith-getdata.sh
norm-matrix-deseq2.txt  norm-matrix-deseq1.txt
norm-matrix-edgeR.txt   norm-matrix-deseq2.txt
reads   norm-matrix-edgeR.txt
refs    reads
results.txt     refs
results_deseq1.txt      results.txt
results_deseq2.txt      results_deseq1.txt
results_edger.txt       results_deseq2.txt
runlog.txt      results_edger.txt
simple_counts.txt       runlog.txt
table1  simple_counts.txt
table1 - Copy   table1
table2  table1 - Copy
table2 - Copy   table2
        table2 - Copy
```

No `^M` in sight. Not sure why they were made before, but it's very reproducible in my environment when using the guide.
