### ISSUE TITLE
Suggested edits to some typos and possibly confusing wording in the Functional analysis section

### ISSUE THREAD

**Issue by bmillerlab** [biostars/biostar-handbook-issues#50]
[Hi. I used to have a fork to the original version of the handbook that I would read and then send suggestions to ialbert for changes using a pull-request.  After I finished the first version I wasn't using the handbook anymore.  Now there are additional topics I'm learning about in the newer version.  Since I don't have a fork, I just cut and pasted the following sections and added the possible changes to them. Unfortunately it is hard to see where I made changes, so if possible I used **bold** around the last word I left before cutting text (this doesn't really work at the beginning of sentences so I just put ** **), and I used *italics* for any suggested rewording.  Best, Paige]

Are there different ways to compute ORA analyses?
If you followed the section on Gene Ontology, you know that the GO files have a relatively simple **format**. Moreover, the data structure is that of a tree **(network)**. *To build* a program that assigns counts to each node and *that* can traverse the tree* , * is a standard problem that requires only moderately advanced programming skill.

** **Data interpretation is such an acute problem, *however*, there always seems to be a shortage of tools that can perform the ORA analysis in one specific way. ** **A cottage industry of *hundreds of* ORA tools *now* ** exists**- the vast majority *have been* abandoned, *and when run* fail** ** or even worse* ,* *tacitly give* the wrong answer** **.

Moreover, the accuracy of a method will critically depend **on ** integrating the most up to date information. As a tale of caution, we note that the DAVID: Functional Annotation Tool was not updated from 2010 to 2016! Over this time it was unclear to users whether the data that the server operate*d* on include*d* the most up to date information. New functions and annotations are added on an almost weekly basis *to functional annotation databases and* **over**  many years **this** *increased the difference between DAVID data and the available data* ** ** considerably. We believe that by the end **of** 2016 DAVID operated on a mere 20% of the total ** information ** *available*. Nevertheless, it had gained thousands of citations every single year *after the 2010 update*.

**Comment by ialbert** [comment]
The chapter has been completely rewritten in the second edition.
