### ISSUE TITLE
More suggested edits:

### ISSUE THREAD

**Issue by bmillerlab** [biostars/biostar-handbook-issues#52]
Do the GO annotations change?
The latest GO data download produces a very different report than **the** *first list*. Notably HLA genes are not in the top ten anymore. *This* reinforces the ephemeral nature of annotations - as new information or different filtering *parameters* are applied the information **content** *will* drastically shift. Why did the HLA genes *disappear*? Was that an error. Probably... but what does it mean for the publications that *were based on research completed* during *the* **time ** the error was present? Was anyone ever publicly notified about *the error*? We discovered this discrepancy by accident... *This demonstrates that* not everything **is** *going* well in the GO world....

The following is a description *of* a discovery process that may not *even* apply anymore but *it* is educational to *learn about*.

As we can see, the most annotated protein is P04637, a cellular tumor antigen p53, which acts as a tumor suppressor in many tumor types. It corresponds to the gene TP53.

The most annotated gene was HLA-B. As it happens, this is a gene that we were unable to find right away when searching for it on the official gene name nomenclature (HGNC).

It is one of those &$!*&@!@ moments that every bioinformatician will have to learn to deal with:

The most annotated gene in the GO *database* seemingly cannot be found when searching for it in HGNC, the repository that is supposed to be the authoritative resource for the domain!

The cause is both simple and infuriating: the search for HLA-B finds over a thousand entries related to HLA-B but the gene that is actually named HLA-B turns up only on the second page of hits, buried among entries distantly related to it.

Situations like this, where seemingly mundane tasks suddenly require problem solving, are very common in bioinformatics. Keep that in mind the next time something completely surreal seems to happen.

An alternative and much better maintained resource*, GeneCards,* allows you to locate the gene by name right away.

How complete is the GO?
We may wonder: how complete are these GO annotations? Would it be possible to estimate what percent of all functional annotations have been discovered so far?

While that question is too abstract for our liking, we could tabulate the dates assigned to each *piece of* evidence and see how many pieces of evidence are produced per year.

It is "reasonably simple" to extract and tabulate the date information from the two files that we downloaded to get the rate of information growth in the GO:

# Don't worry about this command if you don't get it yet.
# We'll cover it later but we just want to demonstrate some results.
cat assoc.txt \
| cut -f 14 \
| awk '{ print substr($1, 1, 4) }' \
| sort \
| uniq -c \
| sort -k 2,2 -n \
| awk '{ print  $2 "\t" $1 }'
Produces the number of annotations verified in a given year.

...
2008    9682
2009    13322
2010    15026
2011    23490
2012    16428
2013    60555
2014    34925
2015    33096
2016    235077
This result is quite surprising, and we don't quite know what to make of it. Is seems that most evidence is assigned to the latest year - 2016. Or maybe there is some sort of quirk in the system that assigns the latest date to every *piece of* evidence that is being re-observed? We don't know.

There is a also a *surprising* dip in the number of annotations in 2012, then a subsequent *increase* in 2013 *that can not be easily explained.*

**Comment by ialbert** [comment]
The chapter has been completely rewritten in the second edition.
