### ISSUE TITLE
Version 5.60 mismatch

### ISSUE THREAD

**Issue by gen0micsc0re** [biostars/biostar-handbook-issues#53]
After following the instructions to setup my computer and running the doctor, I get the following 2 errors:

# Version 5.60 mismatch for: efetch -version
# Version 5.60 mismatch for: esearch -version

Thanks for any advice

**Comment by ialbert** [comment]
If you run 

    efetch -version

what does it say for version?

**Comment by gen0micsc0re** [comment]
the command
esearch -version 
returns the same version (10.2)

**Comment by ialbert** [comment]
ok, bug in the doctor.py once the version numbers rolled over `10` the string comparison fails. 

All good on your side, will fix this soon in the doctor. 

Thanks for reporting.

**Comment by ialbert** [comment]
doctor.py updated to stop raising an error of this case.

You will need to reinstall doctor.py or ignore this particular error.

The setup page has been updated (make sure to press reload to get the new version):

https://www.biostarhandbook.com/setup/setup.html
