### ISSUE TITLE
Setting up the Computer: Doctor.py returns errors

### ISSUE THREAD

**Issue by koh30297** [biostars/biostar-handbook-issues#54]
Hello Biostar, 
I've tried to install conda and the tools on Windows 10 (Ubuntu app) by following steps listed in the book. However, when I ran doctor.py, the following list of errors showed up: 
$ ~/bin/doctor.py
Doctor! Doctor! Give me the news.
Checking 15 symptoms...
Missing program: R
Version 5.60 mismatch for: efetch -version
Version 5.60 mismatch for: esearch -version
Optional program not found: global-align.sh
Optional program not found: local-align.sh
Your system shows 3 errors.
See also: doctor.py --fixme
(bioinfo)

I believed this is the so called "Chronic Case of Entrez Direct" listed in the book. Typing ~/bin/doctor.py --fixme gives me the following output. 
# Install everything:

curl http://data.biostarhandbook.com/install/conda.txt | xargs conda install -y

# A chronic case of Entrez Direct?

mkdir -p ~/src
curl ftp://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/edirect.zip > ~/src/edirect.zip
unzip -o ~/src/edirect.zip  -d ~/src
echo 'export PATH=~/src/edirect:$PATH' >> ~/.bashrc
source  ~/.bashrc

Nonetheless, I tried ~/bin/doctor.py --fixme | bash and manually typed in the commands but neither of these worked. When I entered "efetch", it returns "Can't locate HTML/Entities.pm in @INC". All the above code was executed in the environment "bioinfo" created beforehand. Hoever, the suggested solution (2 lines of code installing parallel and perl 5.26) on the website do not solve the problems. Any thoughts on how I could progress?

**Comment by ialbert** [comment]
Apologies for the setback, there have been quite recent new releases that seem to break some of the code, this will be fixed today with new instructions (this ticket will be updated at that time), see also

https://github.com/biostars/biostar-handbook-issues/issues/53

**Comment by ialbert** [comment]
doctor.py updated to stop raising an error of this case. You will need to reinstall doctor.py or ignore this particular error.

The setup page has been updated (make sure to press reload to get the new version):

https://www.biostarhandbook.com/setup/setup.html

In particular, we added a section on fixing errors titled: **How do I fix installation problems?**, that recommends reinitializing the entire environment. Can you please try this and see if that fixes your problems. If not let us know the platform you are having the trouble on:

**Comment by koh30297** [comment]
Thanks for the fix! Doctor.py no longer reports the error. 

However, when I entered efetch, the following message now shows up "Db value not found in fetch input". I am not sure if I can ignore this message. My efetch version is 10.3. I'm not sure what this means because entrez direct is installed for sure. I've also tried the solutions provided by doctor.py --fixme | bash, but it still doesn't work. 

All the above was run on Windows 10 with Ubuntu app.

**Comment by ialbert** [comment]
> Db value not found in fetch input

that is not an error, just a silly way efetch tells you that you have not request anything. Just give it something to do

     efetch -db nuccore -id 2 -format fasta

it seems the error has been solved.

**Comment by jiuchao** [comment]
I encountered the same problem when setting up my computer, but got it solved after updating my doctor.py. However, even though it does not report errors, there are still two optional programs not found: global-align.sh and local-align.sh. Does that matter? What kind of code could I use if I want to install them?

**Comment by ialbert** [comment]
later on, when you get to alignments there will be code that install the two optional programs.
