### ISSUE TITLE
Error running curl http://data.biostarhandbook.com/install/bash_profile.txt >> ~/.bash_profile

### ISSUE THREAD

**Issue by Mari2061** [biostars/biostar-handbook-issues#57]
Hello, I´m just starting with the book installation process
While Running curl http://data.biostarhandbook.com/install/bash_profile.txt >> ~/.bash_profile
on Windows 10 bash (Ubuntu 18.04) I get

`$` curl http://data.biostarhandbook.com/install/bash_profile.txt >> ~/.bash_profile
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0curl: (7) Failed to connect to data.biostarhandbook.com port 80: Connection refused

**Comment by ialbert** [comment]
It is strange error, it does work for me.

http://data.biostarhandbook.com/install/bash_profile.txt

Click on the link above, does it work for you? Use the same computer that you would be installing on. If so the file is there and the server is allowing access to it. Could there be some sort of network permission (firewall) on your side that does not allow access?

you can also test it out without appending to a file via

    curl http://data.biostarhandbook.com/install/bash_profile.txt

**Comment by Mari2061** [comment]
Hi thanks for the fast answer
The link works.
But, the 
> you can also test it out without appending to a file via
curl http://data.biostarhandbook.com/install/bash_profile.txt
did not

I still get
curl: (7) Failed to connect to data.biostarhandbook.com port 80: Connection refused.
PD:
I am connected through a proxy, but it seems to be working well. Also I´m in Cuba, I don't know if maybe that´s an issue accessing to biostars server

**Comment by ialbert** [comment]
this some sort of network problem where you would have to set up your subsystem to use a proxy
https://help.ubuntu.com/community/AptGet/Howto#Setting_up_apt-get_to_use_a_http-proxy

**Comment by ialbert** [comment]
or this perhaps

https://github.com/Microsoft/WSL/issues/1107

**Comment by Mari2061** [comment]
Hello again, I changed permanently to Ubuntu 18.04, and I have started again the setting up my computer step, again I cannot access to curl http://data.biostarhandbook.com/install/bash_profile.txt via terminal. I downloaded the bash_profile.txt, what is the next step??.
Thanks a lot in advanced, and sorry I have little-to no experience at ubuntu ( all I know is from the UNIX boot camp chapter)

**Comment by ialbert** [comment]
what is the error that you are getting?

if you cannot run `curl` it will be a problem that will keep on giving - so best troubleshoot that. How come `curl` does not work?

**Comment by ialbert** [comment]
sounds like the internet was limited at the location
