### ISSUE TITLE
A problem with efetch

### ISSUE THREAD

**Issue by ThePussyHunter** [biostars/biostar-handbook-issues#60]
Hello. I have a problem with efetch program:
`Can't locate HTML/Entities.pm in @INC (you may need to install the HTML::Entities module) (@INC contains: /Users/nail/miniconda3/envs/biostar_book/bin/aux/lib/perl5 /Users/nail/miniconda3/envs/biostar_book/lib/perl5/site_perl/5.22.0/darwin-thread-multi-2level /Users/nail/miniconda3/envs/biostar_book/lib/perl5/site_perl/5.22.0 /Users/nail/miniconda3/envs/biostar_book/lib/perl5/5.22.0/darwin-thread-multi-2level /Users/nail/miniconda3/envs/biostar_book/lib/perl5/5.22.0 .) at /Users/nail/miniconda3/envs/biostar_book/bin/edirect.pl line 71.
BEGIN failed--compilation aborted at /Users/nail/miniconda3/envs/biostar_book/bin/edirect.pl line 71.
(biostar_book)`

I tried to uninstall and create new environment but these actions didn't help.
Also I run the doctor.py:

```
$ ~/bin/doctor.py
Doctor! Doctor! Give me the news.
Checking 13 symptoms...
Optional program not found: global-align.sh
Optional program not found: local-align.sh
You are doing well!
(biostar_book) 
```

Then I entered the commands advised by doctor.py:
`mkdir -p ~/src
curl ftp://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/edirect.zip > ~/src/edirect.zip
unzip -o ~/src/edirect.zip  -d ~/src
echo 'export PATH=~/src/edirect:$PATH' >> ~/.bash_profile
source  ~/.bash_profile`

This didn't help. But efetch works corrects when is run out of any environment.

**Comment by ialbert** [comment]
yes, this the most common ongoing problem that we have with conda, perl gets out of whack everyone once in a while - where in fact the command works if nothing were installed in the first place

https://www.biostarhandbook.com/2nd-edition/how-to-set-up-your-computer.html

and take a look at

"How do I fix my Chronic Case of Entrez Direct?"

    conda install perl-net-ssleay

finally please change your handle name - it is embarrassingly offensive - I have seriously considered not responding - but I am willing to give you the benefit of doubt - but will not respond again and your username will be blocked
