### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by Aps2019** [biostars/biostar-handbook-issues#61]
Hi, I get these errors while installing the tools. I've tried deactivating and creating steps several times as recommended by doctor.py --fixme. but keep getting these errors...HELP!

The following packages will be UPDATED:

  cryptography       pkgs/main::cryptography-2.5-py36h1ba5~ --> conda-forge::cryptography-2.5-py36hb7f436b_1

The following packages will be SUPERSEDED by a higher-priority channel:

  python                 pkgs/main::python-3.6.8-h0371630_0 --> conda-forge::python-3.6.7-hd21baee_1002

The following packages will be DOWNGRADED:

  openssl                              1.1.1a-h14c3975_1000 --> 1.0.2p-h14c3975_1002

Downloading and Extracting Packages
bcftools-1.9         | 813 KB    | ############################################################## | 100%
cryptography-2.5     | 645 KB    | ############################################################## | 100%
perl-5.26.2          | 15.4 MB   | ############################################################## | 100%
Preparing transaction: done
Verifying transaction: failed

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'annotation/hg19_RefSeq_exon.txt'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'annotation/hg38_RefSeq_exon.txt'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'annotation/mm10_RefSeq_exon.txt'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'annotation/mm9_RefSeq_exon.txt'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/detectionCall'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/exactSNP'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/featureCounts'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/flattenGTF'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/propmapped'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/qualityScores'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/removeDup'
specified in the package manifest cannot be found.

SafetyError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/repair'
has an incorrect size.
  reported size: 1894520 bytes
  actual size: 540672 bytes

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/subindel'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/subjunc'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/subread-align'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/subread-buildindex'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/subread-fullscan'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/txUnique'
specified in the package manifest cannot be found.

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::openjdk-11.0.1-h14c3975_1014, conda-forge::freetype-2.9.1-h94bbf69_1005
  path: 'lib/libfreetype.so'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda::bbmap-38.22-h14c3975_1, bioconda::entrez-direct-10.2-pl526_0
  path: 'bin/conda_build.sh'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h14c3975_1002, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'man/man3/Cwd.3'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h14c3975_1002, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'man/man3/File::Spec.3'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h14c3975_1002, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'man/man3/File::Spec::AmigaOS.3'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h14c3975_1002, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'man/man3/File::Spec::Cygwin.3'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h14c3975_1002, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'man/man3/File::Spec::Epoc.3'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h14c3975_1002, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'man/man3/File::Spec::Functions.3'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h14c3975_1002, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'man/man3/File::Spec::Mac.3'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h14c3975_1002, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'man/man3/File::Spec::OS2.3'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h14c3975_1002, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'man/man3/File::Spec::Unix.3'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h14c3975_1002, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'man/man3/File::Spec::VMS.3'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h14c3975_1002, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'man/man3/File::Spec::Win32.3'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda::perl-compress-raw-bzip2-2.084-pl526hfc679d8_0, bioconda::perl-digest-hmac-1.03-pl526_2, bioconda::perl-digest-md5-2.55-pl526_0, bioconda::perl-extutils-makemaker-7.34-pl526_3, bioconda::perl-html-tagset-3.20-pl526_3, bioconda::perl-io-html-1.001-pl526_2, bioconda::perl-io-zlib-1.10-pl526_2, bioconda::perl-scalar-list-utils-1.45-pl526h470a237_3, conda-forge::perl-xml-parser-2.44_01-pl526h3a4f0e9_1, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'lib/5.26.2/x86_64-linux-thread-multi/perllocal.pod'

**Comment by ialbert** [comment]
First make sure that you follow the steps in the second edition shown here:

https://www.biostarhandbook.com/2nd-edition/how-to-set-up-your-computer.html

there should be no messages for "UPDATED", "SUPERSEEDEDE", "DOWNGRADED"  since it should be a new installation. 

I have just tried the following:

    conda --version

it prints

    conda 4.6.2

then I did the following  

    conda create --name foo python=3.6

    conda activate foo

    curl http://data.biostarhandbook.com/install/conda.txt | xargs conda install -y

and it all installed correctly. It is important that you have the latest conda and that you follow the latest instructions.

**Comment by Aps2019** [comment]
Thanks ialbert! The conda version I have is 4.6.7

I tried deactivating the previous environment (bioinfo) and followed your instructions as above. I don't get the "updated", "supersede" or "downgraded" messages but still get the following-

bioawk             bioconda/linux-64::bioawk-1.0-ha92aebf_3
  blas               pkgs/main/linux-64::blas-1.0-mkl
  blast              bioconda/linux-64::blast-2.7.1-h4422958_6
  boost              conda-forge/linux-64::boost-1.67.0-py36h3e44d54_0
  boost-cpp          conda-forge/linux-64::boost-cpp-1.67.0-h3a22d5f_0
  bowtie2            bioconda/linux-64::bowtie2-2.3.4.3-py36he860b03_1
  bwa                bioconda/linux-64::bwa-0.7.17-h84994c4_5
  bz2file            conda-forge/noarch::bz2file-0.98-py_0
  bzip2              conda-forge/linux-64::bzip2-1.0.6-h14c3975_1002
  curl               conda-forge/linux-64::curl-7.64.0-h646f8bb_0
  cutadapt           bioconda/linux-64::cutadapt-1.18-py36h14c3975_1
  datamash           conda-forge/linux-64::datamash-1.4-h14c3975_1000
  emboss             bioconda/linux-64::emboss-6.6.0-h6debe1e_0
  entrez-direct      bioconda/linux-64::entrez-direct-10.2-pl526_0
  expat              conda-forge/linux-64::expat-2.2.5-hf484d3e_1002
  fastqc             bioconda/linux-64::fastqc-0.11.8-1
  font-ttf-dejavu-s~ pkgs/main/noarch::font-ttf-dejavu-sans-mono-2.37-h6964260_0
  fontconfig         conda-forge/linux-64::fontconfig-2.13.1-h2176d3f_1000
  freebayes          bioconda/linux-64::freebayes-1.2.0-py36h82df9c4_3
  freetype           conda-forge/linux-64::freetype-2.9.1-h94bbf69_1005
  giflib             conda-forge/linux-64::giflib-5.1.4-h14c3975_1001
  gmp                conda-forge/linux-64::gmp-6.1.2-hf484d3e_1000
  gnutls             conda-forge/linux-64::gnutls-3.5.19-h2a4e5f8_1
  hisat2             bioconda/linux-64::hisat2-2.1.0-py36h2d50403_1
  htslib             bioconda/linux-64::htslib-1.9-h47928c2_5
  icu                conda-forge/linux-64::icu-58.2-hf484d3e_1000
  intel-openmp       pkgs/main/linux-64::intel-openmp-2019.1-144
  jpeg               conda-forge/linux-64::jpeg-9c-h14c3975_1001
  krb5               conda-forge/linux-64::krb5-1.16.3-hc83ff2d_1000
  libcurl            conda-forge/linux-64::libcurl-7.64.0-h01ee5af_0
  libdeflate         bioconda/linux-64::libdeflate-1.0-h14c3975_1
  libedit            conda-forge/linux-64::libedit-3.1.20170329-hf8c457e_1001
  libgd              conda-forge/linux-64::libgd-2.2.5-h0d07dcb_1005
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.2.0-hdf63c60_3
  libiconv           conda-forge/linux-64::libiconv-1.15-h14c3975_1004
  libpng             conda-forge/linux-64::libpng-1.6.36-h84994c4_1000
  libssh2            conda-forge/linux-64::libssh2-1.8.0-h1ad7b7a_1003
  libtiff            conda-forge/linux-64::libtiff-4.0.10-h648cc4a_1001
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000
  libwebp            conda-forge/linux-64::libwebp-1.0.2-h576950b_1
  libxml2            conda-forge/linux-64::libxml2-2.9.8-h143f9aa_1005
  minimap2           bioconda/linux-64::minimap2-2.15-h84994c4_1
  mkl                pkgs/main/linux-64::mkl-2019.1-144
  mkl_fft            conda-forge/linux-64::mkl_fft-1.0.10-py36h14c3975_1
  mkl_random         conda-forge/linux-64::mkl_random-1.0.2-py36h637b7d7_2
  nettle             conda-forge/linux-64::nettle-3.3-0
  numpy              pkgs/main/linux-64::numpy-1.15.4-py36h7e9f1db_0
  numpy-base         pkgs/main/linux-64::numpy-base-1.15.4-py36hde5b4d6_0
  openjdk            conda-forge/linux-64::openjdk-11.0.1-h14c3975_1014
  parallel           conda-forge/linux-64::parallel-20190122-0
  pcre               conda-forge/linux-64::pcre-8.41-hf484d3e_1003
  perl               conda-forge/linux-64::perl-5.26.2-h14c3975_1002
  perl-app-cpanminus bioconda/linux-64::perl-app-cpanminus-1.7044-pl526_1
  perl-archive-tar   bioconda/linux-64::perl-archive-tar-2.32-pl526_0
  perl-base          bioconda/linux-64::perl-base-2.23-pl526_1
  perl-business-isbn bioconda/linux-64::perl-business-isbn-3.004-pl526_0
  perl-business-isb~ bioconda/linux-64::perl-business-isbn-data-20140910.003-pl526_0
  perl-carp          bioconda/linux-64::perl-carp-1.38-pl526_1
  perl-compress-raw~ bioconda/linux-64::perl-compress-raw-bzip2-2.084-pl526hfc679d8_0
  perl-compress-raw~ bioconda/linux-64::perl-compress-raw-zlib-2.084-pl526h2d50403_0
  perl-constant      bioconda/linux-64::perl-constant-1.33-pl526_1
  perl-data-dumper   bioconda/linux-64::perl-data-dumper-2.173-pl526_0
  perl-digest-hmac   bioconda/linux-64::perl-digest-hmac-1.03-pl526_2
  perl-digest-md5    bioconda/linux-64::perl-digest-md5-2.55-pl526_0
  perl-encode        bioconda/linux-64::perl-encode-2.88-pl526_1
  perl-encode-locale bioconda/linux-64::perl-encode-locale-1.05-pl526_6
  perl-exporter      bioconda/linux-64::perl-exporter-5.72-pl526_1
  perl-exporter-tiny bioconda/linux-64::perl-exporter-tiny-1.002001-pl526_0
  perl-extutils-mak~ bioconda/linux-64::perl-extutils-makemaker-7.34-pl526_3
  perl-file-listing  bioconda/linux-64::perl-file-listing-6.04-pl526_1
  perl-file-path     bioconda/linux-64::perl-file-path-2.15-pl526_0
  perl-file-temp     bioconda/linux-64::perl-file-temp-0.2304-pl526_2
  perl-html-parser   bioconda/linux-64::perl-html-parser-3.72-pl526h2d50403_4
  perl-html-tagset   bioconda/linux-64::perl-html-tagset-3.20-pl526_3
  perl-html-tree     bioconda/linux-64::perl-html-tree-5.07-pl526_0
  perl-http-cookies  bioconda/linux-64::perl-http-cookies-6.04-pl526_0
  perl-http-daemon   bioconda/linux-64::perl-http-daemon-6.01-pl526_1
  perl-http-date     bioconda/linux-64::perl-http-date-6.02-pl526_3
  perl-http-message  bioconda/linux-64::perl-http-message-6.18-pl526_0
  perl-http-negotia~ bioconda/linux-64::perl-http-negotiate-6.01-pl526_2
  perl-io-compress   bioconda/linux-64::perl-io-compress-2.084-pl526hfc679d8_0
  perl-io-html       bioconda/linux-64::perl-io-html-1.001-pl526_2
  perl-io-socket-ssl bioconda/linux-64::perl-io-socket-ssl-2.060-pl526_0
  perl-io-zlib       bioconda/linux-64::perl-io-zlib-1.10-pl526_2
  perl-libwww-perl   bioconda/linux-64::perl-libwww-perl-6.36-pl526_0
  perl-list-moreuti~ bioconda/linux-64::perl-list-moreutils-0.428-pl526_1
  perl-list-moreuti~ bioconda/linux-64::perl-list-moreutils-xs-0.428-pl526_0
  perl-lwp-mediatyp~ bioconda/linux-64::perl-lwp-mediatypes-6.02-pl526_3
  perl-lwp-protocol~ bioconda/linux-64::perl-lwp-protocol-https-6.07-pl526_4
  perl-mime-base64   bioconda/linux-64::perl-mime-base64-3.15-pl526_1
  perl-mozilla-ca    bioconda/linux-64::perl-mozilla-ca-20180117-pl526_0
  perl-net-http      bioconda/linux-64::perl-net-http-6.18-pl526_0
  perl-net-ssleay    bioconda/linux-64::perl-net-ssleay-1.85-pl526h9dad42d_0
  perl-ntlm          bioconda/linux-64::perl-ntlm-1.09-pl526_3
  perl-parent        bioconda/linux-64::perl-parent-0.236-pl526_1
  perl-pathtools     bioconda/linux-64::perl-pathtools-3.73-h470a237_2
  perl-scalar-list-~ bioconda/linux-64::perl-scalar-list-utils-1.45-pl526h470a237_3
  perl-socket        bioconda/linux-64::perl-socket-2.027-pl526_1
  perl-storable      bioconda/linux-64::perl-storable-3.11-pl526_0
  perl-test-more     bioconda/linux-64::perl-test-more-1.001002-pl526_1
  perl-test-require~ bioconda/linux-64::perl-test-requiresinternet-0.05-pl526_0
  perl-time-local    bioconda/linux-64::perl-time-local-1.28-pl526_1
  perl-try-tiny      bioconda/linux-64::perl-try-tiny-0.30-pl526_0
  perl-uri           bioconda/linux-64::perl-uri-1.76-pl526_0
  perl-www-robotrul~ bioconda/linux-64::perl-www-robotrules-6.02-pl526_3
  perl-xml-namespac~ bioconda/linux-64::perl-xml-namespacesupport-1.12-pl526_0
  perl-xml-parser    conda-forge/linux-64::perl-xml-parser-2.44_01-pl526h3a4f0e9_1
  perl-xml-sax       bioconda/linux-64::perl-xml-sax-1.00-pl526_0
  perl-xml-sax-base  bioconda/linux-64::perl-xml-sax-base-1.09-pl526_0
  perl-xml-sax-expat bioconda/linux-64::perl-xml-sax-expat-0.51-pl526_2
  perl-xml-simple    bioconda/linux-64::perl-xml-simple-2.25-pl526_0
  perl-xsloader      bioconda/linux-64::perl-xsloader-0.24-pl526_0
  picard             bioconda/noarch::picard-2.18.26-0
  pigz               conda-forge/linux-64::pigz-2.3.4-0
  readseq            bioconda/noarch::readseq-2.1.30-1
  samtools           bioconda/linux-64::samtools-1.9-h57cc563_6
  seqkit             bioconda/linux-64::seqkit-0.10.0-1
  seqtk              bioconda/linux-64::seqtk-1.3-h84994c4_1
  snpeff             bioconda/noarch::snpeff-4.3.1t-1
  sra-tools          bioconda/linux-64::sra-tools-2.9.1_1-h470a237_0
  subread            bioconda/linux-64::subread-1.6.3-h84994c4_1
  tbb                conda-forge/linux-64::tbb-2019.3-h6bb024c_1000
  trimmomatic        bioconda/noarch::trimmomatic-0.38-1
  vt                 bioconda/linux-64::vt-2015.11.10-he941832_3
  xopen              bioconda/noarch::xopen-0.5.0-py_0


Preparing transaction: done
Verifying transaction: failed

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'annotation/hg19_RefSeq_exon.txt'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'annotation/hg38_RefSeq_exon.txt'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'annotation/mm10_RefSeq_exon.txt'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'annotation/mm9_RefSeq_exon.txt'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/detectionCall'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/exactSNP'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/featureCounts'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/flattenGTF'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/propmapped'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/qualityScores'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/removeDup'
specified in the package manifest cannot be found.

SafetyError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/repair'
has an incorrect size.
  reported size: 1894520 bytes
  actual size: 540672 bytes

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/subindel'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/subjunc'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/subread-align'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/subread-buildindex'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/subread-fullscan'
specified in the package manifest cannot be found.

CondaVerificationError: The package for subread located at /home/ps5511/miniconda3/pkgs/subread-1.6.3-h84994c4_1
appears to be corrupted. The path 'bin/txUnique'
specified in the package manifest cannot be found.

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::openjdk-11.0.1-h14c3975_1014, conda-forge::freetype-2.9.1-h94bbf69_1005
  path: 'lib/libfreetype.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda::bbmap-38.22-h14c3975_1, bioconda::entrez-direct-10.2-pl526_0
  path: 'bin/conda_build.sh'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h14c3975_1002, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'man/man3/Cwd.3'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h14c3975_1002, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'man/man3/File::Spec.3'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h14c3975_1002, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'man/man3/File::Spec::AmigaOS.3'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h14c3975_1002, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'man/man3/File::Spec::Cygwin.3'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h14c3975_1002, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'man/man3/File::Spec::Epoc.3'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h14c3975_1002, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'man/man3/File::Spec::Functions.3'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h14c3975_1002, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'man/man3/File::Spec::Mac.3'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h14c3975_1002, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'man/man3/File::Spec::OS2.3'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h14c3975_1002, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'man/man3/File::Spec::Unix.3'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h14c3975_1002, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'man/man3/File::Spec::VMS.3'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::perl-5.26.2-h14c3975_1002, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'man/man3/File::Spec::Win32.3'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda::perl-compress-raw-bzip2-2.084-pl526hfc679d8_0, bioconda::perl-digest-hmac-1.03-pl526_2, bioconda::perl-digest-md5-2.55-pl526_0, bioconda::perl-extutils-makemaker-7.34-pl526_3, bioconda::perl-html-tagset-3.20-pl526_3, bioconda::perl-io-html-1.001-pl526_2, bioconda::perl-io-zlib-1.10-pl526_2, bioconda::perl-scalar-list-utils-1.45-pl526h470a237_3, conda-forge::perl-xml-parser-2.44_01-pl526h3a4f0e9_1, bioconda::perl-pathtools-3.73-h470a237_2
  path: 'lib/5.26.2/x86_64-linux-thread-multi/perllocal.pod'

**Comment by ialbert** [comment]
I think something is wrong with entire miniconda3 directory. Note how all the files are corrupted - feels 

look at the file conda file:

* <http://data.biostarhandbook.com/install/conda.txt>

then install one or a few tools at time. See how that goes

    conda install perl perl-net-ssleay seqkit parallel entrez-direct 

then 

    conda install  minimap2 bwa htslib bowtie2

and so one

The original installation attempts to do it all in one shot - but that is clearly not working and keeps you installing any of them.

**Comment by ialbert** [comment]
The bioconda recipes have been updated at bioconda.

New installations should not experience this error anymore.

**Comment by Aps2019** [comment]
Hi ialbert,
I followed instructions in the update provided...I tried the following- first to remove the conda setup file with:
# Remove conda setup file.
rm ~/.condarc

Followed by 

wget https://repo.continuum.io/miniconda/Miniconda3-4.3.21-Linux-x86_64.sh
bash Miniconda3-4.3.21-Linux-x86_64.sh

I get the following-
ERROR: File or directory already exists: /home/ps5511/miniconda3

**Comment by ialbert** [comment]
looks like you already installed conda

the name of the conda directory is `miniconda3` and would need to be also deleted if you really wanted to reinstall conda from scratch 

    rm -rf miniconda3
