### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by linzhangTuesday** [biostars/biostar-handbook-issues#62]
Hi I tried every step in 2nd edition of Biostar Handbook and the doctor.py kept saying optinal program not found for global-align.sh and local-align.sh. I have also removed bioinfo and restarted the environment building and tools installation again. But the same issues appear. 
Any comments or suggestions would be highly appreciated! Thanks in advance : )

**Comment by ialbert** [comment]
the optional programs are not installed right away. That's what I was trying to convey by saying "optional" program.

sorry about the misunderstanding. I will change the wording. Those programs are installed in the alignment chapter:

https://www.biostarhandbook.com/2nd-edition/global-and-local-alignments.html

**Comment by linzhangTuesday** [comment]
Thank you very much for the information and quick response!
________________________________
