### ISSUE TITLE
Chronic case of Entrez direct

### ISSUE THREAD

**Issue by birdtj** [biostars/biostar-handbook-issues#63]
Hi There,

I am totally new to the CLI but have just bought the biostar handbook and looking forward to going through it. I am a windows 10 user.

I however cannot the line to work - efetch -db nuccore -id 2 -format gb

It worked for the very first day I setup my computer whereby I produced what was described in the handbook. However when I revisited the handbook a couple of days later is was not working. 

I have tried using the workarounds listed in the book - 

# Reinstall the `perl-net-ssleay` library
conda install perl-net-ssleay

and then

# Uninstall perl.
conda uninstall perl
# Reinstall perl
conda install perl
# Reinstall a perl library
conda install perl-net-ssleay
# Reinstall all tools.
curl http://data.biostarhandbook.com/install/conda.txt | xargs conda install -y

I have completely removed ubuntu from my windows laptop and gone through the installation process again. This issue is still here.

I noticed on the ticket - https://github.com/bioconda/bioconda-recipes/issues/13415 
there has been some recent comments, however I did not understand these enough to resolve any issues myself.

Thanks in advance,
Toby

**Comment by ialbert** [comment]
Can you please try the install again. In the issue:

https://github.com/bioconda/bioconda-recipes/issues/13415

 a fix has been applied. Can you verify that it solves your problem as well.  Run the following:

```
conda create -y -n foo python=3.6
conda activate foo
conda install -y entrez-direct
```

then verify that `efetch` works.

**Comment by birdtj** [comment]
Hi There,

I have run those 3 lines you suggest and unfortunately efetch is still not working for me. I am still receiving the error message containing (LWP: : Protocol : https not installed ...

Initially, ubuntu wouldn't let me run  - conda create  (it gave me a message regarding the shell, which I have forgotten sorry), so first I ran - conda init bash

Do I need to reinstall the other packages prior to entrez-direct ?

Again, apologies for my lack of understanding and thank you for your fast response.

Cheers again

**Comment by ialbert** [comment]
try the following installation, it worked on my system

    conda install perl-net-ssleay==1.85

as you can see on the main ticket, work is being done but progress is sporadic

**Comment by birdtj** [comment]
Hi Istvan,

Unfortunately after running this line I now get:

$ efetch -db nuccore -id 2 -format gb
Can't locate HTML/Entities.pm in @INC (you may need to install the
HTML::Entities module) (@INC contains:
/home/birdt/src/edirect/aux/lib/perl5
/home/birdt/miniconda3/envs/bioinfo/lib/site_perl/5.26.2/x86_64-linux-thread-multi
/home/birdt/miniconda3/envs/bioinfo/lib/site_perl/5.26.2
/home/birdt/miniconda3/envs/bioinfo/lib/5.26.2/x86_64-linux-thread-multi
/home/birdt/miniconda3/envs/bioinfo/lib/5.26.2 .) at
/home/birdt/src/edirect/edirect.pl line 71.
BEGIN failed--compilation aborted at /home/birdt/src/edirect/edirect.pl
line 71.
(bioinfo)

I have been able to continue going through the handbook so far, although I
am guessing I am going to need this function working once I get a bit
further in. I might try again on another laptop and see if this helps (it
will be a windows machine also though).

If you have any ideas on what i may have done wrong (ie. setting up the
PATH maybe?) I would love to know.

Thanks,
Toby

**Comment by ialbert** [comment]
you might need to refresh install altogether. Other packages have been changed in the meantime. On my Windows Bash I can do a:

```
conda create -y -n bioinfo python=3.6
conda activate bioinfo
curl http://data.biostarhandbook.com/install/conda.txt | xargs conda install -y
```

this will drop and reinstall your environment. On my system, all tools install properly

**Comment by birdtj** [comment]
Brilliant. The refresh install has worked.

Thanks very much

**Comment by ialbert** [comment]
good to hear
