### ISSUE TITLE
Installation IOS

### ISSUE THREAD

**Issue by catarinaserrano** [biostars/biostar-handbook-issues#64]
Hi!

I am stuck in the installation process,

I already installed the conda package and then I write $conda, it shows a list of options. So, I guess my problem is in the next step. 
When I try to activate bioconda, it looks like this:

`catarinaserrano@MacBook-Pro-de-Catarina ~
$ conda config --add channels conda-forge
Warning: 'conda-forge' already in 'channels' list, moving to the top
(base) 
catarinaserrano@MacBook-Pro-de-Catarina ~
$ conda config --add channels bioconda
Warning: 'bioconda' already in 'channels' list, moving to the top
(base) 
catarinaserrano@MacBook-Pro-de-Catarina ~
$ 
`

Can someone help me? What am I doing wrong?

**Comment by ialbert** [comment]
this is just a warning, it says that it has already been added to the channel, nothing needs to be done, proceed to the next step.
