### ISSUE TITLE
The doctor says I have two missing programs

### ISSUE THREAD

**Issue by CatChenal** [biostars/biostar-handbook-issues#65]
This this is the diagnostic from doctor.py:
```
# Optional program not found: global-align.sh
# Optional program not found: local-align.sh
```
After re-running the program with `--fixme`, I get two 'fixes'. The first one is to reinstall conda, but there nothing wrongs with my environment); the second is:
```
# How to install Entrez Direct from source.
mkdir -p ~/src
curl ftp://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/edirect.zip > ~/src/edirect.zip
unzip -o ~/src/edirect.zip  -d ~/src
echo 'export PATH=~/src/edirect:$PATH' >> ~/.bash_profile
source  ~/.bash_profile
```
Could you please confirm/correct the following:
1. The above NCBI software is not part of the biostar handbook downloaded package
2. The two missing bash scripts come from the NCBI software, therefore, yes: I need to apply fix No. 2

Thanks!

**Comment by ialbert** [comment]
the two missing are optional programs and will get installed later in the book. no action is necessary.

I in the new edition I make a note that this message is not a problem, perhaps I will remove the check for them altogether

https://www.biostarhandbook.com/2nd-edition/how-to-set-up-your-computer.html

**Comment by CatChenal** [comment]
OK. I should have followed the online book, not the pdf (November 2018 edition).
