### ISSUE TITLE
Tip: alternate activation with conda

### ISSUE THREAD

**Issue by CatChenal** [biostars/biostar-handbook-issues#67]
If you initialize conda with the bash shell:
```
conda init bash
```
You will be able to initialize the `bioinfo` environment  using this command:
```
conda activate bioinfo
```
and deactivate it with:
```
conda deactivate
```
But that's only if you find the command ` source activate bioinfo` wierd, as I do!

**Comment by ialbert** [comment]
I would suggest using the second edition of the Handbook, soon the second edition will replace the current edition:

https://www.biostarhandbook.com/2nd-edition/index.html

the `conda activate bioinfo` is the new recommended approach
