### ISSUE TITLE
doctor.py installation

### ISSUE THREAD

**Issue by npwjyt** [biostars/biostar-handbook-issues#69]
Hello~
I just stated learning Biostarhandbook and I am in the middle of installation - almost done. 

I tested with doctor.py but I see

$ mkdir -p ~/bin
(bioinfo)
npwjyt@DESKTOP-DVLM831 ~
$ curl http://data.biostarhandbook.com/install/doctor.py > ~/bin/doctor.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3682  100  3682    0     0   4296      0 --:--:-- --:--:-- --:--:--  4306
(bioinfo)
npwjyt@DESKTOP-DVLM831 ~
$ chmod +x ~/bin/doctor.py
(bioinfo)
npwjyt@DESKTOP-DVLM831 ~
$ ~/bin/doctor.py
# Doctor! Doctor! Give me the news.
# Checking 13 symptoms...
# Optional program not found: global-align.sh
# Optional program not found: local-align.sh
# You are doing well!
(bioinfo)

Is there anything wrong to see
# Optional program not found: global-align.sh
# Optional program not found: local-align.sh ?

Since it is optional, can I proceed?
Or to fix it what can I do? 
I am a very beginner in programming and bioinformatics, so please let me know very easily with patience. Thanks.

**Comment by ialbert** [comment]
there is no problem, the programs are optional, see the page on the second edition:

https://www.biostarhandbook.com/2nd-edition/how-to-set-up-your-computer.html

I will remove that check now since it seems to trip up people

**Comment by ialbert** [comment]
The optional program check has been removed so that it does not confuse readers.

**Comment by npwjyt** [comment]
Thank you!

2019년 4월 8일 (월) 오전 10:24에 Istvan Albert <notifications@github.com>님이 작성:
