### ISSUE TITLE
Wrong command in "BLAST use cases"

### ISSUE THREAD

**Issue by Karyo** [biostars/biostar-handbook-issues#7]
The last command in the chapter "BLAST use cases"  shown underneath 
# Get the sequence
efetch -db nucleotide -id AKC37152 -format fasta > AKC37152.fa

should be "protein" instead of "nucleotide".

Thanks.

**Comment by ialbert** [comment]
Thanks for the report. It has now been fixed in the sources. The change will be made live on the site later this week (or early next week).
