### ISSUE TITLE
No available formula with the name "edirect" 

### ISSUE THREAD

**Issue by DawnWangfbio** [biostars/biostar-handbook-issues#71]
Hello.I am going to install efetch using "brew install edirect" on Mac, here is the problem I met:
Error: No available formula with the name "edirect" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
This problem is also met when I try to install readseq by using"brew install readseq".
I can't figue out.  Hoping someone can help me.

**Comment by ialbert** [comment]
brew is not supported anymore.

please use the new edition installation

    conda install entrez-direct
