### ISSUE TITLE
brew --with-default-names no longer available

### ISSUE THREAD

**Issue by spitfire115** [biostars/biostar-handbook-issues#72]
when I follow the Biostar handbook to setup and install libraries into my MacBook using Home-brew, there is a line `brew install findutils --with-default-names` but then the with-default-names function is no longer available and error return Error: invalid option: --default-names.

My question is that is it okay to install findutils directly? or it will somehow screw my subsequent steps? I am just a beginner and guided help is needed. Thanks a lot

**Comment by ialbert** [comment]
actually, you may not need findutils or even homebrew anymore, 

conda should suffice, 

for now move onto the next step, and I will revisit that section. It used to be required but I believe the conda installation superseeds the brew installation, it is just that one needs to wipe the whole computer to retest and that is a bit tedious

**Comment by ialbert** [comment]
the instructions have been updated.
