### ISSUE TITLE
ploting normalized matrix

### ISSUE THREAD

**Issue by npwjyt** [biostars/biostar-handbook-issues#73]
Hi~

I installed R with conda and also installed DESEQ1, DESEQ2, and EdgeR, and r-gplot also with conda. When I executed 'cat norm-matrix-deseq1.txt | Rscript draw-heatmap.r > output.pdf', I got following message. Can you let me know what I can do? Thanks a lot.

$ cat norm-matrix-deseq1.txt | Rscript draw-heatmap.r > output.pdf
Attaching package: 'gplots'
The following object is masked from 'package:stats':
    lowess

**Comment by ialbert** [comment]
this is not related to the handbook, rather the R packages and internals. It is also a warning and not an error.
