### ISSUE TITLE
Lecture 3 Link to Genomic surveillance

### ISSUE THREAD

**Issue by njbowen** [biostars/biostar-handbook-issues#76]
It seems that a link 

( https://www.biostarhandbook.com/2nd-edition/redo-genomic-surveillance-elucidates-ebola-virus-origin.html  )  

at the beginning of Lecture 3  
(  https://www.biostarhandbook.com/edu/lecture/view/52/  )

should be directed to:

https://www.biostarhandbook.com/2nd-edition/ebolaredo.html

instead.

**Comment by ialbert** [comment]
correction applied.
