### ISSUE TITLE
compiled SRA download and unpack

### ISSUE THREAD

**Issue by njbowen** [biostars/biostar-handbook-issues#77]
the command:
tar xzvf sra-runinfo-2019-02.tar.gz

should be
tar xzvf sra-runinfo-2019-01.tar.gz

the 2019-02 should be 2019-01

from this section of the html handbook:

https://www.biostarhandbook.com/how-much-data-in-the-sra.html

Is it ok to post these here as I work through the book?  is it helpful?  or is it annoying to you.
let me know. thanks again for a great handbook. 

best,
Nathan

**Comment by njbowen** [comment]
from this section of html version of book:
https://www.biostarhandbook.com/how-much-data-in-the-sra.html

**Comment by ialbert** [comment]
I am eager to fix errors - thank you for reporting them.

**Comment by ialbert** [comment]
Fixed in the source - correction will go live in the next update.
