### ISSUE TITLE
When I should start learning python? After completing this book or before ?

### ISSUE THREAD

**Issue by arriyaz** [biostars/biostar-handbook-issues#78]
I'm from a genetics background. Recently I've started learning Bioinformatics from BiostarHandbook. As far as I know, bioinformatics requires decent programming knowledge. So, I'm planning to learn python. But, I'm a little confused, do I need prior programming knowledge to understand the topics in BiostarHandbook?
Or, I should learn python after completing this book...

**Comment by ialbert** [comment]
Bioinformatics does not require programming in the traditional sense of having to learn a programming language from ground up. It requires the use of Unix tools and some scripting skills.
