### ISSUE TITLE
Why links copied from ebook do not work in terminal?

### ISSUE THREAD

**Issue by arriyaz** [biostars/biostar-handbook-issues#79]
I always type the code manually in the terminal. But you know web links are complex and it is always tedious to type them. So, I tried to copy only the links from the ebook version of Biostar Handbook.
Surprisingly, these copied link doesn't work in the terminal,  and even I tried to put these links in the address bar of my web browser, they showed an error. For example:
Link 1: ftp://​ftp.​ebi.​ac.​uk/​pub/​databases/​gencode/​Gencode_​human/​release_​29/
Link 2: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/

Here, Link 1 is copied from ebook and Link 2 found from manual searching from the internet. Though both links are exactly the same, Link 1 does not work in the terminal with codes, even in the address bar, where Link 2 works fine.

You may suggest me, to find the link from internet, Yes! now I'm exactly doing this, though sometimes it is grievous to find the exact link.

But, My curiosity is, Why links copied from the book do not work directly?

**Comment by ialbert** [comment]
The links look the same but the non-working version contains invisible characters, that are not displayed. It is not yet clear to me if it is present in all ebooks or just ones opened when certain other languages are enabled.

Basically the link that does not work has the following form:

`ftp://ftp.ebi.ac.uk/%E2%80%8Bpub/%E2%80%8Bdatabases/%E2%80%8Bgencode/%E2%80%8BGencode_%E2%80%8Bhuman/%E2%80%8Brelease_%E2%80%8B29/`

The `%E2%80%8B` characters do not have a width on the display but do have meaning on the web. If you paste the above link you will see that it will show in the bar as:

`ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/`

but will not work.

I will investigate and comment here on what I find. What language is your system set to?

**Comment by arriyaz** [comment]
My system is in English.

**Comment by ialbert** [comment]
I have tested this on a Mac and the link copied over correctly. But clearly there are many ways to copy over links from ebooks.

Can you please let me know what operating system you were using and how you copied the link over. I

**Comment by arriyaz** [comment]
I am using Ubuntu. I use Calibre ebook reader for reading the book. To copy the links I just select the texts in Calibre and follow as usual copy-paste method.

But I found a temporary solution to this problem. After copying from ebook-reader I paste the text into notepad++ where it shows some invalid boxes in between texts of the link. Then I remove the boxes and copy the link and it works fine.

**Comment by ialbert** [comment]
Upon further investigation, I have come to understand more details about this issue.  The character in question is the so-called zero-width-space:

https://en.wikipedia.org/wiki/Zero-width_space

and allows links to be shown wrapped even though otherwise they would form one long word. The ebook itself does not contain this character, it is the rendering of it via Calibre and the copy-paste implemented in the Linux version of Calibre that appears to cause the problem.
