### ISSUE TITLE
Linux Bash Shell on Windows 10- Known Perl Installation Issues

### ISSUE THREAD

**Issue by greggjm** [biostars/biostar-handbook-issues#8]
Has anybody successfully installed all necessary components from Conda as described in the biostar handbook?

It seems there is an issue with perl running on windows 10. [It's possible to fix this issue](https://github.com/Microsoft/BashOnWindows/issues/186#issuecomment-240591395) but that would mean installing the programs from source instead of conda. The particular issue with conda installing perl can be [found here](https://github.com/conda/conda/issues/4827). 

I'm afraid I haven't found an easy way around this. I'm using the anniversary build Windows 10. From the first link, it seems Microsoft is aware of the issue and has fixed it (along with adding additional improvements) in the creators update rumored to be released around April 17th. 

My question is has anybody encountered and surmounted this obstacle in conda? If not, it would probably be better to hold off on creating a solution until after the creator update when they can apply a patch.

**Comment by ialbert** [comment]
Which tool does not work for you? 

I ran everything on Windows and I also taught it in class and AFAIK everything worked other than fastq-dump.

entrez-direct has to be installed from source.

**Comment by greggjm** [comment]
You are correct, perl-lwp-protocol-https and entrez-direct fail to install using conda. Both install the additional perl package which fails during the extraction process. 

They can be installed from source and I'm guessing since you were able to get it working that there weren't any further dependency conflicts from packages installed through conda? I knew entrez could be installed from source but I didn't know if perl-lwp-protocol would function in a similar manner.

Aside from that, how did you set up conda environments for specific tools (hisat, tophat, cutadapt) to use specific python versions for installation and use?

**Comment by ialbert** [comment]
The versions installed by conda is obsolete 5.80 and will not work even if you got those libraries installed. The latest release here is 6.50

ftp://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/versions/

So this is a matter of fixing it with bioconda.

I had been in contact with the primary developer of it and if I recall correctly he stated the new version does not need the extra libraries.

**Comment by ialbert** [comment]
Let me retract that - I installed entrez-direct with bioconda on Linux and it worked fine.

I will check the Windows Ubuntu later today.

**Comment by ialbert** [comment]
Following the instructions in the doctor.py fixme:

```
mkdir -p ~/src
curl ftp://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/edirect.zip > ~/src/edirect.zip
unzip -o ~/src/edirect.zip  -d ~/src
echo 'export PATH=~/src/edirect:$PATH' >> ~/.bashrc
source  ~/.bashrc
```

installs efetch for me in a working state:

```
$ esearch --help
esearch 6.50
```

**Comment by greggjm** [comment]
Thanks, the rest I wrote to install from source. When would perl-lwp-protocol-https be needed for the purposes of this book?

**Comment by ialbert** [comment]
I realized that when using conda on linux the normally installed perl libraries may become shadowed by the conda environment leading to very annoying situations where a tool that used to work suddenly fails.

The default perl environment in conda does not install two packages:

    perl-lwp-simple
    perl-html-parser

installing these fixed the problem.

**Comment by greggjm** [comment]
Took the advice on page 587 of the handbook too literally by attempting to perform all work in the unix folder.

The issue was that I extracted miniconda to the unix folder outside of the linux subsystem instead of within the home directory itself. When extracting perl windows had an issue with one of the files containing a semicolon `:` in the file name. Only the packages requiring perl had this conflict. 

Installing miniconda to the home directory fixed the issue. Life just became much easier.
