### ISSUE TITLE
curl for bash setup seems to fail

### ISSUE THREAD

**Issue by Sean-McCaffrey** [biostars/biostar-handbook-issues#81]
First time linux user here using Ubuntu 18.04.2 LTS with Windows 10 subsystem for Linux and trying to setup up the shell. curl for http://data.biostarhandbook.com/install/bash_profile.txt >> ~/.bash_profile and ~/.bashrc seems to fail. The output I receive is for both is:

$ curl http://data.biostar.com/install/bash_profile.txt >> ~/.bash_profile
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

With the complete lack of time I suspect that it is not receiving any data. When using cat on bash_profile is empty and bashrc has text but doesn't seem to have anything from the biostar url added. Using the --head command it suggests that the connection with biostar's url is not being made.

$ curl --head http://data.biostar.com/install/bash_profile.txt
HTTP/1.1 301 Moved Permanently
Date: Wed, 17 Jul 2019 20:54:27 GMT
Location: http://alere.com
Content-Length: 0
X-ORACLE-DMS-ECID: bbbae386-5743-42f3-90ab-ccb5b58b9936-3e21275f
X-ORACLE-DMS-RID: 0

I can follow the hyperlink supplied by the text the internet browser running on windows. Any suggestions on what could be going wrong and how to handle it?

**Comment by ialbert** [comment]
In your example you are using a different domain `data.biostar.com` The correct domain is `data.biostarhandbook.com`. Running:

    curl http://data.biostarhandbook.com/install/bash_profile.txt

produces the expected output on my system:
```

#
# Source the settings from .bashrc.
#
if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi
```

**Comment by Sean-McCaffrey** [comment]
Thanks for your time. Glad and embarrassed it was something so simple.

**Comment by ialbert** [comment]
No problem - been there myself. The real headscratchers are often things that we can't see  because they are *too* obvious -  we are used to dealing with and solving difficult problems.
