### ISSUE TITLE
`dwgsim` is used in "Introduction to Variant Calling" but not listed in list of packages to install in conda environment

### ISSUE THREAD

**Issue by RamRS** [biostars/biostar-handbook-issues#83]
The "Introduction to Variant Calling" section uses `dwgsim`, but this tool is not listed among the tools for conda to install while setting up the environment. See: https://www.biostars.org/p/392078/

I think http://data.biostarhandbook.com/install/conda.txt needs to be updated with `dwgsim` (available on bioconda channel)

**Comment by ialbert** [comment]
There used to be a problem with dwgsim in that it required an older version of perl (for no good reason though) that interfered with the other software) thus dwgsim used to be installed, separately into a different environment and not into the main environment. 

I have to check if the dependency is still there.

**Comment by RamRS** [comment]
Or we could mention on the handbook page that it needs to be installed separately.

**Comment by ialbert** [comment]
I have added a mention that `dwgsim` needs to be installed separately.
