### ISSUE TITLE
miniconda installation: could not resolve host

### ISSUE THREAD

**Issue by HMcBain** [biostars/biostar-handbook-issues#84]
Hi, 
when I tried to install miniconda on my mac according to section 8.6 of the manual, I don't see the license agreement, but instead get the following: 
curl: (6) Could not resolve host: bash
curl: (6) Could not resolve host: Miniconda3-latest-MacOSX-x86_64.sh

please advise. Thanks

**Comment by ialbert** [comment]
you need to show the command that you are typing, and the full error 

from the description, it sounds like you are running it differently,

**Comment by HMcBain** [comment]
Hi,
Thanks for your reply. Here is the whole text, done on  anew terminal:
curl -OL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh bash Miniconda3-latest-MacOSX-x86_64.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
100 71.7M  100 71.7M    0     0  3330k      0  0:00:22  0:00:22 --:--:-- 4672k
curl: (6) Could not resolve host: bash
curl: (6) Could not resolve host: Miniconda3-latest-MacOSX-x86_64.sh

In case it has any relevance, I earlier had to  repeat the libraries installation in section 122.4 because I mistyped hdf5 bison as hdf5bison, but it worked when I went back and retyped. 
 correctly. 
Thanks for your help!

**Comment by ialbert** [comment]
you have two put two separate commands one a single line, the first command is

`curl -OL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh `

once that completes run the second command

`bash Miniconda3-latest-MacOSX-x86_64.sh`

**Comment by HMcBain** [comment]
Thanks- sorry, I'm new to all this. The first command worked:
curl -OL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 71.7M  100 71.7M    0     0  4117k      0  0:00:17  0:00:17 --:--:-- 5327k

-so I then entered the second line, but got the following: 
bash Miniconda3-latest-MacOSX-x86_64.sh
bash: Miniconda3-latest-MacOSX-x86_64.sh: No such file or directory

**Comment by ialbert** [comment]
Actually, I copied your commands and did notice how you have another mistake there. 

You are downloading the Linux, version of Miniconda but you end up invoking the other version the (Mac version). Stick to the one that matches your operating system.

Go back to the commands in the book, and copy them over one at a time.

**Comment by HMcBain** [comment]
Hi,
Thanks for the picking up this error. Looks like a typo, as I copied it directly from the book pdf, so I rechecked where I copied it from just now- it has the following:

Open a Terminal then on MacOS execute:
curl -OL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh bash Miniconda3-latest-MacOSX-x86_64.sh

I am using MacOSX, so presumably I just substitute that for Linux in the top line.
Thanks again for your help

**Comment by ialbert** [comment]
Apologies for that, that typo has been long fixed on the web as seen here:

https://www.biostarhandbook.com/computer-setup.html

In general, when using the book to copy commands we recommend using the website for two reasons, 

1. the website has all the fixes to all typos and corrections
2. when you copy-paste commands from the PDF the new lines can get messed up, whereas the website should work properly

**Comment by HMcBain** [comment]
Thanks- I will stick to the website in future. 

BTW, very impressed with the level of support you provide. For a relative novice working alone, it makes all the difference.
