### ISSUE TITLE
SSL module is not avavilable

### ISSUE THREAD

**Issue by criscruz43** [biostars/biostar-handbook-issues#85]
hi all my laptop has Linux 16. 4 lts. the following message apear when I tried to do an update or install 

$ conda update -y -n base conda
Solving environment: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/bioconda/noarch/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError("Can't connect to HTTPS URL because the SSL module is not available.",),)

**Comment by ialbert** [comment]
this problem was present in the past, then got fixed, but perhaps rears its head again

See this:

https://github.com/ContinuumIO/anaconda-issues/issues/6424

one fix in the past was to do:

`execstack -c libcrypto.so.1.0.0`

**Comment by criscruz43** [comment]
Hi ialbert

I already did that but nothing happened.
If I want to re install all ; what I have to do ? thanks so much

**Comment by ialbert** [comment]
delete the miniconda3 directory
`
rm -r miniconda3
`
then start the process again. Make sure to download the newest miniconda installer.

Did you have  previous miniconda or the newest version already?

**Comment by criscruz43** [comment]
Hi.

I have previous version I think.
I installed miniconda following the steps and conman line described in
Biostar handbook 2018 version.

How can I sure I will install new version?

Thanks a lot

Christopher

**Comment by ialbert** [comment]
ok, that is the problem, uninstall the whole thing and start with the fresh proper install with the latest conda. 

The old conda had that nasty bug that you ran into.

**Comment by criscruz43** [comment]
OK thanks.

So you mean that I just have following the same command lines and the new
miniconda version will be installed?

Sorry but Im a biginer.

Best

Chris

**Comment by ialbert** [comment]
delete the previous conda install and try again with the new one.

perhaps it is best if you install the new Linux Bash as well.

Follow the book, install the Ubuntu windows app, it is much simpler than it used to be, then follow along the same way.

**Comment by criscruz43** [comment]
OK. Thanks so much

**Comment by criscruz43** [comment]
Hi, just to clarify. Mi laptop is based on only in Linux not in windows.

**Comment by criscruz43** [comment]
Thanks!
