### ISSUE TITLE
Bioinformatics Tool Installation 8.9

### ISSUE THREAD

**Issue by sebastianjuhl** [biostars/biostar-handbook-issues#86]
**After creating+entering bioinfo environment 
Executed curl http://data.biostarhandbook.com/install/conda.txt | xargs conda install -y
I installed efetch separately to access NCBI then reinstalled the bioinfo env to attempt a clean tool install** 

curl http://data.biostarhandbook.com/install/conda.txt | xargs conda install -y
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   244  100   244    0     0   1626      0 --:--:-- --:--:-- --:--:--  1637
Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

  - blast -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0']
  - bowtie2 -> python[version='2.7.*,3.6.*,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0']
  - cutadapt -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0']
  - freebayes -> python[version='3.5.*,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0']
  - hisat2 -> python[version='2.7.*,3.4.*,>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0']
  - picard -> python[version='2.7.*,3.6.*']

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to.  Your current python version
is (python=3.7).  Note that conda will not change your python version to a different minor version
unless you explicitly specify that.

The following specifications were found to be incompatible with each other:

Package pip conflicts for:
cutadapt -> dnaio[version='>=0.3'] -> xopen[version='>=0.5.0'] -> bz2file -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip
hisat2 -> python[version='2.7.*,3.4.*,>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip
freebayes -> python[version='3.5.*,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip
blast -> boost[version='1.64.*,>=1.66.0,<1.66.1.0a0'] -> numpy[version='1.11.*,1.12.*,>=1.8,>=1.9.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip
bowtie2 -> python[version='2.7.*,3.6.*,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip
picard -> python[version='2.7.*,3.6.*'] -> pip
python=3.7 -> pip
trimmomatic -> python -> pip
Package certifi conflicts for:
hisat2 -> python[version='2.7.*,3.4.*,>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel -> setuptools -> certifi[version='>=2016.09']
bowtie2 -> python[version='2.7.*,3.6.*,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel -> setuptools -> certifi[version='>=2016.09']
freebayes -> python[version='3.5.*,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel -> setuptools -> certifi[version='>=2016.09']
blast -> boost[version='1.64.*,>=1.66.0,<1.66.1.0a0'] -> numpy[version='1.11.*,1.12.*,>=1.8,>=1.9.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel -> setuptools -> certifi[version='>=2016.09']
trimmomatic -> python -> pip -> wheel -> setuptools -> certifi[version='>=2016.09']
picard -> python[version='2.7.*,3.6.*'] -> pip -> wheel -> setuptools -> certifi[version='>=2016.09']
cutadapt -> dnaio[version='>=0.3'] -> xopen[version='>=0.5.0'] -> bz2file -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel -> setuptools -> certifi[version='>=2016.09']
python=3.7 -> pip -> wheel -> setuptools -> certifi[version='>=2016.09']
Package wheel conflicts for:
hisat2 -> python[version='2.7.*,3.4.*,>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel
cutadapt -> dnaio[version='>=0.3'] -> xopen[version='>=0.5.0'] -> bz2file -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel
trimmomatic -> python -> pip -> wheel
blast -> boost[version='1.64.*,>=1.66.0,<1.66.1.0a0'] -> numpy[version='1.11.*,1.12.*,>=1.8,>=1.9.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel
python=3.7 -> pip -> wheel
freebayes -> python[version='3.5.*,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel
picard -> python[version='2.7.*,3.6.*'] -> pip -> wheel
bowtie2 -> python[version='2.7.*,3.6.*,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel
Package setuptools conflicts for:
cutadapt -> dnaio[version='>=0.3'] -> xopen[version='>=0.5.0'] -> bz2file -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel -> setuptools
trimmomatic -> python -> pip -> wheel -> setuptools
bowtie2 -> python[version='2.7.*,3.6.*,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel -> setuptools
picard -> python[version='2.7.*,3.6.*'] -> pip -> wheel -> setuptools
blast -> boost[version='1.64.*,>=1.66.0,<1.66.1.0a0'] -> numpy[version='1.11.*,1.12.*,>=1.8,>=1.9.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel -> setuptools
python=3.7 -> pip -> wheel -> setuptools
hisat2 -> python[version='2.7.*,3.4.*,>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel -> setuptools
freebayes -> python[version='3.5.*,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel -> setuptools

**The first thought I have is I had python previously installed with version 3.7.4 but that shouldn't be an issue should it?

and of course when running doctor.py** 

_# Doctor! Doctor! Give me the news.
_# The ~/bin folder is not in your PATH!
_# Checking 13 symptoms...
_# ERROR! Missing program: bwa
_# ERROR! Missing program: datamash
_# ERROR! Missing program: fastqc
_# ERROR! Missing program: hisat2
_# ERROR! Missing program: seqret
_# ERROR! Missing program: subread-align
_# ERROR! Missing program: featureCounts
_# ERROR! Missing program: efetch
_# ERROR! Missing program: esearch
_# ERROR! Missing program: samtools
_# ERROR! Missing program: fastq-dump
_# Optional program not found: global-align.sh
_# Optional program not found: local-align.sh
_# Your system shows 12 errors.
_# See also: doctor.py --fixme_

**Comment by ialbert** [comment]
I would recommend to delete and recreate the environment. 

It seems that have installed the wrong python into the environment.

make sure to use the installation command exactly as the book does. 

    conda create -y --name bioinfo python=3.6

**Comment by sebastianjuhl** [comment]
That was the issue 
I was relying on a local install of python 
Thanks!
