### ISSUE TITLE
“Bash Unix for Windows.”

### ISSUE THREAD

**Issue by julianstanley** [biostars/biostar-handbook-issues#89]
From ["What is bioinformatics"](https://www.biostarhandbook.com/what-is-bioinformatics.html):
> “Bash Unix for Windows.”

Just a small thing--is this the correct name?

I think it's the "Windows Subsystem for Linux" now, as a proper GNU/Linux system, replacing the Windows Services for Unix ([wikipedia entry](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux), [microsoft docs](https://docs.microsoft.com/en-us/windows/wsl/install-win10), [canonical announcement for proper GNU/Linux](https://ubuntu.com/blog/canonical-announces-support-for-ubuntu-on-windows-subsystem-for-linux-2))

**Comment by ialbert** [comment]
Indeed, that paragraph was written a few years ago when this virtualization software did not have an official name. The change has been made will go out with the next update.
