### ISSUE TITLE
Chapter  VI visualizing example issue AF086833

### ISSUE THREAD

**Issue by MirrorReaper** [biostars/biostar-handbook-issues#90]
Im having an issue that when I get the fasta file directly for AF086833 via efetch (unlike the book where seqret tool is used to get the fasta from gb file) the gff file does not show any features at all., the track is empty.

While when doing exactly as the book (getting gb format, then using seqret tool to get both fasta and gff formats)  all seems good 

Why this discrepancy?

**Comment by ialbert** [comment]
can you please link in the exact commands that do not seem to work

**Comment by MirrorReaper** [comment]
Getting the genbank file
`efetch -db nuccore -id AF086833 -format gb >AF.gb`

Getting the gff file from gb bank
`cat AF.gb | seqret  -filter  -feature  -osformat gff3 > AF.gff`

Getting the fasta format
`efetch -db nuccore -id AF086833 -format fasta >AF.fa`

Indexing the fasta file
`samtools faidx AF.fa`

When using the  AF.fa as the genome  and loading the gff file , the track show nothing

![2019-10-16](https://user-images.githubusercontent.com/46757142/66904107-3ae6f880-f00c-11e9-8f63-6da3dcf52fc2.png)


While when getting the fasta format from the genbank file

cat AF.gb | seqret -filter -feature -osformat fasta > AF-2.fa

![2019-10-16 (1)](https://user-images.githubusercontent.com/46757142/66904169-4df9c880-f00c-11e9-92d3-d5c04d8153ee.png)

**Comment by MirrorReaper** [comment]
Thanks.

It is really frustrating indeed.

Thanks again.
