### ISSUE TITLE
Problems with SRA: "curl: (9) Server denied you to change to the given directory"

### ISSUE THREAD

**Issue by Gabriel-Hideki** [biostars/biostar-handbook-issues#91]
Good evening, everyone.

Following instructions of the Biostar Handbook, I tried to download an SRA dataset through this command:

`wonderdump -X 10000 --split-files SRR1972739`

The file was not downloaded and I got the following message on my Windows Bash terminal:

`curl: (9) Server denied you to change to the given directory`

Does anyone know how to proceed in this situation? I have just started studying bioinformatics, I'm still learning the basic concepts and any observations you have would be welcome.

Thank you all!

**Comment by ialbert** [comment]
There is no need to use `wonderdump` anymore. 

All references to that program should be removed from the book, sorry if some are still there.

Use `fastq-dump` as for all other platforms.

**Comment by Gabriel-Hideki** [comment]
Hi, Istvan!
I'm actualy using an outdated version of the book. But I switched to `fastq-dump` and it worked just fine. 
Thnk you!
