### ISSUE TITLE
setup windows 8

### ISSUE THREAD

**Issue by gsk7757** [biostars/biostar-handbook-issues#92]
Hello, 
I was wondering if bash can be used on windows 8 computer?
Thanks,
Shiva

**Comment by ialbert** [comment]
It would only work as a VirtualBox approach

**Comment by ialbert** [comment]
It would only work as a VirtualBox approach

https://www.virtualbox.org/

but that is not something I would recommend to beginners. It is a bit more complicated.

**Comment by gsk7757** [comment]
Thanks Dr. Albert. May I know what would be the best platform to get started? would it be a windows with Ubuntu or a Mac with Linux?

**Comment by ialbert** [comment]
The best platforms are Apple Macs. They are a type of Unix so no Linux needs to be installed on them.

In addition, the quality of the hardware and usability is also the best.

**Comment by gsk7757** [comment]
Also, would you please let me know the minimum hardware requirement needed to run basic analysis?

**Comment by ialbert** [comment]
Your priority should be to learn and for that any computer will work. I use a Macbook Air for all coding you can learn and develop any analysis on a laptop. Running full analyses always depend on many factors, consider that a bacterial genome is three orders of magnitude smaller than a human genome, and there many other considerations. Once you learn how to run analyses you'll also gain some understanding on what systems you might need to do full analyses.

**Comment by gsk7757** [comment]
Thanks a lot for your quick responses.
