### ISSUE TITLE
Ubuntu start up error

### ISSUE THREAD

**Issue by fanzhaom** [biostars/biostar-handbook-issues#94]
Hello there,

I am using a Windows 10 machine with Ubuntu installed.

I followed each step on the book. But after I set up the bioinfo environment, I started to have this error each time I open Ubuntu.

**Traceback (most recent call last):
  File "`stdin`", line 3, in `module`
ImportError: No module named conda**

Other than that, the doctor.py works well, so does the Entrez Direct. So I am not sure how this error would affect me yet. Appreciate your help.

**Comment by fanzhaom** [comment]
It is File <stdin>, not sure why it fails to appear

**Comment by ialbert** [comment]
This feel like your terminal tries to start conda on opening a terminal, which it should most certainly not do

look into the .bashrc and .bash_profile files. Show me the output of

     cat ~/.bashrc

and 

     cat ~/bash_profile

(just make sure you don't have anything there that is personally identifiable, passwords etc) if you are new to Ubuntu that's should not be problem, normally bash startups do not have such information only if you put it there.

**Comment by fanzhaom** [comment]
Hi Istvan,

Here is my bashrc:
#
# A minimal BASH profile.
#

# ON Mac OS uncomment the line below.
# alias ls='ls -hG'

# On Linux use the following:
# alias ls='ls -h --color'

# Safe versions of the default commands.
# Will ask permissions before overwriting files.
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'

# Extend the program search PATH and add the ~/bin folder.
export PATH=~/bin:$PATH

# Makes the prompt much more user friendly.
# But I do agree that the command to set it up looks a bit crazy.
export PS1='\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\n\$ '

# This is required for Entrez Direct to work.
# Disables strict checking of an encryption page.
export PERL_LWP_SSL_VERIFY_HOSTNAME=0

# This is necessary for the sort to work correctly.
export LC_ALL=C

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/fanzhaom_unix/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/fanzhaom_unix/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/fanzhaom_unix/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/fanzhaom_unix/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

And for bash_profile, it says:
cat: /home/fanzhaom_unix/bash_profile: No such file or directory

Thank you for your help!

**Comment by ialbert** [comment]
sorry make it .bash_profile

    cat ~/.bash_profile

when you copy select the code you paste in then  format as code (the `<>` symbol above)  so that it looks like this:

```
one
two
three
```

use the Preview button to see what it will look like

**Comment by fanzhaom** [comment]
Sorry for the format issue! I have pasted the result from bashrc again:
```
#
# A minimal BASH profile.
#

# ON Mac OS uncomment the line below.
# alias ls='ls -hG'

# On Linux use the following:
# alias ls='ls -h --color'

# Safe versions of the default commands.
# Will ask permissions before overwriting files.
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'

# Extend the program search PATH and add the ~/bin folder.
export PATH=~/bin:$PATH

# Makes the prompt much more user friendly.
# But I do agree that the command to set it up looks a bit crazy.
export PS1='\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\n\$ '

# This is required for Entrez Direct to work.
# Disables strict checking of an encryption page.
export PERL_LWP_SSL_VERIFY_HOSTNAME=0

# This is necessary for the sort to work correctly.
export LC_ALL=C

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/fanzhaom_unix/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/fanzhaom_unix/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/fanzhaom_unix/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/fanzhaom_unix/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```
For the bash_profile, it is:
```
#
# Source the settings from .bashrc.
#
if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi
```

**Comment by ialbert** [comment]
Le'ts try the following:

This will download new versions of the shell profileL


```
curl http://data.biostarhandbook.com/install/bash_profile.txt > ~/.bash_profile
curl http://data.biostarhandbook.com/install/bashrc.txt > ~/.bashrc
```

then reinitialize `conda`

`conda init`

then open a new terminal

**Comment by fanzhaom** [comment]
It seems to have the same problem after I did those commands.
```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
ImportError: No module named conda
```
And for the bashrc:
```
#
# A minimal BASH profile.
#

# ON Mac OS uncomment the line below.
# alias ls='ls -hG'

# On Linux use the following:
# alias ls='ls -h --color'

# Safe versions of the default commands.
# Will ask permissions before overwriting files.
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'

# Extend the program search PATH and add the ~/bin folder.
export PATH=~/bin:$PATH

# Makes the prompt much more user friendly.
# But I do agree that the command to set it up looks a bit crazy.
export PS1='\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\n\$ '

# This is required for Entrez Direct to work.
# Disables strict checking of an encryption page.
export PERL_LWP_SSL_VERIFY_HOSTNAME=0

# This is necessary for the sort to work correctly.
export LC_ALL=C

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/fanzhaom_unix/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/fanzhaom_unix/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/fanzhaom_unix/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/fanzhaom_unix/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```
for the bash_profile:
```
#
# Source the settings from .bashrc.
#
if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi
```

**Comment by fanzhaom** [comment]
@ialbert I still get the same problem and I was wondering if you could further help. Appreciate it!

**Comment by ialbert** [comment]
what version is your conda:

    conda -V

this feels some sort of conda problem, it should not do that, do the commands otherwise work?

**Comment by ialbert** [comment]
one other possiblity is to redo that the conda installation step, it feels like something went wrong there.

    rm -rf miniconda3
    rm -f .bashrc
    rm -f .bash_profile

then redo the steps starting with miniconda installation:

```
curl http://data.biostarhandbook.com/install/bash_profile.txt >> ~/.bash_profile
curl http://data.biostarhandbook.com/install/bashrc.txt >> ~/.bashrc
curl -OL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
```

then go on with creating the environments.

**Comment by fanzhaom** [comment]
Conda version: 4.8.0
I am going to remove conda and start over. Thank you!

**Comment by fanzhaom** [comment]
After I reinstall the whole thing, I am not getting the error again. Really appreciate your help!

**Comment by ialbert** [comment]
great to hear.
