### ISSUE TITLE
DEseq R code problem

### ISSUE THREAD

**Issue by theokirkland** [biostars/biostar-handbook-issues#97]
I have Deseq installed using Bioconductor and RStudio.

When I try to use the following
wget -q -nc  http://data.biostarhandbook.com/rnaseq/code/deseq1.r it does not load an R script
I get
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/bin/wget
  Reason: image not found
Abort trap: 6

Any ideas?

Thx Theo

**Comment by ialbert** [comment]
This looks like some sort of conflict with OpenSSL when installed in different ways

https://github.com/kelaberetiv/TagUI/issues/86

if your `wget` is not working the whole installation is suspect.

**Comment by kensoh** [comment]
Adding on, it looks like wget is using OpenSSL v1.0, which is deprecated from Homebrew, and also macOS newer versions don't come with OpenSSL anymore. An ideal solution would be getting an updated version of wget if available that works with the newer macOS releases.

If that's not viable, then maybe use the curl command which can also download files from the internet. If that's not possible, then following will install OpenSSL v1.0 on macOS. I created below custom solution to solve this problem for an open-source project that I maintain, so that users don't have to install Xcode and build the OpenSSL if using the existing Homebrew solution.

```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update && brew upgrade
brew uninstall openssl; brew uninstall openssl; brew install https://github.com/tebelorg/Tump/releases/download/v1.0.0/openssl.rb
```

**Comment by theokirkland** [comment]
You’re absolutely right.  Once I downloaded wget with home-brew I got the script.  However the line of code will not run.  I have R open in RStudio and DESeq installed, but the  error is

cat simple_counts.txt | Rscript deseq1.r 3x3 > results.txt
Error in library(DESeq) : there is no package called 'DESeq'
Execution halted


I’m clearly having a problem running R from the command line.  I tried running the script in RStudio but couldn’t get that to work either.

Thanks for your help.

Theo

**Comment by ialbert** [comment]
looks like `wget` has now been installed correctly. That solves the original problem.

For the R script to work, you need to install the libraries into R. The chapter:

* https://www.biostarhandbook.com/rnaseq-statistics.html

has more details

**Comment by kadavesh** [comment]
> looks like `wget` has now been installed correctly. That solves the original problem.
> 
> For the R script to work, you need to install the libraries into R. The chapter:
> 
> * https://www.biostarhandbook.com/rnaseq-statistics.html
> 
> has more details

Following the instructions in the Biostar Handbook, I run into the sample problem:
Error in library(DESeq) : there is no package called 'DESeq'
Execution halted
(bioinfo) 

I have RStudio globally installed. Then I installed DEseq, DEseq2, edgeR, and gplots in the RStuio.

**Comment by ialbert** [comment]
these problems usually have to do with multiple R versions on the system.

The book has been updated with installation instructions from the command line to ensure the same R version is used.
