### ISSUE TITLE
using efetch for Entrez direct  (Entrez Direct by Example chapter)

### ISSUE THREAD

**Issue by eflasch** [biostars/biostar-handbook-issues#98]
When trying to use efetch I get the following:
Can't locate XML/Simple.pm in @INC (you may need to install the XML::Simple module) .
pus a long path.  Any ideas, thank you.

Edward Flaschner

**Comment by ialbert** [comment]
make sure to activate the bioinfo environment and that you followed the instructions in the book.

if in doubt reinstall everything, conda, bioconda etc.
