### ISSUE TITLE
Guide for contributions

### ISSUE THREAD

**Issue by bsipos** [biostars/biostar-handbook-issues#99]
Is there a guide for contributing to the BioStars books?

**Comment by ialbert** [comment]
yes we have a guide to contributing on the following page:

https://www.biostarhandbook.com/about-the-author.html

**Comment by bsipos** [comment]
I would like to potentially contribute (again). Could you try giving me access to the source? It did not work last time for some reason but maybe the second time is the charm. :)

**Comment by ialbert** [comment]
currently, the goal is to make the book is a separate repository, where everyone can set it up however they want it. The mono-repository was too hard to deal with. We are slowly migrating all content to individual books.

So the recommended practice for adding new pages on any content is very straightforward, make a repo public or private (if private allow us to pull from). 

Generate markdown files into it with any editor you wish and we'll clone your repo and add link your contents to the table of contents.

For fixing up new content tell us which chapter you want to work on and we can either let you edit that repo or if the refactoring is not yet done we'll start that.

**Comment by bsipos** [comment]
That sounds like a sensible approach when in full swing. Will the markdown for the different books be available for folks who want to do fixes later on? It would make things easier.

**Comment by ialbert** [comment]
I have not thought of that yet, needs to be evaluated,, the prior experiment in allowing people to work on the book was partially successful, the vast majority did not contribute in the end.

**Comment by bsipos** [comment]
Well, nevermind. Indeed if there is a will, there is way. :)
